// ---------------------------------------------------------------------------
// AI Prompts data — edit this file to add, change, or remove prompts.
// Each section maps to a section on the access page.
//
// ORDERING RULE: newest collection goes at the TOP of this file.
// Add new COLLECTION arrays above MARBLE_CAFE_SERIES, then add the section
// to the page in app/ai-prompts/access/[token]/page.tsx (same top order).
// ---------------------------------------------------------------------------

export type PromptCard = {
  number: string
  title: string
  id: string
  whenToUse: string
  mood: string
  prompt: string
  exampleImage?: string
}

export const REUSABLE_STARTER =
  "Use my uploaded selfie as the facial identity reference. Preserve my facial identity, age, skin tone, facial structure, and natural features. Do not alter my face, smooth my skin unnaturally, or create a more idealised version of me. You may change the styling, outfit, background, lighting, crop, camera angle, pose energy, and mood. The face stays the same. Everything else can transform. The result should look like a photograph, not AI art."

export const MAIN_LOOKS: PromptCard[] = [
  {
    number: "01",
    id: "bw-supermodel",
    title: "90s Black and White Supermodel",
    whenToUse: "You want something dramatic for a black and white post. Strong, fashion-editorial, and scroll-stopping.",
    mood: "contrast · 90s editorial · monochrome · film",
    prompt:
      "Use my uploaded selfie as the facial identity reference. Preserve my facial identity, age, skin tone, facial structure, and natural features. Do not alter my face, smooth my skin unnaturally, or create a more idealised version of me. You may change the crop, lighting, background, expression energy, and overall mood entirely. Recreate this as a high-contrast black and white portrait in the style of a 1990s fashion magazine editorial. Strong directional light that defines the cheekbones and jaw. One soft flash reflected in the eyes. Natural skin texture with visible pores. Subtle silver halide film grain. Studio-gray background. The crop should feel like a magazine portrait, not a selfie. The expression should feel direct, cool, and present. Photographic, not illustrated. This should look like it was shot on film in a photography studio, not generated by AI.",
  },
  {
    number: "02",
    id: "car-mirror-noir",
    title: "Car Mirror Lipstick Noir",
    whenToUse: "You want something cinematic and unexpected. One of the most distinctive looks in the pack.",
    mood: "cinematic · noir · late night · shadow",
    prompt:
      "Use my uploaded selfie as the facial identity reference. Preserve my facial identity, age, skin tone, facial structure, and natural features. Do not alter my face, smooth my skin unnaturally, or create a more idealised version of me. You may change the crop, angle, lighting, setting, and mood entirely. Create a black and white cinematic portrait seen through a car side mirror. My face fills the mirror, partial and cropped, showing mostly my eyes, nose, and the top of my lips. One hand near my jaw or collarbone. Deep shadow on one side of the face. A single stripe of light crossing the eyes and the bridge of the nose. Rim light from behind on the hair. The blurred car door and mirror frame surround the reflection like a border. Fine film grain. The mood is late night, private, cinematic. Photographic, not illustrated. This should look like a still from a film, not an AI image.",
  },
  {
    number: "03",
    id: "y2k-selfie",
    title: "Compact Camera Y2K Selfie",
    whenToUse: "You want something fun and nostalgic. A lighter post, a throwback feel.",
    mood: "Y2K · direct flash · warm · candid · found photo",
    prompt:
      "Use my uploaded selfie as the facial identity reference. Preserve my facial identity, age, skin tone, facial structure, and natural features. Do not alter my face or create a more idealised version of me. You may change the lighting, colour grade, crop, background, and overall era. Recreate this as a photo taken on a cheap compact digital camera in 2002. Direct on-camera flash hitting my face straight on. Slight overexposure on the forehead and cheekbones from the flash. Warm white balance with a faint yellow cast. Soft flat digital grain, not film grain. The background can shift to a casual indoor setting: a bedroom, bathroom, or kitchen. Add a white timestamp in the bottom right corner. This should look like a photo found in an old digital album, not an AI image.",
  },
  {
    number: "04",
    id: "window-light-brand",
    title: "Window Light Brand Portrait",
    whenToUse: "You need a personal brand photo that looks natural, not corporate. Good for bios, press, and website use.",
    mood: "morning light · approachable · real · personal brand",
    prompt:
      "Use my uploaded selfie as the facial identity reference. Preserve my facial identity, age, skin tone, facial structure, and natural features. Do not alter my face, smooth my skin unnaturally, or create a more idealised version of me. You may change the lighting, background, crop, and overall image quality entirely. Create a personal brand portrait with soft diffused morning window light falling across my face from one side. Clean neutral background in warm white or soft off-white tones. Real skin texture with natural pores visible. Relaxed shoulders, present, grounded. The mood is real and approachable, not corporate, not a studio shot, not aspirational in a manufactured way. It should feel like a photographer came to my home on a quiet morning and found me in good light. Photorealistic, no beauty filter, no dramatic retouching.",
  },
  {
    number: "05",
    id: "mirror-selfie-upgrade",
    title: "Expensive Mirror Selfie Upgrade",
    whenToUse: "You took a mirror selfie but the lighting or background is not working. You want the same moment, elevated.",
    mood: "clean · elevated · editorial · same moment, better light",
    prompt:
      "Use my uploaded mirror selfie as the facial identity reference. Preserve my facial identity, age, skin tone, facial structure, and natural features. Do not alter my face or create a more idealised version of me. Keep my outfit and body position. You may change everything else: the background, the lighting, the room, and the overall quality of the image. Replace the background and room behind me with a clean minimal interior in warm neutral tones, a white wall or pale plaster in soft light. Adjust the lighting to soft and directional, coming from slightly above and to one side. Straighten the composition. Sharpen the mirror detail. Natural skin texture. The result should feel like the same moment, same outfit, same body, same energy, but photographed in a well-styled space by someone who knew what they were doing. Editorial mirror selfie quality. Real, not filtered.",
  },
]

export const BONUS_LOOKS: PromptCard[] = [
  {
    number: "06",
    id: "clean-editorial",
    title: "Clean Editorial Selfie",
    whenToUse: "Your selfie is good but looks casual. You want it to feel polished and shareable.",
    mood: "editorial · soft light · neutral tones · iPhone quality",
    prompt:
      "Use my uploaded selfie as the facial identity reference. Preserve my facial identity, age, skin tone, facial structure, and natural features. Do not alter my face, smooth my skin unnaturally, or create a more idealised version of me. You may change the lighting, background, crop, and overall editorial quality. Turn this into a clean editorial portrait with soft window light, natural skin texture, minimal background in neutral tones, shallow depth of field, and subtle film grain. The result should feel polished but real, like a high-quality iPhone photo with clean editing, not AI art.",
  },
  {
    number: "07",
    id: "narrow-light",
    title: "Narrow Light Portrait",
    whenToUse: "You want a moody, high-contrast look. Works well for quotes and single-image posts.",
    mood: "dramatic · shadow · moody · sharp",
    prompt:
      "Use my uploaded selfie as the facial identity reference. Preserve my facial identity, age, skin tone, facial structure, and natural features. Do not alter my face or smooth my skin unnaturally. You may change the lighting, background, and crop entirely. Create a close-up portrait where most of my face is in deep shadow, with one narrow band of light crossing my eyes and the bridge of my nose. Plain muted gray-blue background. High-contrast cinematic lighting. Sharp focus on the eyes. Realistic photography with soft grain.",
  },
  {
    number: "08",
    id: "bathroom-magazine",
    title: "Bathroom Selfie to Magazine Shot",
    whenToUse: "You have a bathroom selfie you like but it is not quite there yet. Keep the moment, improve everything around it.",
    mood: "editorial · clean · elevated · same moment, better room",
    prompt:
      "Use my uploaded bathroom selfie as the facial identity reference. Preserve my facial identity, age, skin tone, facial structure, and natural features. Do not alter my face or create a more idealised version of me. Keep my hair, outfit, phone, and body position. You may change the lighting, background, room detail, and overall quality. Improve the lighting so it is soft and even. Clean up the background so it is minimal and neutral. Straighten the lines and composition. The result should feel like a high-end editorial bathroom mirror photo, the same moment but photographed well. Real skin texture. Not filtered.",
  },
]

export const WORKFLOW_PROMPTS: PromptCard[] = [
  {
    number: "09",
    id: "selfie-audit",
    title: "Selfie Audit",
    whenToUse: "You know something is off but you cannot identify what. Use this before you try any of the visual prompts.",
    mood: "This prompt does not change your photo. It gives you a written critique.",
    prompt:
      "Analyse this selfie like an iPhone photography coach. Tell me exactly what is working and what is making it look less polished. Give me 5 simple fixes for lighting, angle, pose, crop, and editing. Keep the advice beginner-friendly and specific to iPhone selfies. Give me the fastest way to make this photo look better before I post it.",
  },
  {
    number: "10",
    id: "edit-bridge",
    title: "Prompt-to-Edit Bridge",
    whenToUse: "You love an AI result and want to recreate that same mood in Lightroom or iPhone editing without AI.",
    mood: "This prompt does not change your photo. It gives you manual editing steps.",
    prompt:
      "Look at this AI-edited version of my selfie. Help me recreate the same mood manually in iPhone editing or Lightroom. Break the look into simple steps: exposure, contrast, highlights, shadows, warmth, colour, sharpness, crop, and grain. Keep the steps beginner-friendly. The goal is a natural, realistic result, not an over-edited one.",
  },
  {
    number: "11",
    id: "content-caption",
    title: "Content Caption From My Selfie",
    whenToUse: "You have a photo but do not know what to write. Use this to turn a selfie into an Instagram caption.",
    mood: "This prompt does not change your photo. It generates caption copy.",
    prompt:
      "Use this selfie as the starting point for an Instagram caption. Write a warm, honest caption about showing up online before you feel fully ready. Write it as a real woman speaking to another woman, not as a brand. Keep it short and direct. Include one practical line about using your phone, your face, and everyday life to start building online. End with a soft CTA to comment GUIDE for the free selfie guide.",
  },
  {
    number: "12",
    id: "studio-workflow",
    title: "SSELFIE Studio Workflow",
    whenToUse: "You want a full content plan from one photo. Hook, caption, edit direction, reel idea, and CTA.",
    mood: "This prompt does not change your photo. It generates a content plan.",
    prompt:
      "Act like my personal content assistant. I am uploading one selfie. Give me: 1. what this photo says about me right now, 2. the strongest Instagram hook for this image, 3. one caption idea, 4. one simple edit direction, 5. one carousel or reel idea, 6. the best CTA to use: GUIDE, KIT, or Studio. Keep the advice short, confident, and made for a woman building her brand from her phone.",
  },
]

export const MARBLE_CAFE_SERIES: PromptCard[] = [
  {
    number: "13",
    id: "marble-wine-shot-1",
    title: "Marble Café · Hero Wine Sip",
    whenToUse: "Your hero shot for the series. Intimate, editorial, and fashion-forward. Use this as the single-image post or the carousel cover.",
    mood: "quiet luxury · marble café · wine · editorial · fashion-forward",
    exampleImage: "/images/ai-prompts/marble-wine-shot-1.jpg",
    prompt:
      "Create image 1 of a 6-part editorial photoshoot.\n\nUse the uploaded reference photos as the only source for the person's face and identity. Preserve the person's facial structure, skin tone, hair color, body proportions, age, and natural texture from the reference photos.\n\nScene: an elegant outdoor marble café terrace with gray-white marble walls, dark wooden window frames, a round white marble café table, and a quiet luxury city atmosphere.\n\nOutfit: oversized black structured blazer with strong shoulders, simple fitted white crew-neck top underneath, black sheer floral lace skirt or lace trousers visible in the lower frame. Styling should feel minimal, expensive, and fashion-forward.\n\nAccessories: slim black Celine Triomphe-style oval sunglasses, small polished silver or gold hoop earrings, simple Cartier-style rings, dark burgundy Chanel Le Vernis-style manicured nails, and a black Bottega Veneta Intrecciato-style woven leather handbag placed near the table.\n\nHair: sleek low bun or low ponytail with a clean center part, polished but not overly perfect. Keep the person's natural hair color from the uploaded reference photos.\n\nPose: seated close to the marble table, body angled slightly sideways, one knee raised into the frame with lace fabric visible, holding a large Riedel-style red wine glass near the lips as if taking a sip. Face in three-quarter profile, calm and confident expression, sunglasses on.\n\nCamera: close editorial crop from chest to knee, slightly low and intimate angle, like a candid iPhone fashion photo but polished.\n\nMood: cool, quiet luxury, marble café terrace, Pinterest fashion editorial, feminine but sharp, expensive without looking staged.\n\nLighting: soft natural daylight, muted gray marble tones, black-white contrast, realistic skin texture, subtle film grain, clean shadows.\n\nImage quality: vertical 9:16 portrait, 2K quality, minimum 1440 x 2560 px if available, crisp facial detail, sharp lace texture, sharp blazer structure, realistic wine glass reflections, no blur, no compression softness.\n\nAvoid: distorted hands, extra fingers, warped wine glass, messy jewelry, fake-looking logos, plastic skin, over-smoothed beauty filter, CGI, cartoonish AI style, overly staged stock-photo look.",
  },
  {
    number: "14",
    id: "marble-wine-shot-2",
    title: "Marble Café · Outfit Shot",
    whenToUse: "Slide 2 of the carousel or a standalone outfit post. Shows the full look with the marble setting.",
    mood: "quiet luxury · café · outfit · editorial · effortless",
    exampleImage: "/images/ai-prompts/marble-wine-shot-2.jpg",
    prompt:
      "Create image 2 of the same marble café wine editorial photoshoot.\n\nUse the uploaded reference photos as the only source for the person's face and identity. Preserve the person's facial structure, skin tone, hair color, body proportions, age, and natural texture from the reference photos.\n\nScene: seated at a round white marble café table on an outdoor terrace with gray-white marble walls, dark wood-framed windows, and a clean expensive European city feel.\n\nOutfit: oversized black structured blazer with strong shoulders, fitted white crew-neck top, black sheer floral lace skirt or lace trousers, slim black oval sunglasses, small hoop earrings, simple rings, dark manicured nails.\n\nBrand-coded details: Celine Triomphe-style black oval sunglasses, Bottega Veneta Intrecciato-style black woven leather handbag, Cartier-style rings, Riedel-style red wine glass.\n\nHair: sleek low bun or low ponytail with a center part, polished but natural. Keep the person's natural hair color from the uploaded reference photos.\n\nPose: wider seated outfit shot. The person is leaning back slightly in the chair, one arm resting on the chair or table, the other holding a red wine glass at chest height. One knee is bent and visible with lace texture. The black woven leather handbag sits on the marble table or chair beside her.\n\nExpression: relaxed, cool, confident, not smiling too much. Sunglasses on, head turned slightly away from the camera.\n\nCamera: medium-wide editorial composition with enough space to show the marble wall, table, bag, outfit, lace detail, and wine glass.\n\nMood: quiet luxury café, modern fashion editorial, calm confidence, expensive but effortless.\n\nLighting: soft overcast daylight, muted contrast, realistic shadows, subtle film grain, natural iPhone-editorial sharpness.\n\nImage quality: vertical 9:16 portrait, 2K quality, minimum 1440 x 2560 px if available, sharp outfit silhouette, sharp handbag texture, clear wine glass, crisp lace fabric, no blur, no low-resolution softness.\n\nAvoid: distorted hands, extra fingers, warped glass, fake-looking logos, unrealistic handbag texture, plastic skin, overly commercial pose, CGI.",
  },
  {
    number: "15",
    id: "marble-wine-shot-3",
    title: "Marble Café · Looking Away",
    whenToUse: "The mysterious candid shot. Works for quotes, captions about presence and stillness, or as a mid-carousel break.",
    mood: "candid · mysterious · café moment · quiet · fashion",
    exampleImage: "/images/ai-prompts/marble-wine-shot-3.jpg",
    prompt:
      "Create image 3 of the same marble café wine editorial photoshoot.\n\nUse the uploaded reference photos as the only source for the person's face and identity. Preserve the person's facial structure, skin tone, hair color, body proportions, age, and natural texture from the reference photos.\n\nScene: outdoor marble café terrace with gray-white marble wall, dark wooden window frame, round marble table, and soft city atmosphere.\n\nOutfit: oversized black blazer, fitted white crew-neck top, black sheer floral lace skirt or lace trousers, slim black oval sunglasses, hoop earrings, simple rings, dark manicured nails.\n\nAccessories: Celine Triomphe-style black oval sunglasses, Bottega Veneta Intrecciato-style woven black leather handbag placed near the table, Cartier-style rings, Riedel-style red wine glass.\n\nHair: sleek low bun or low ponytail with a clean center part. Keep the person's natural hair color from the uploaded reference photos.\n\nPose: seated at the marble table, holding the stem of a red wine glass lightly in one hand, looking away to the side as if watching the street. The other hand rests naturally near the blazer lapel or on the lap. Body language calm, elegant, and slightly mysterious.\n\nComposition: side-profile or three-quarter profile, face partly turned away, marble wall and wood window behind, wine glass in focus, table edge visible in the foreground.\n\nMood: quiet, expensive, fashion-editorial, not overly posed. It should feel like a real candid café moment that accidentally looks like a campaign.\n\nLighting: soft natural daylight, gentle highlights on cheekbones and sunglasses, realistic shadows, gray marble background, subtle film grain.\n\nImage quality: vertical 9:16 portrait, 2K quality, minimum 1440 x 2560 px if available, crisp face profile, sharp wine glass, sharp hand and rings, detailed lace texture, no blur, no compression haze.\n\nAvoid: distorted hands, extra fingers, warped wine glass, stiff pose, over-smoothed skin, fake-looking product details, CGI, stock-photo feeling.",
  },
  {
    number: "16",
    id: "marble-wine-shot-4",
    title: "Marble Café · Beauty Portrait",
    whenToUse: "Use for your profile photo, a close-up post, or any moment where you want the face to be the focus.",
    mood: "beauty · close-up · editorial · quiet luxury · sharp",
    exampleImage: "/images/ai-prompts/marble-wine-shot-4.jpg",
    prompt:
      "Create image 4 as a close-up beauty portrait from the same marble café wine editorial photoshoot.\n\nUse the uploaded reference photos as the only source for the person's face and identity. Preserve the person's real facial structure, skin tone, natural texture, hair color, body proportions, and age from the reference photos.\n\nScene: marble café terrace with gray-white marble wall, dark wood window frame, and soft blurred wine glass or café table in the background.\n\nStyling: oversized black blazer collar visible, fitted white top peeking through, slim black Celine Triomphe-style oval sunglasses pushed slightly low on the nose but not fully hiding the face, small polished hoop earrings, soft nude lips, natural polished makeup, realistic skin texture.\n\nHair: sleek low bun or low ponytail with a clean center part, polished but not stiff. Keep the person's natural hair color from the uploaded reference photos.\n\nPose: seated at the café terrace, face turned slightly toward camera, chin relaxed, expression calm and confident. One hand lightly touches the sunglasses or blazer collar. Wine glass and marble wall can be softly blurred in the background.\n\nCamera: tight portrait crop from shoulders up, shallow depth of field, editorial Pinterest beauty shot, realistic iPhone-editorial hybrid.\n\nMood: cool, elegant, quiet luxury, soft but powerful, feminine without looking too glam.\n\nLighting: soft natural daylight, cool marble reflections, gentle shadow under cheekbones, subtle grain, realistic pores and skin texture.\n\nImage quality: vertical 9:16 portrait, 2K quality, minimum 1440 x 2560 px if available, ultra-sharp face, crisp sunglasses, sharp hairline, realistic skin detail, no blur, no low-resolution softness.\n\nAvoid: distorted hand near face, fake-looking sunglasses reflections, heavy glam makeup, over-filled lips, plastic skin, airbrushed beauty filter, CGI.",
  },
  {
    number: "17",
    id: "marble-wine-shot-5",
    title: "Marble Café · Detail Shot",
    whenToUse: "The carousel detail slide. No face needed. Pairs perfectly with a caption about the outfit, the accessories, or the mood.",
    mood: "detail · tactile · quiet luxury · accessories · no face",
    exampleImage: "/images/ai-prompts/marble-wine-shot-5.jpg",
    prompt:
      "Create image 5 as the detail shot of this same marble café wine editorial photoshoot.\n\nNo full face needed.\n\nFocus on the details: hands with dark burgundy manicured nails holding the stem of a Riedel-style red wine glass, simple Cartier-style rings, oversized black blazer sleeve, black sheer floral lace fabric over one knee, a black Bottega Veneta Intrecciato-style woven leather handbag on the round white marble table, and the edge of the fitted white top or black blazer visible.\n\nScene: round white marble café table, gray-white marble wall, soft outdoor terrace light, quiet luxury café mood.\n\nComposition: close-up detail crop from above or slightly side angle. Show the wine glass, hand, rings, lace texture, blazer sleeve, handbag, and marble surface. The image should feel like a real Pinterest carousel detail slide.\n\nMood: expensive, minimal, tactile, fashion detail shot, quiet luxury, not overly staged.\n\nLighting: soft daylight, realistic reflections in the wine glass, natural shadows, subtle film grain, black-white-gray palette with deep red wine as the only color accent.\n\nImage quality: vertical 9:16 portrait, 2K quality, minimum 1440 x 2560 px if available, sharp hand details, crisp rings, crisp lace texture, sharp handbag weave, realistic marble texture, no blur, no low-resolution softness.\n\nAvoid: distorted fingers, extra hands, warped wine glass, fake-looking logos, messy handbag details, unrealistic wine, plastic textures, overly staged product-photo look.",
  },
  {
    number: "18",
    id: "marble-wine-shot-6",
    title: "Marble Café · Reel Cover",
    whenToUse: "Your reel cover or the strongest single image from the series. Strong silhouette, clean space for text at the top.",
    mood: "reel cover · editorial · silhouette · strong · vertical",
    exampleImage: "/images/ai-prompts/marble-wine-shot-6.jpg",
    prompt:
      "Create image 6 as the strongest reel-cover image from this marble café wine editorial photoshoot.\n\nUse the uploaded reference photos as the only source for the person's face and identity. Preserve the person's real facial structure, skin tone, hair color, body proportions, age, and natural texture from the reference photos.\n\nScene: elegant marble café terrace with gray-white marble walls, dark wooden window frames, a round white marble table, and refined city atmosphere.\n\nOutfit: oversized black structured blazer with strong shoulders, fitted white crew-neck top, black sheer floral lace skirt or lace trousers, slim black oval sunglasses, small hoop earrings, rings, dark manicured nails.\n\nBrand-coded styling: Celine Triomphe-style black oval sunglasses, Bottega Veneta Intrecciato-style black woven leather handbag, Cartier-style rings, Riedel-style red wine glass.\n\nHair: sleek low bun or low ponytail with a clean center part, polished but slightly natural. Keep the person's natural hair color from the uploaded reference photos.\n\nPose: seated with one knee raised into frame, leaning slightly back with confident posture, holding a red wine glass near the face, head turned slightly to the side. The black blazer should create a strong silhouette, and the lace detail should be visible but elegant.\n\nComposition: vertical 9:16 reel-cover crop with clean space at the top or side for text overlay. Make it look like a Pinterest fashion reel cover.\n\nMood: cool, quiet luxury, expensive, calm, confident, feminine, not overly glam, not too polished, not AI-looking.\n\nLighting: soft natural daylight, muted marble tones, realistic shadows, subtle film grain, sharp but natural iPhone editorial feel.\n\nImage quality: vertical 9:16 portrait, 2K quality, minimum 1440 x 2560 px if available, crisp editorial sharpness, sharp face, clear outfit silhouette, sharp lace texture, sharp wine glass, clean text space, no blur, no compression softness.\n\nAvoid: distorted hands, extra fingers, warped wine glass, fake-looking logos, plastic skin, overly generic influencer face, stock-photo pose, CGI.",
  },
]
