// SSELFIE Studio 3.0 - MAYA-GUIDED-TEXT-01: pre-rendered example covers for the six text styles.
//
// Sandra's call (2026-07-02): the Text Studio got too messy. Maya now pulls up inline example
// cards of each design; the member taps one and generates from that exact template. Each card
// shows a finished-looking cover: an editorial detail background (no person) with that style's
// text treatment BAKED in, so she sees the real result, not a wireframe.
//
// The images are generated once by scripts/generate-text-style-examples.ts (gpt-image-2 +
// Vercel Blob) and pinned here. Graceful fallback: when a style has no example URL yet, the
// card falls back to the live CSS mini-preview (TextOverlayLayer with the sample copy below),
// so the picker never shows a broken tile.

import {
  resolveOverlayStyle,
  type OverlayFormat,
  type OverlayStyleId,
  type TextOverlaySpec,
} from "@/lib/app-v3/text-overlay"

/**
 * One example cover per style, generated by scripts/generate-text-style-examples.ts.
 * Empty string = no example yet -> the picker card falls back to the CSS mini-preview.
 */
export const TEXT_STYLE_EXAMPLE_IMAGES: Record<OverlayStyleId, string> = {
  "editorial-serif-center":
    "https://kcnmiu7u3eszdkja.public.blob.vercel-storage.com/app-v3/text-style-examples/editorial-serif-center.png",
  "lower-third-accent":
    "https://kcnmiu7u3eszdkja.public.blob.vercel-storage.com/app-v3/text-style-examples/lower-third-accent.png",
  "top-band-minimal":
    "https://kcnmiu7u3eszdkja.public.blob.vercel-storage.com/app-v3/text-style-examples/top-band-minimal.png",
  "quote-statement":
    "https://kcnmiu7u3eszdkja.public.blob.vercel-storage.com/app-v3/text-style-examples/quote-statement.png",
  "series-cover":
    "https://kcnmiu7u3eszdkja.public.blob.vercel-storage.com/app-v3/text-style-examples/series-cover.png",
  "cutout-editorial":
    "https://kcnmiu7u3eszdkja.public.blob.vercel-storage.com/app-v3/text-style-examples/cutout-editorial.png",
}

/** The example cover URL for a style, or null when the card should use the CSS fallback. */
export function getTextStyleExampleImage(style: OverlayStyleId): string | null {
  const url = TEXT_STYLE_EXAMPLE_IMAGES[style]
  return typeof url === "string" && url.startsWith("https://") ? url : null
}

/**
 * Neutral, on-voice sample copy per style (used by BOTH the generation script and the CSS
 * fallback preview, so the fallback shows the same words as the real example image).
 * Markers (*phrase*) drive each style's own accent: underline, cut-paper strip, circle.
 */
export const TEXT_STYLE_SAMPLE_COPY: Record<
  OverlayStyleId,
  { headline: string; subline?: string }
> = {
  "editorial-serif-center": {
    headline: "The Part Nobody Sees",
    subline: "A note on building quietly",
  },
  "lower-third-accent": {
    headline: "I stopped waiting to feel *ready*",
    subline: "A note from the quiet season",
  },
  "top-band-minimal": {
    headline: "Begin Quietly",
    subline: "Notes on a slower morning",
  },
  "quote-statement": {
    headline: "She built it anyway",
  },
  "series-cover": {
    headline: "The Quiet Build",
    subline: "Part 3",
  },
  "cutout-editorial": {
    headline: "The Part *Nobody Sees*",
    subline: "Save this for your *next chapter*",
  },
}

/** The sample spec a fallback card renders live (same words the example image bakes in). */
export function textStyleSampleSpec(
  style: OverlayStyleId,
  format: OverlayFormat = "reel-cover"
): TextOverlaySpec {
  const copy = TEXT_STYLE_SAMPLE_COPY[style]
  const preset = resolveOverlayStyle(style)
  return {
    headline: copy.headline,
    subline: copy.subline,
    position: preset.lockedPosition ?? preset.defaultPosition ?? "bottom",
    style,
    format,
  }
}
