export const ALLOWED_ANALYTICS_EVENTS = [
  "landing_view",
  "pricing_view",
  "checkout_start",
  "purchase",
  "studio_opened",
  "tab_opened",
  "activation_jumpstart_opened",
  "activation_continue_clicked",
  "activation_selfie_uploaded",
  "feed_planner_quick_start_viewed",
  "feed_planner_quick_start_clicked",
  "signup_to_first_gen",
  "academy_home_opened",
  "academy_opens_from_maya",
  "first_generation_guided_start",
  "first_generation_guided_complete",
  "first_image_generated",
  "maya_capabilities_opened",
  "maya_tool_invoked",
  "maya_asset_draft_created",
  "maya_asset_draft_updated",
  "maya_public_page_view",
  "maya_public_page_checkout_clicked",
  "maya_public_page_lead_captured",
  "maya_tool_blocked_low_credits",
  "maya_multi_step_executor_run",
  "onboarding_step_complete",
  "onboarding_abandoned",
  "onboarding_complete",
  "credits_used",
  "mode_selected",
  "brand_strategy_pack_upsell_view",
  "brand_strategy_pack_checkout_start",
  "brand_strategy_pack_checkout_success",
  "brand_strategy_pack_access_opened",
  "brand_strategy_pack_studio_click",
  "one_time_session_studio_click",
  "selfie_guide_opt_in_submit",
  "selfie_guide_opt_in_success",
  "selfie_guide_opt_in_failed",
  "selfie_guide_entry_click",
  "selfie_guide_checkout_success",
  "selfie_guide_access_resolved",
  "selfie_guide_access_failed",
  "selfie_guide_upsell_click",
  "starter_kit_checkout_success",
  "starter_kit_access_opened",
  "starter_kit_preset_download_clicked",
  "masterclass_checkout_success",
  "masterclass_access_opened",
  "access_recovery_requested",
  "access_recovery_email_sent",
  "selfie_guide_chapter_completed",
  "selfie_guide_challenge_submitted",
  "offer_landing_view",
  "offer_cta_click",
  "quiz_started",
  "quiz_completed",
  "quiz_result_viewed",
  "quiz_result_served",
  "micro_offer_cta_clicked",
  "visibility_suite_upsell_view",
  "upsell_viewed",
  "upsell_accepted",
  "studio_entry_from_suite",
  "post_keyword_attributed",
  "private_sprint_application_started",
  "private_sprint_application_submitted",
  "studio_from_suite_clicked",
  "ai_prompts_subscribed",
  "ai_prompts_access_opened",
  "ai_prompts_prompt_copied",
  "ai_prompts_selfie_guide_click",
  "ai_prompts_prompt_vault_click",
  "ai_prompts_starter_kit_click",
  "prompt_vault_checkout_success",
  "prompt_vault_access_resolved",
  "prompt_vault_access_failed",
  "prompt_vault_access_opened",
] as const

export type AnalyticsEventName = (typeof ALLOWED_ANALYTICS_EVENTS)[number]

const ALLOWED_ANALYTICS_EVENT_SET = new Set<string>(ALLOWED_ANALYTICS_EVENTS)

export function isAllowedAnalyticsEventName(eventName: string): eventName is AnalyticsEventName {
  return ALLOWED_ANALYTICS_EVENT_SET.has(eventName)
}
