export const ALLOWED_ANALYTICS_EVENTS = [
  "landing_view",
  "pricing_view",
  "checkout_start",
  "purchase",
  "studio_opened",
  "tab_opened",
  "activation_jumpstart_opened",
  "activation_continue_clicked",
  "activation_selfie_uploaded",
  "feed_planner_quick_start_viewed",
  "feed_planner_quick_start_clicked",
  "signup_to_first_gen",
  "academy_home_opened",
  "academy_opens_from_maya",
  "first_generation_guided_start",
  "first_generation_guided_complete",
  "first_image_generated",
  "maya_capabilities_opened",
  "maya_tool_invoked",
  "maya_asset_draft_created",
  "maya_asset_draft_updated",
  "maya_public_page_view",
  "maya_public_page_checkout_clicked",
  "maya_public_page_lead_captured",
  "maya_tool_blocked_low_credits",
  "maya_multi_step_executor_run",
  "onboarding_step_complete",
  "onboarding_abandoned",
  "onboarding_complete",
  "credits_used",
  "mode_selected",
  "brand_strategy_pack_upsell_view",
  "brand_strategy_pack_checkout_start",
  "brand_strategy_pack_checkout_success",
  "brand_strategy_pack_access_opened",
  "brand_strategy_pack_studio_click",
  "one_time_session_studio_click",
  "selfie_guide_opt_in_submit",
  "selfie_guide_opt_in_success",
  "selfie_guide_opt_in_failed",
  "selfie_guide_entry_click",
  "selfie_guide_checkout_success",
  "selfie_guide_access_resolved",
  "selfie_guide_access_failed",
  "selfie_guide_upsell_click",
  "starter_kit_checkout_success",
  "starter_kit_checkout_session_requested",
  "starter_kit_checkout_session_created",
  "starter_kit_checkout_session_failed",
  "starter_kit_payment_form_rendered",
  "starter_kit_access_opened",
  "starter_kit_preset_download_clicked",
  "selfie_ai_photos_kit_landing_view",
  "selfie_ai_photos_kit_checkout_email_capture_view",
  "selfie_ai_photos_kit_checkout_session_requested",
  "selfie_ai_photos_kit_checkout_session_created",
  "selfie_ai_photos_kit_checkout_session_failed",
  "selfie_ai_photos_kit_payment_form_rendered",
  "selfie_ai_photos_kit_checkout_success",
  "selfie_ai_photos_kit_access_resolved",
  "selfie_ai_photos_kit_access_failed",
  "selfie_ai_photos_kit_access_opened",
  "selfie_ai_photos_kit_prompt_copied",
  "selfie_ai_photos_kit_vault_upgrade_click",
  "selfie_ai_photos_kit_suite_click",
  "masterclass_checkout_email_capture_view",
  "masterclass_checkout_session_requested",
  "masterclass_checkout_session_created",
  "masterclass_checkout_session_failed",
  "masterclass_checkout_payment_entry_shown",
  "masterclass_checkout_success",
  "masterclass_access_opened",
  "access_recovery_requested",
  "access_recovery_email_sent",
  "selfie_guide_chapter_completed",
  "selfie_guide_challenge_submitted",
  "offer_landing_view",
  "offer_cta_click",
  "quiz_started",
  "quiz_completed",
  "quiz_result_viewed",
  "quiz_result_served",
  "micro_offer_cta_clicked",
  "visibility_suite_upsell_view",
  "upsell_viewed",
  "upsell_accepted",
  "studio_entry_from_suite",
  "post_keyword_attributed",
  "private_sprint_application_started",
  "private_sprint_application_submitted",
  "work_with_me_landing_view",
  "work_with_me_application_started",
  "work_with_me_application_submitted",
  "work_with_me_application_failed",
  "studio_from_suite_clicked",
  "ai_prompts_subscribed",
  "ai_prompts_access_opened",
  "ai_prompts_prompt_copied",
  "ai_prompts_after_copy_vault_cta_view",
  "ai_prompts_after_copy_kit_cta_view",
  "ai_prompts_locked_vault_tiles_view",
  "ai_prompts_locked_vault_tile_click",
  "ai_prompts_selfie_guide_click",
  "ai_prompts_prompt_vault_click",
  "ai_prompts_selfie_ai_photos_kit_click",
  "ai_prompts_starter_kit_click",
  "studio_membership_door_view",
  "studio_membership_door_click",
  "studio_membership_payment_form_rendered",
  "prompt_vault_landing_view",
  "prompt_vault_reel_click",
  "prompt_vault_checkout_session_requested",
  "prompt_vault_checkout_session_created",
  "prompt_vault_checkout_session_failed",
  "prompt_vault_payment_form_rendered",
  "prompt_vault_payment_completed",
  "prompt_vault_checkout_success",
  "prompt_vault_access_resolved",
  "prompt_vault_access_failed",
  "prompt_vault_access_opened",
  "prompt_vault_prompt_viewed",
  "prompt_vault_prompt_copied",
  "prompt_vault_checkout_recovery_sent",
  "presets_checkout_email_capture_view",
  "presets_checkout_session_requested",
  "presets_checkout_session_created",
  "presets_checkout_session_failed",
  "presets_payment_form_rendered",
  "presets_checkout_success",
  "presets_access_resolved",
  "presets_access_failed",
  "presets_access_opened",
  "presets_download_clicked",
  // One Selfie Visibility Bundle: paid-event behavior only. Revenue remains Stripe truth.
  "selfie_visibility_bundle_checkout_completed",
  "selfie_visibility_bundle_access_opened",
  "selfie_visibility_bundle_asset_opened",
  "selfie_visibility_bundle_annual_upsell_viewed",
  "selfie_visibility_bundle_annual_upsell_clicked",
  "selfie_visibility_bundle_annual_upsell_completed",
  "selfie_to_brand_shoot_landing_view",
  "selfie_to_brand_shoot_checkout_start",
  "selfie_to_brand_shoot_checkout_success",
  "selfie_to_brand_shoot_access_resolved",
  "selfie_to_brand_shoot_access_failed",
  "selfie_to_brand_shoot_access_opened",
  "selfie_to_brand_shoot_module_started",
  "selfie_to_brand_shoot_module_completed",
  "selfie_to_brand_shoot_workbook_downloaded",
  "selfie_to_brand_shoot_visual_code_saved",
  "selfie_to_brand_shoot_maya_prompt_pack_built",
  "selfie_to_brand_shoot_prompt_pack_copied",
  "selfie_to_brand_shoot_final_selects_completed",
  "selfie_to_brand_shoot_content_plan_completed",
  "selfie_to_brand_shoot_testimonial_requested",
  "selfie_to_brand_shoot_testimonial_submitted",
  "selfie_to_brand_shoot_checkout_recovery_sent",
  "prompt_vault_system_upgrade_click",
  // BRIDGE-01 — SUITE trial lifecycle (behavior only; conversion truth lives in subscriptions)
  "trial_claimed",
  "trial_first_generation",
  "trial_expired",
  "membership_checkout_email_capture_view",
  "membership_checkout_recovery_sent",
  "suite_home_viewed",
  "suite_trial_first_run_seen",
  "first_action_selected",
  // ManyChat vault-step DM email capture (behavior/lead-source only; never money)
  "manychat_vault_email_captured",
  // SUITE-UX-02 — member pulse: what members DO with Maya in /app (behavior only, never money).
  // Aggregated weekly by lib/admin/member-pulse.ts into the Monday content brief.
  "suite_concepts_emitted",
  "suite_clarify_asked",
  "suite_image_generated",
  "suite_image_downloaded",
  "suite_edit_applied",
  // Authenticated, post-download SUITE review capture. Behavior only; approved proof lives in
  // admin_testimonials and never counts as revenue.
  "suite_review_prompt_shown",
  "suite_review_prompt_opened",
  "suite_review_prompt_dismissed",
  "suite_review_submitted",
  // MAYA-FIRST-SUITE-UX — inline guided creation path. Behavior only.
  "suite_maya_inline_started",
  "suite_intent_detected",
  "suite_inline_choice_selected",
  "suite_inline_selfie_uploaded",
  "suite_generation_path_completed",
  "suite_next_action_selected",
  "suite_maya_recovery_shown",
  // App v3 generation reliability + trial-cap conversion moments (behavior only).
  "suite_generation_failed",
  // STORY-GENERATION round 3 (2026-07-03): a malformed emit_concepts call was repaired
  // server-side / a chat stream died before finishing (behavior only).
  "suite_concepts_repaired",
  "suite_chat_aborted",
  "trial_cap_offer_shown",
  "trial_cap_offer_cta_click",
  // VIDEO reliability 2026-07 — persistent failure log for member video generation
  // (stage, error, model, refunded live in properties; behavior only, never money).
  "suite_video_generation_failed",
  "suite_memory_note_saved",
  // LIKENESS-MEMORY-01 — a likeness correction became a durable memory note (behavior only).
  "suite_likeness_note_captured",
  // CALENDAR-UPGRADE-01: behavioral outcome only. Revenue truth never lives here.
  "calendar_post_published",
  // TEXT-STUDIO-01 — hybrid text studio: she asked for a baked text render / the bake failed
  // (behavior only, never money; credits truth lives in credit_transactions).
  "suite_text_bake_requested",
  "suite_text_bake_failed",
] as const

export type AnalyticsEventName = (typeof ALLOWED_ANALYTICS_EVENTS)[number]

const ALLOWED_ANALYTICS_EVENT_SET = new Set<string>(ALLOWED_ANALYTICS_EVENTS)

export function isAllowedAnalyticsEventName(eventName: string): eventName is AnalyticsEventName {
  return ALLOWED_ANALYTICS_EVENT_SET.has(eventName)
}
