// Legacy browser/server keys are mapped to the questions in the existing protected workbooks.
// Keep these labels stable so old saved answers are never assigned a different meaning.
export const WORKBOOK_LEGACY_QUESTIONS: Record<string, Record<string, string>> = {
  what_to_say: {
    buyer_language_dms: "DMs or comments people have sent me",
    buyer_language_questions: "Questions people keep asking me",
    buyer_language_poll_replies: "Poll replies or audience words",
    buyer_language_problems: "Problems they say out loud",
    buyer_language_help_requests: "Things friends, clients, or followers ask for help with",
    buyer_language_buying_signals: "Buying signals I have noticed",
    q6f0: "Question 01 — Who Is Your One Person?",
    q7f0: "Question 02 — What Does She Tell Herself?",
    q8f0: "Question 03 — What's The 90-Day Transformation?",
    q9f0: "Question 04 — Why Are YOU The Right Person?",
    q10f0: "Your Story",
    q11f0: "Your Expertise",
    q12f0: "Your Values",
    q13f0: "Your Vision",
    q14f0: "Your Voice",
    q15f0: "Your 10 Brand Words",
    q16f0: "Message Test — Would A Stranger Understand This In 5 Seconds?",
    q17f0: "Proof — What Makes This Believable?",
    q18f0: "Content-To-Offer Bridge — What Should They Want Next?",
  },
  show_up: {
    content_goal_this_month: "What is your content goal this month?",
    q1f0: "Question 01 — What Are The 4 Things You Talk About Most?",
    q2f0: "Question 02 — What's Happening In Your Business This Month?",
    q3f0: "Question 03 — What Do You Want People To DO After 30 Days?",
    q4f0: "Which Content Type Feels Most Natural To You?",
    q5f0: "Which Content Type Do You Avoid — And Why?",
    q6f0: "What Time Sunday Works For You?",
    q7f0: "What Would Make This Feel Easier?",
    q8f0: "How Many Posts Can You Realistically Create Each Week?",
    q9f0: "Which Formats Fit You Best Right Now?",
    q10f0: "What Content Assets Do You Already Have?",
    q11f0: "What Can You Repurpose This Week?",
  },
  get_paid: {
    q0f0: "Question 01 — What Exact Result Do You Help Someone Achieve?",
    q1f0: "Question 02 — How Long Does It Take?",
    q2f0: "Question 03 — What Does Their Life Look Like Before vs. After?",
    offer_readiness_one_sentence: "Can someone understand what it is in one sentence?",
    offer_readiness_who_for: "Do they know who it is for?",
    offer_readiness_result: "Do they know what result it helps them move toward?",
    offer_readiness_get: "Do they know what they get?",
    offer_readiness_buy: "Do they know how to buy?",
    offer_readiness_not_included: "Do they know what is not included?",
    q9f0: "Question 01 — Who Has Already Paid You?",
    q10f0: "Question 02 — What Were They Struggling With?",
    q11f0: "Question 03 — What Did They Say After?",
    q12f0: "Your Buyer In One Sentence",
    q13f0: "Question 01 — Which Path Feels Most Realistic Right Now?",
    q14f0: "Question 02 — What Would You Need To Sell?",
    q15f0: "Question 03 — What's Stopping You From Offering It Today?",
    q16f0: "Buyer Urgency — Why Would She Want This Now?",
    q17f0: "Willingness To Pay — Has She Paid For Similar Help Before?",
    q18f0: "Delivery Boundary — What Is Included And What Is Not?",
    q19f0: "First 10 Buyers — Who Can You Invite This Week?",
    q20f0: "What Part Of Selling Feels Hardest?",
  },
}
