import { describe, expect, it } from "vitest"

import { ALLOWED_ANALYTICS_EVENTS, isAllowedAnalyticsEventName } from "@/lib/analytics/event-contract"

describe("analytics event contract", () => {
  it("includes guided activation and onboarding lifecycle events", () => {
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("first_generation_guided_start")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("first_generation_guided_complete")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("first_image_generated")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("onboarding_complete")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("credits_used")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("mode_selected")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("academy_home_opened")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("onboarding_step_complete")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("onboarding_abandoned")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("feed_planner_quick_start_viewed")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("feed_planner_quick_start_clicked")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("maya_capabilities_opened")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("maya_tool_invoked")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("maya_asset_draft_created")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("maya_asset_draft_updated")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("maya_public_page_view")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("maya_public_page_checkout_clicked")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("maya_public_page_lead_captured")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("maya_tool_blocked_low_credits")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("maya_multi_step_executor_run")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("brand_strategy_pack_upsell_view")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("brand_strategy_pack_checkout_start")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("brand_strategy_pack_checkout_success")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("brand_strategy_pack_access_opened")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("brand_strategy_pack_studio_click")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("one_time_session_studio_click")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("selfie_guide_opt_in_submit")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("selfie_guide_opt_in_success")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("selfie_guide_opt_in_failed")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("selfie_guide_entry_click")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("selfie_guide_checkout_success")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("selfie_guide_access_resolved")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("selfie_guide_access_failed")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("selfie_guide_upsell_click")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("starter_kit_checkout_success")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("starter_kit_access_opened")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("masterclass_checkout_success")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("quiz_result_served")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("upsell_viewed")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("upsell_accepted")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("studio_entry_from_suite")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("post_keyword_attributed")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("prompt_vault_reel_click")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("prompt_vault_prompt_viewed")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("prompt_vault_checkout_recovery_sent")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("selfie_to_brand_shoot_checkout_start")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("selfie_to_brand_shoot_checkout_success")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("selfie_to_brand_shoot_access_opened")
  })

  it("rejects unknown event names", () => {
    expect(isAllowedAnalyticsEventName("wizard_step_3_complete")).toBe(false)
    expect(isAllowedAnalyticsEventName("totally_unknown_event")).toBe(false)
  })

  it("accepts known event names", () => {
    expect(isAllowedAnalyticsEventName("studio_opened")).toBe(true)
    expect(isAllowedAnalyticsEventName("academy_home_opened")).toBe(true)
    expect(isAllowedAnalyticsEventName("mode_selected")).toBe(true)
    expect(isAllowedAnalyticsEventName("first_image_generated")).toBe(true)
    expect(isAllowedAnalyticsEventName("maya_public_page_lead_captured")).toBe(true)
    expect(isAllowedAnalyticsEventName("maya_tool_blocked_low_credits")).toBe(true)
    expect(isAllowedAnalyticsEventName("maya_multi_step_executor_run")).toBe(true)
    expect(isAllowedAnalyticsEventName("brand_strategy_pack_checkout_success")).toBe(true)
    expect(isAllowedAnalyticsEventName("selfie_guide_entry_click")).toBe(true)
    expect(isAllowedAnalyticsEventName("selfie_guide_checkout_success")).toBe(true)
    expect(isAllowedAnalyticsEventName("starter_kit_checkout_success")).toBe(true)
    expect(isAllowedAnalyticsEventName("masterclass_checkout_success")).toBe(true)
    expect(isAllowedAnalyticsEventName("selfie_guide_access_resolved")).toBe(true)
    expect(isAllowedAnalyticsEventName("quiz_result_served")).toBe(true)
    expect(isAllowedAnalyticsEventName("post_keyword_attributed")).toBe(true)
    expect(isAllowedAnalyticsEventName("prompt_vault_reel_click")).toBe(true)
    expect(isAllowedAnalyticsEventName("prompt_vault_prompt_viewed")).toBe(true)
    expect(isAllowedAnalyticsEventName("prompt_vault_checkout_recovery_sent")).toBe(true)
    expect(isAllowedAnalyticsEventName("selfie_to_brand_shoot_checkout_start")).toBe(true)
    expect(isAllowedAnalyticsEventName("selfie_to_brand_shoot_checkout_success")).toBe(true)
    expect(isAllowedAnalyticsEventName("selfie_to_brand_shoot_access_opened")).toBe(true)
  })
})
