import { readFileSync } from "node:fs"
import { describe, expect, it } from "vitest"

import {
  ALLOWED_ANALYTICS_EVENTS,
  isAllowedAnalyticsEventName,
} from "@/lib/analytics/event-contract"

describe("analytics event contract", () => {
  it("includes guided activation and onboarding lifecycle events", () => {
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("first_generation_guided_start")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("first_generation_guided_complete")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("first_image_generated")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("onboarding_complete")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("credits_used")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("mode_selected")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("academy_home_opened")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("onboarding_step_complete")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("onboarding_abandoned")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("feed_planner_quick_start_viewed")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("feed_planner_quick_start_clicked")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("maya_capabilities_opened")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("maya_tool_invoked")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("maya_asset_draft_created")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("maya_asset_draft_updated")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("maya_public_page_view")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("maya_public_page_checkout_clicked")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("maya_public_page_lead_captured")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("studio_membership_page_view")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("studio_membership_page_cta_click")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("maya_tool_blocked_low_credits")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("maya_multi_step_executor_run")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("brand_strategy_pack_upsell_view")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("brand_strategy_pack_checkout_start")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("brand_strategy_pack_checkout_success")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("brand_strategy_pack_access_opened")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("brand_strategy_pack_studio_click")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("one_time_session_studio_click")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("selfie_guide_opt_in_submit")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("selfie_guide_opt_in_success")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("selfie_guide_opt_in_failed")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("selfie_guide_entry_click")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("selfie_guide_checkout_success")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("selfie_guide_access_resolved")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("selfie_guide_access_failed")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("selfie_guide_upsell_click")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("starter_kit_checkout_success")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("starter_kit_access_opened")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("masterclass_checkout_success")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("quiz_result_served")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("upsell_viewed")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("upsell_accepted")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("studio_entry_from_suite")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("post_keyword_attributed")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("prompt_vault_reel_click")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("prompt_vault_prompt_viewed")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("prompt_vault_suite_offer_viewed")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("prompt_vault_suite_offer_clicked")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("prompt_vault_suite_offer_declined")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("prompt_vault_presets_downsell_clicked")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("prompt_vault_checkout_recovery_sent")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("selfie_to_brand_shoot_checkout_start")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("selfie_to_brand_shoot_checkout_success")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("selfie_to_brand_shoot_access_opened")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("suite_home_viewed")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("suite_trial_first_run_seen")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("first_action_selected")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("suite_maya_inline_started")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("suite_intent_detected")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("suite_inline_choice_selected")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("suite_inline_selfie_uploaded")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("suite_generation_path_completed")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("suite_next_action_selected")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("suite_maya_recovery_shown")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("story_studio_opened")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("story_studio_saved")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("learn_goal_selected")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("learn_plan_saved")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("learn_calendar_handoff")
    expect(ALLOWED_ANALYTICS_EVENTS).toContain("learn_maya_handoff")
  })

  it("rejects unknown event names", () => {
    expect(isAllowedAnalyticsEventName("wizard_step_3_complete")).toBe(false)
    expect(isAllowedAnalyticsEventName("totally_unknown_event")).toBe(false)
  })

  it("accepts known event names", () => {
    expect(isAllowedAnalyticsEventName("studio_opened")).toBe(true)
    expect(isAllowedAnalyticsEventName("academy_home_opened")).toBe(true)
    expect(isAllowedAnalyticsEventName("mode_selected")).toBe(true)
    expect(isAllowedAnalyticsEventName("first_image_generated")).toBe(true)
    expect(isAllowedAnalyticsEventName("maya_public_page_lead_captured")).toBe(true)
    expect(isAllowedAnalyticsEventName("maya_tool_blocked_low_credits")).toBe(true)
    expect(isAllowedAnalyticsEventName("maya_multi_step_executor_run")).toBe(true)
    expect(isAllowedAnalyticsEventName("brand_strategy_pack_checkout_success")).toBe(true)
    expect(isAllowedAnalyticsEventName("selfie_guide_entry_click")).toBe(true)
    expect(isAllowedAnalyticsEventName("selfie_guide_checkout_success")).toBe(true)
    expect(isAllowedAnalyticsEventName("starter_kit_checkout_success")).toBe(true)
    expect(isAllowedAnalyticsEventName("masterclass_checkout_success")).toBe(true)
    expect(isAllowedAnalyticsEventName("selfie_guide_access_resolved")).toBe(true)
    expect(isAllowedAnalyticsEventName("quiz_result_served")).toBe(true)
    expect(isAllowedAnalyticsEventName("post_keyword_attributed")).toBe(true)
    expect(isAllowedAnalyticsEventName("prompt_vault_reel_click")).toBe(true)
    expect(isAllowedAnalyticsEventName("prompt_vault_prompt_viewed")).toBe(true)
    expect(isAllowedAnalyticsEventName("prompt_vault_suite_offer_viewed")).toBe(true)
    expect(isAllowedAnalyticsEventName("prompt_vault_suite_offer_clicked")).toBe(true)
    expect(isAllowedAnalyticsEventName("prompt_vault_suite_offer_declined")).toBe(true)
    expect(isAllowedAnalyticsEventName("prompt_vault_presets_downsell_clicked")).toBe(true)
    expect(isAllowedAnalyticsEventName("prompt_vault_checkout_recovery_sent")).toBe(true)
    expect(isAllowedAnalyticsEventName("selfie_to_brand_shoot_checkout_start")).toBe(true)
    expect(isAllowedAnalyticsEventName("selfie_to_brand_shoot_checkout_success")).toBe(true)
    expect(isAllowedAnalyticsEventName("selfie_to_brand_shoot_access_opened")).toBe(true)
    expect(isAllowedAnalyticsEventName("suite_home_viewed")).toBe(true)
    expect(isAllowedAnalyticsEventName("suite_trial_first_run_seen")).toBe(true)
    expect(isAllowedAnalyticsEventName("first_action_selected")).toBe(true)
    expect(isAllowedAnalyticsEventName("suite_maya_inline_started")).toBe(true)
    expect(isAllowedAnalyticsEventName("suite_generation_path_completed")).toBe(true)
  })

  it("labels every suite intent event so intent is queryable", () => {
    const concierge = readFileSync("components/app-v3/maya-concierge.tsx", "utf8")
    const frontDoor = readFileSync("components/app-v3/visual-front-door.tsx", "utf8")
    const events = readFileSync("lib/analytics/events.ts", "utf8")
    const schema = readFileSync("lib/analytics/schema.ts", "utf8")
    expect(concierge).toContain('intent_label: intent.format ?? "needs_clarify"')
    expect(frontDoor).toContain('intent_label: format ?? "needs_clarify"')
    expect(events).toContain('eventName === "suite_intent_detected"')
    expect(schema).toContain("NOT (properties ? 'intent_label')")
  })
})
