import { streamText, tool, generateObject } from "ai"
import { z } from "zod"
import { getUserByAuthId } from "@/lib/user-mapping"
import { createServerClient } from "@/lib/supabase/server"
import { MAYA_SYSTEM_PROMPT } from "@/lib/maya/personality"
import type { CoreMessage } from "ai"
import { neon } from "@neondatabase/serverless"
import { generateCaptionsForFeed } from "@/lib/instagram-strategist/caption-logic"
import { generateInstagramBio } from "@/lib/instagram-bio-strategist/bio-logic"

// Global map to track active feed generations per user
const activeFeedGenerations = new Map<number, boolean>()

const MAYA_FEED_STRATEGIST_EXTENSION = `

## Instagram Feed Strategy Expertise

You're an expert Instagram visual strategist who creates cohesive, professional feeds.

**When a user asks you to design their feed:**

1. Respond warmly and let them know you're starting
2. Call the feed_strategy tool ONCE (it automatically generates bio and captions)
3. After the feed is created, explain the complete strategy
4. Users can manually generate highlights and profile images later if they want

**CRITICAL: Only call feed_strategy ONCE per request. Do not call it multiple times.**

The Instagram Caption Strategist writes all captions using research-backed insights.
You focus on visual strategy and coordination.

The tools handle all the design work internally, so you call them and explain the results.
`

const generateCompleteFeedTool = tool({
  description:
    "Design a complete 9-post Instagram feed strategy with VISUAL CONCEPTS ONLY. This tool creates the visual layout, Flux prompts, and post structure. Bio and captions will be generated by specialists. **IMPORTANT: Only call this tool ONCE per user request.**",
  inputSchema: z.object({
    brandVibe: z
      .string()
      .describe(
        "The overall aesthetic and mood from user's brand profile (e.g., 'elegant minimalist', 'bold and confident', 'warm and approachable')",
      ),
    businessType: z
      .string()
      .describe("What the user does from their brand profile (e.g., 'life coach', 'fashion designer', 'entrepreneur')"),
    colorPalette: z
      .string()
      .describe(
        "Specific color scheme that matches their brand (e.g., 'neutral earth tones - beige, cream, white', 'dark moody - charcoal, black, gold')",
      ),
    feedStory: z
      .string()
      .describe(
        "The complete narrative this feed tells (e.g., 'A confident life coach who empowers women to build their dream businesses')",
      ),
    username: z.string().describe("Instagram username/handle (e.g., 'sandra.social', 'yourhandle') - without @ symbol"),
    brandName: z.string().describe("Brand or business name to display (e.g., 'Sandra Social', 'Your Brand Name')"),
    highlights: z
      .array(
        z.object({
          title: z.string().describe("Highlight title (e.g., 'Tips', 'BTS', 'Client Wins')"),
          prompt: z
            .string()
            .describe(
              "FLUX prompt for generating the BACKGROUND IMAGE ONLY (flatlay, object, aesthetic scene) - DO NOT include text in the prompt. The text will be overlaid later. Focus on creating a beautiful, brand-aligned background image with the user's colors and aesthetic.",
            ),
        }),
      )
      .describe("4-5 Instagram highlight categories with detailed FLUX prompts for BACKGROUND images (no text)"),
  }),
  execute: async ({ brandVibe, businessType, colorPalette, feedStory, username, brandName, highlights }) => {
    console.log("[v0] [SERVER] === TOOL EXECUTION STARTED ===")
    console.log("[v0] [SERVER] Generating feed strategy:", {
      brandVibe,
      businessType,
      colorPalette,
      username,
      brandName,
    })

    const supabase = await createServerClient()
    const {
      data: { user: authUser },
    } = await supabase.auth.getUser()

    if (!authUser) {
      console.error("[v0] [SERVER] No auth user found")
      return "I encountered an error - you need to be logged in to save your feed strategy. Please refresh and try again."
    }

    const user = await getUserByAuthId(authUser.id)

    if (!user) {
      console.error("[v0] [SERVER] No user found, cannot save feed")
      return "I encountered an error - you need to be logged in to save your feed strategy. Please refresh and try again."
    }

    if (activeFeedGenerations.get(user.id)) {
      console.log("[v0] [SERVER] ⚠️ Feed generation already in progress for user:", user.id)
      return "I'm already working on your feed strategy! Please wait for it to complete."
    }

    // Mark feed generation as active for this user
    activeFeedGenerations.set(user.id, true)
    console.log("[v0] [SERVER] ✓ Marked feed generation as active for user:", user.id)
    // </CHANGE>

    try {
      console.log("[v0] [SERVER] 🔍 Starting content research (this may take 1-2 minutes)...")
      const sql = neon(process.env.DATABASE_URL || "")

      const [brandProfile] = await sql`
        SELECT * FROM user_personal_brand
        WHERE user_id = ${user.id}
        AND is_completed = true
        LIMIT 1
      `

      let researchInsights: string | null = null

      // TODO: Debug why performContentResearch is causing route to crash
      researchInsights = `Instagram best practices for ${businessType}: Focus on authentic storytelling, consistent visual aesthetic, engaging captions that spark conversation, strategic use of hashtags, and building genuine community connections.`

      console.log("[v0] [SERVER] 🎨 Using AI to design custom feed layout...")

      const { object: feedDesign } = await generateObject({
        model: "anthropic/claude-sonnet-4",
        schema: z.object({
          visualRhythm: z.string().describe("Description of the visual flow and rhythm of this feed"),
          posts: z
            .array(
              z.object({
                type: z.enum(["Close-Up", "Half Body", "Full Body", "Lifestyle", "Object"]).describe("Post type"),
                tone: z.enum(["warm", "cool"]).describe("Color temperature for visual balance"),
                purpose: z.string().describe("What this post achieves in the feed story"),
                composition: z.string().describe("Specific composition and framing details"),
                styleDirection: z.string().describe("Unique styling direction for this specific post"),
              }),
            )
            .length(9),
        }),
        prompt: `You are Maya, an expert Instagram visual strategist and fashion photographer.

Design a cohesive 9-post Instagram feed for a ${businessType} with this brand identity:
- Brand Vibe: ${brandVibe}
- Color Palette: ${colorPalette}
- Feed Story: ${feedStory}
- Username: ${username}
- Brand Name: ${brandName}

${researchInsights ? `\n**Research Insights:**\n${researchInsights}\n` : ""}

Create a unique feed layout that:
1. Has visual rhythm and flow (balance warm/cool tones, vary post types strategically)
2. Tells a compelling story across all 9 posts through VISUALS
3. Showcases personality, expertise, and lifestyle authentically
4. Uses diverse post types: Close-Up (face focus), Half Body (upper body), Full Body (complete outfit), Lifestyle (environment/activity), Object (styled flatlay)
5. Each post should have a clear visual purpose in the overall narrative

For each post, provide:
- Type and tone for visual balance
- Specific purpose in the feed story
- Unique composition and styling direction

Focus ONLY on the visual strategy. Bio and captions will be handled separately by specialists.

Be creative and authentic. No generic templates - every element should feel custom-designed for this specific brand.`,
      })

      console.log("[v0] [SERVER] AI-generated feed design complete:", feedDesign.visualRhythm)

      const posts = feedDesign.posts.map((post, index) => {
        if (post.type === "Object") {
          return {
            id: `post-${index + 1}`,
            title: "Styled Moment",
            description: `${post.purpose}. ${post.composition}`,
            category: "Object",
            prompt: `${colorPalette.replace(/#[0-9a-fA-F]{6}/g, "").trim()} styled flatlay photography, ${post.styleDirection}, elegant arrangement, overhead shot with soft directional natural lighting creating gentle shadows, professional editorial quality with ${brandVibe} aesthetic, carefully curated brand-aligned objects, shallow depth of field with creamy bokeh, subtle film grain texture, high-end commercial photography, sophisticated composition, trending Instagram aesthetic 2025, warm inviting atmosphere, cohesive color story`,
            textOverlay: undefined,
            purpose: post.purpose,
            composition: post.composition,
          }
        }

        const lensSpecs = {
          "Close-Up": "shot on 85mm lens f/1.4, shallow depth of field, creamy bokeh, face focus",
          "Half Body": "shot on 50mm lens f/2.0, medium depth of field, balanced composition, upper body focus",
          "Full Body": "shot on 35mm lens f/2.8, environmental context, full scene, head to toe",
          Lifestyle: "shot on 35mm lens f/2.0, natural environment, authentic moment, environmental storytelling",
        }

        const colorDescription = colorPalette
          .replace(/#[0-9a-fA-F]{6}/g, "")
          .replace(/,\s*,/g, ",")
          .trim()

        const lightingStyle = colorPalette.includes("dark")
          ? "dramatic lighting with moody shadows and high contrast, cinematic atmosphere"
          : "soft natural lighting with gentle shadows and even exposure, warm inviting glow"

        const genderStyling =
          user.gender === "woman" || user.gender === "female"
            ? "elegant flowing hair styled naturally, refined makeup with natural glow, feminine grace and confidence"
            : user.gender === "man" || user.gender === "male"
              ? "styled hair with clean lines, masculine confidence and presence, strong professional demeanor"
              : "styled appearance with confident presence, authentic professional energy"

        const fashionDetails =
          post.type === "Full Body"
            ? `wearing sophisticated ${colorDescription} attire with impeccable tailoring and refined silhouette, ${post.styleDirection}, styled with carefully chosen accessories that complement the overall aesthetic, complete outfit showcasing personal style and brand identity`
            : post.type === "Half Body"
              ? `dressed in elegant ${colorDescription} professional attire with attention to fabric quality and fit, ${post.styleDirection}, styled with minimal sophisticated accessories, upper body styling that conveys both professionalism and approachability`
              : post.type === "Close-Up"
                ? `styled with ${colorDescription} tones in clothing and background, ${post.styleDirection}, natural skin texture with healthy radiant glow, authentic expression that connects with viewers`
                : `authentic ${colorDescription} styling that feels natural and effortless, ${post.styleDirection}, environmental elements that tell a story, genuine moment captured with editorial quality`

        return {
          id: `post-${index + 1}`,
          title: `${post.type} ${post.type === "Lifestyle" ? "Moment" : "Portrait"}`,
          description: `${post.purpose}. ${post.composition}`,
          category: post.type,
          prompt: `${user.trigger_word}, ${genderStyling}, ${fashionDetails}, ${post.styleDirection}, ${lensSpecs[post.type as keyof typeof lensSpecs]}, ${lightingStyle}, natural skin texture with subtle film grain for authenticity, ${post.composition}, timeless elegance meets modern sophistication, high-end editorial photography with ${brandVibe} aesthetic, genuine professional presence that feels both aspirational and relatable, trending Instagram aesthetic 2025, cohesive visual story`,
          textOverlay: undefined,
          purpose: post.purpose,
          composition: post.composition,
        }
      })

      const postsWithoutCaptions = posts

      let feedId: string | null = null

      try {
        const sql = neon(process.env.DATABASE_URL!)

        const [feedLayout] = await sql`
          INSERT INTO feed_layouts (
            user_id, brand_vibe, business_type, color_palette,
            visual_rhythm, feed_story, research_insights, title, description,
            username, brand_name
          )
          VALUES (
            ${user.id}, ${brandVibe}, ${businessType}, ${colorPalette},
            ${feedDesign.visualRhythm}, ${feedStory}, ${researchInsights},
            ${`${businessType} Feed Strategy`}, ${feedStory},
            ${username}, ${brandName}
          )
          RETURNING id
        `

        feedId = feedLayout.id.toString()
        console.log("[v0] [SERVER] ✓ Feed layout created with ID:", feedId, "Username:", username, "Brand:", brandName)

        // Declare instagramBio variable here
        const instagramBio = await generateInstagramBio(user.id)

        await sql`
          INSERT INTO instagram_bios (feed_layout_id, bio_text, user_id)
          VALUES (${feedId}, ${instagramBio}, ${user.id})
        `
        console.log("[v0] [SERVER] ✓ Instagram bio generated:", instagramBio)

        for (const highlight of highlights) {
          await sql`
            INSERT INTO instagram_highlights (feed_layout_id, title, prompt, user_id)
            VALUES (${feedId}, ${highlight.title}, ${highlight.prompt}, ${user.id})
          `
        }
        console.log("[v0] [SERVER] ✓ Highlights saved with FLUX prompts:", highlights.length)

        for (let i = 0; i < postsWithoutCaptions.length; i++) {
          const post = postsWithoutCaptions[i]
          await sql`
            INSERT INTO feed_posts (
              feed_layout_id, user_id, position, prompt, post_type,
              caption, text_overlay_style, generation_status
            )
            VALUES (
              ${feedId}, ${user.id}, ${i}, ${post.prompt}, ${post.category},
              ${"Caption will be generated by Instagram Caption Strategist..."},
              ${post.textOverlay ? JSON.stringify(post.textOverlay) : null},
              'pending'
            )
          `
        }
        console.log("[v0] [SERVER] ✓ All", postsWithoutCaptions.length, "posts saved to database")

        console.log("[v0] [SERVER] 🎯 Step 3: Calling Instagram Caption Strategist directly...")
        try {
          const captionResult = await generateCaptionsForFeed({
            feedId,
            userId: user.id,
            brandVibe,
            businessType,
            colorPalette,
            feedStory,
            researchData: researchInsights, // Now using real research data
          })

          if (captionResult.success) {
            console.log(
              `[v0] [SERVER] ✓ Instagram Caption Strategist generated ${captionResult.captionsGenerated}/${captionResult.totalPosts} captions`,
            )
          } else {
            console.error("[v0] [SERVER] ⚠️ Caption Strategist completed with some errors")
          }
        } catch (captionError) {
          console.error("[v0] [SERVER] ⚠️ Error calling Caption Strategist:", captionError)
        }

        console.log("[v0] [SERVER] === TOOL EXECUTION COMPLETED SUCCESSFULLY ===")

        return `Perfect! I've created your complete Instagram feed visual strategy with 9 concept cards, and the Instagram Caption Strategist has generated authentic, engaging captions for each post using current trends and competitive insights from our research. (Feed ID: ${feedId})`
      } catch (error) {
        console.error("[v0] [SERVER] === TOOL EXECUTION FAILED ===")
        console.error("[v0] [SERVER] Error saving feed to database:", error)
        if (error instanceof Error) {
          console.error("[v0] [SERVER] Error details:", error.message)
        }
        return "I encountered an error while saving your feed strategy. Please try again."
      }
    } finally {
      activeFeedGenerations.delete(user.id)
      console.log("[v0] [SERVER] ✓ Cleared active feed generation flag for user:", user.id)
      // </CHANGE>
    }
  },
})

const generateStoryHighlightsTool = tool({
  description:
    "Generate cover images for all story highlights in the feed. Call this ONLY if user explicitly asks for highlights.",
  inputSchema: z.object({
    feedId: z.string().describe("The feed layout ID from generateCompleteFeed"),
    colorPalette: z.string().describe("The brand's color palette"),
    brandVibe: z.string().describe("The brand's aesthetic vibe"),
  }),
  execute: async ({ feedId, colorPalette, brandVibe }) => {
    console.log("[v0] [SERVER] === GENERATING STORY HIGHLIGHTS ===")
    console.log("[v0] [SERVER] Feed ID:", feedId, "Color Palette:", colorPalette)

    try {
      const sql = neon(process.env.DATABASE_URL || "")
      const supabase = await createServerClient()
      const {
        data: { user: authUser },
      } = await supabase.auth.getUser()

      if (!authUser) {
        return "Error: User not found"
      }

      const user = await getUserByAuthId(authUser.id)

      if (!user) {
        return "Error: User not found"
      }

      const highlights = await sql`
        SELECT * FROM instagram_highlights
        WHERE feed_layout_id = ${feedId}
        ORDER BY created_at ASC
      `

      console.log("[v0] [SERVER] Found", highlights.length, "highlights to generate")

      let successCount = 0
      const errors: string[] = []

      for (const highlight of highlights) {
        try {
          const conceptPrompt = `Instagram story highlight cover for "${highlight.title}". ${highlight.prompt}. ${colorPalette} color palette, ${brandVibe} aesthetic, minimalist design, professional quality, centered composition, soft lighting, elegant and cohesive with brand identity`

          const controller = new AbortController()
          const timeoutId = setTimeout(() => controller.abort(), 10000) // 10 second timeout

          const response = await fetch(
            `${process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000"}/api/maya/generate-image`,
            {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({
                conceptTitle: highlight.title,
                conceptDescription: highlight.prompt,
                conceptPrompt,
                category: "feed-design",
              }),
              signal: controller.signal,
            },
          )

          clearTimeout(timeoutId)

          if (response.ok) {
            const data = await response.json()

            await sql`
              UPDATE instagram_highlights
              SET prediction_id = ${data.predictionId},
                  cover_url = 'generating'
              WHERE id = ${highlight.id}
            `

            successCount++
            console.log("[v0] [SERVER] ✓ Started generation for highlight:", highlight.title)
          } else {
            const errorText = await response.text()
            console.error("[v0] [SERVER] ⚠️ Failed to generate highlight:", highlight.title, "Status:", response.status)
            errors.push(`${highlight.title}: ${response.status}`)
          }
        } catch (error) {
          console.error("[v0] [SERVER] ⚠️ Error generating highlight:", highlight.title, error)
          errors.push(`${highlight.title}: ${error instanceof Error ? error.message : "Unknown error"}`)
        }
      }

      console.log("[v0] [SERVER] === STORY HIGHLIGHTS GENERATION COMPLETE ===")

      if (successCount === 0) {
        return `I encountered issues generating the highlight covers. This might be due to rate limits or network issues. You can try again later by asking me to "generate highlights".`
      }

      if (errors.length > 0) {
        return `Started generating ${successCount} out of ${highlights.length} story highlight covers. Some failed due to rate limits or network issues. They'll appear in the preview as they complete.`
      }

      return `Started generating ${successCount} story highlight covers. They'll appear in the preview as they complete.`
    } catch (error) {
      console.error("[v0] [SERVER] Error in generateStoryHighlights:", error)
      return "I encountered an error generating story highlights. You can try again later by asking me to 'generate highlights'."
    }
  },
})

const generateProfileImageTool = tool({
  description:
    "Generate an intelligent FLUX prompt for the profile picture using AI. This creates a sophisticated, detailed prompt that matches the feed's aesthetic.",
  inputSchema: z.object({
    feedId: z.string().describe("The feed layout ID from generateCompleteFeed"),
    businessType: z.string().describe("What the user does"),
    colorPalette: z.string().describe("The brand's color palette"),
    brandVibe: z.string().describe("The brand's aesthetic vibe"),
  }),
  execute: async ({ feedId, businessType, colorPalette, brandVibe }) => {
    console.log("[v0] [SERVER] === GENERATING PROFILE IMAGE PROMPT WITH AI ===")
    console.log("[v0] [SERVER] Feed ID:", feedId, "Business Type:", businessType)

    try {
      const sql = neon(process.env.DATABASE_URL || "")
      const supabase = await createServerClient()
      const {
        data: { user: authUser },
      } = await supabase.auth.getUser()

      if (!authUser) {
        return "Error: User not found"
      }

      const user = await getUserByAuthId(authUser.id)

      if (!user) {
        return "Error: User not found"
      }

      const userDataResult = await sql`
        SELECT
          u.gender,
          um.trigger_word
        FROM users u
        LEFT JOIN user_models um ON u.id = um.user_id
        WHERE u.id = ${user.id}
        AND um.training_status = 'completed'
        ORDER BY um.created_at DESC
        LIMIT 1
      `

      let triggerWord = "person"
      let userGender = "person"

      if (userDataResult.length > 0) {
        triggerWord = userDataResult[0].trigger_word || "person"
        userGender = userDataResult[0].gender || "person"
      }

      const { object: profileDesign } = await generateObject({
        model: "anthropic/claude-sonnet-4",
        schema: z.object({
          styleDirection: z.string().describe("Specific styling direction for this profile image"),
          composition: z.string().describe("Composition and framing details"),
          lightingMood: z.string().describe("Lighting style and mood"),
          fashionDetails: z.string().describe("Clothing and styling details"),
        }),
        prompt: `You are Maya, an expert fashion photographer and Instagram strategist.

Create a sophisticated FLUX prompt for an Instagram profile picture for a ${businessType} with this brand identity:
- Brand Vibe: ${brandVibe}
- Color Palette: ${colorPalette}
- Gender: ${userGender}

The profile image should:
1. Be a close-up portrait (face focus, circular crop friendly)
2. Convey confidence, approachability, and professionalism
3. Match the ${brandVibe} aesthetic perfectly
4. Use ${colorPalette} in clothing and background
5. Feel authentic and editorial quality

Provide specific details for:
- Style direction (hair, makeup/grooming, expression, energy)
- Composition (framing, angle, focus)
- Lighting mood (natural/dramatic, soft/bold, warm/cool)
- Fashion details (clothing style, colors, accessories)

Be specific and sophisticated - this should feel like high-end editorial photography, not a generic headshot.`,
      })

      console.log("[v0] [SERVER] AI-generated profile design:", profileDesign.styleDirection)

      const genderStyling =
        userGender === "woman" || userGender === "female"
          ? "elegant flowing hair styled naturally, refined makeup with natural glow, feminine grace and confidence"
          : userGender === "man" || userGender === "male"
            ? "styled hair with clean lines, masculine confidence and presence, strong professional demeanor"
            : "styled appearance with confident presence, authentic professional energy"

      const profileImagePrompt = `${triggerWord}, confident ${businessType} professional with ${genderStyling}, ${profileDesign.fashionDetails}, ${profileDesign.styleDirection}, shot on 85mm lens f/1.4, shallow depth of field, creamy bokeh, face focus, ${profileDesign.lightingMood}, natural skin texture with subtle film grain for authenticity, ${profileDesign.composition}, timeless elegance meets modern sophistication, high-end editorial photography with ${brandVibe} aesthetic, perfect for Instagram profile picture, circular crop friendly, genuine professional presence that feels both aspirational and relatable, cohesive with ${colorPalette} color palette`

      await sql`
        UPDATE feed_layouts
        SET profile_image_prompt = ${profileImagePrompt}
        WHERE id = ${feedId}
      `

      console.log("[v0] [SERVER] ✓ Sophisticated profile image prompt saved to database")
      console.log("[v0] [SERVER] Prompt preview:", profileImagePrompt.substring(0, 150) + "...")
      return `Profile image prompt created with sophisticated styling! Users can click the profile placeholder to generate it.`
    } catch (error) {
      console.error("[v0] [SERVER] Error creating profile image prompt:", error)
      return "Error creating profile image prompt"
    }
  },
})

const rewriteCaptionTool = tool({
  description:
    "Rewrite a specific post's caption based on user instructions (make it longer, shorter, change topic, different tone, etc.)",
  inputSchema: z.object({
    feedId: z.string().describe("The feed layout ID"),
    postNumber: z.number().describe("The post number (1-9) as the user sees it in the grid"),
    instructions: z.string().describe("User's instructions for rewriting"),
    currentCaption: z.string().describe("The current caption text"),
    brandVibe: z.string().describe("The brand's aesthetic vibe for consistency"),
  }),
  execute: async ({ feedId, postNumber, instructions, currentCaption, brandVibe }) => {
    console.log("[v0] [MAYA] Rewriting caption...")
    console.log("[v0] [MAYA] Feed ID:", feedId)
    const position = postNumber - 1
    console.log("[v0] [MAYA] Post Number:", postNumber, "→ Position:", position)
    console.log("[v0] [MAYA] Instructions:", instructions)
    console.log("[v0] [MAYA] Current caption preview:", currentCaption.substring(0, 100) + "...")

    try {
      const { object: rewrittenCaption } = await generateObject({
        model: "anthropic/claude-sonnet-4",
        schema: z.object({
          caption: z.string().describe("The rewritten caption following user's instructions"),
        }),
        prompt: `You are Maya, an expert Instagram caption writer.

Rewrite this caption following the user's instructions:

**Current Caption:**
${currentCaption}

**User's Instructions:**
${instructions}

**Brand Vibe:** ${brandVibe}

Create a new caption that:
1. Follows the user's instructions precisely
2. Maintains the ${brandVibe} brand voice
3. Feels authentic and engaging
4. Has a clear hook and call-to-action
5. Is optimized for Instagram engagement

**CRITICAL WRITING STYLE:**
- Write in SIMPLE, EVERYDAY LANGUAGE - like texting a friend
- NEVER use em dashes (—) - use periods or commas instead
- Use short, punchy sentences that feel natural
- Sound like a real person, NOT like AI wrote it
- Avoid fancy words - use simple, conversational language
- Be authentic and relatable, not polished or formal
- Write how people actually talk on Instagram

**FORMATTING REQUIREMENTS:**
- Use double line breaks (\\n\\n) between paragraphs for readability
- Include 2-3 strategic emojis throughout (not just at the end)
- Place emojis at natural breaks to enhance meaning
- Keep paragraphs short (2-3 sentences max per paragraph)
- End with hashtags on a new line

Be creative and authentic - no generic templates.`,
      })

      console.log("[v0] [MAYA] ✓ AI generated new caption:", rewrittenCaption.caption.substring(0, 100) + "...")

      const sql = neon(process.env.DATABASE_URL || "")
      const supabase = await createServerClient()
      const {
        data: { user: authUser },
      } = await supabase.auth.getUser()

      if (!authUser) {
        console.error("[v0] [MAYA] ❌ No auth user found")
        return "Error: User not found"
      }

      const user = await getUserByAuthId(authUser.id)

      if (!user) {
        console.error("[v0] [MAYA] ❌ No user found")
        return "Error: User not found"
      }

      console.log("[v0] [MAYA] User ID:", user.id)

      const existingPost = await sql`
        SELECT id, caption, user_id, feed_layout_id, position
        FROM feed_posts
        WHERE feed_layout_id = ${feedId}
        AND position = ${position}
        AND user_id = ${user.id}
      `

      console.log("[v0] [MAYA] Existing post query result:", existingPost.length, "rows")
      if (existingPost.length > 0) {
        console.log("[v0] [MAYA] Found post:", {
          id: existingPost[0].id,
          position: existingPost[0].position,
          user_id: existingPost[0].user_id,
          feed_layout_id: existingPost[0].feed_layout_id,
          caption_preview: existingPost[0].caption.substring(0, 50) + "...",
        })
      } else {
        console.error("[v0] [MAYA] ❌ Post not found at position:", position, "in feed:", feedId)
        return `Error: Post ${postNumber} not found in the current feed.`
      }

      const postId = existingPost[0].id

      console.log("[v0] [MAYA] Attempting to update caption for post ID:", postId)
      const updateResult = await sql`
        UPDATE feed_posts
        SET caption = ${rewrittenCaption.caption}
        WHERE id = ${postId}
        AND feed_layout_id = ${feedId}
        AND user_id = ${user.id}
        RETURNING id, caption, position
      `

      console.log("[v0] [MAYA] Update result:", updateResult.length, "rows affected")
      if (updateResult.length > 0) {
        console.log("[v0] [MAYA] ✓ Caption updated successfully")
        console.log("[v0] [MAYA] Updated post position:", updateResult[0].position)
        console.log("[v0] [MAYA] New caption preview:", updateResult[0].caption.substring(0, 100) + "...")
      } else {
        console.error("[v0] [MAYA] ❌ No rows updated")
        return "Error: Failed to update caption. Please try again."
      }

      return `Perfect! I've rewritten the caption for post ${postNumber}. Here's the new version:\n\n"${rewrittenCaption.caption}"\n\nThe caption has been updated in your feed preview.`
    } catch (error) {
      console.error("[v0] [MAYA] ❌ Error rewriting caption:", error)
      if (error instanceof Error) {
        console.error("[v0] [MAYA] Error message:", error.message)
        console.error("[v0] [MAYA] Error stack:", error.stack)
      }
      return "Error rewriting caption. Please try again."
    }
  },
})

const callCaptionStrategistTool = tool({
  description:
    "Call the Instagram Caption Strategist to write or rewrite captions. Use this when users ask to change caption tone, style, or content.",
  inputSchema: z.object({
    feedId: z.string().describe("The feed layout ID"),
    postNumber: z.number().describe("The post number (1-9) to rewrite caption for"),
    instructions: z.string().describe("User's instructions for the caption"),
  }),
  execute: async ({ feedId, postNumber, instructions }) => {
    console.log("[v0] [MAYA] Calling Instagram Caption Strategist...")
    console.log("[v0] [MAYA] Feed ID:", feedId, "Post:", postNumber, "Instructions:", instructions)

    try {
      const supabase = await createServerClient()
      const {
        data: { user: authUser },
      } = await supabase.auth.getUser()

      if (!authUser) {
        return "Error: User not found"
      }

      const user = await getUserByAuthId(authUser.id)

      if (!user) {
        return "Error: User not found"
      }

      const sql = neon(process.env.DATABASE_URL || "")

      const position = postNumber - 1
      const [post] = await sql`
        SELECT * FROM feed_posts
        WHERE feed_layout_id = ${feedId}
        AND position = ${position}
        AND user_id = ${user.id}
      `

      if (!post) {
        return `Error: Post ${postNumber} not found`
      }

      const [brand] = await sql`
        SELECT * FROM user_personal_brand
        WHERE user_id = ${user.id}
        AND is_completed = true
        LIMIT 1
      `

      // Fetch research data to pass to the caption strategist if available
      let researchData = null
      if (post.feed_layout_id) {
        const [research] = await sql`
          SELECT * FROM content_research
          WHERE user_id = ${user.id}
          AND niche = ${post.feed_layout_id} -- Assuming niche can be derived from feed_layout_id for simplicity, adjust if needed
          ORDER BY updated_at DESC
          LIMIT 1
        `
        if (research) {
          researchData = research
        }
      }

      const response = await fetch(
        `${process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000"}/api/instagram-strategist/generate-captions`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            feedId,
            postId: post.id,
            postNumber,
            instructions,
            currentCaption: post.caption,
            brandProfile: brand,
            researchData, // Pass research data
          }),
        },
      )

      if (!response.ok) {
        return "Error: Failed to generate caption"
      }

      const data = await response.json()
      return `Perfect! I've updated the caption for post ${postNumber}:\n\n"${data.caption}"\n\nThe caption has been updated in your feed.`
    } catch (error) {
      console.error("[v0] [MAYA] Error calling Caption Strategist:", error)
      return "Error: Failed to generate caption"
    }
  },
})

export async function POST(req: Request) {
  console.log("[v0] [SERVER] 🚀 FEED CHAT API CALLED")
  console.log("[v0] [SERVER] Brave API Key present:", !!process.env.BRAVE_SEARCH_API_KEY)

  try {
    const body = await req.json()
    const messages = body.messages

    console.log("[v0] [SERVER] Messages received:", messages?.length)

    const supabase = await createServerClient()
    const {
      data: { user: authUser },
    } = await supabase.auth.getUser()

    if (!authUser) {
      console.error("[v0] [SERVER] No auth user")
      return new Response("Unauthorized", { status: 401 })
    }

    const user = await getUserByAuthId(authUser.id)

    if (!user) {
      console.error("[v0] [SERVER] No user found")
      return new Response("Unauthorized", { status: 401 })
    }

    console.log("[v0] [SERVER] User authenticated:", user.id)

    let messagesArray: CoreMessage[] = []
    try {
      messagesArray = messages
        .map((msg: any, index: number) => {
          if (!msg.role || (msg.role !== "user" && msg.role !== "assistant")) {
            console.warn(`[v0] [SERVER] Skipping message ${index} with invalid role:`, msg.role)
            return null
          }

          let textContent = ""

          if (typeof msg.content === "string") {
            textContent = msg.content
          } else if (Array.isArray(msg.content)) {
            textContent = msg.content
              .filter((part: any) => part.type === "text" && part.text)
              .map((part: any) => part.text)
              .join(" ")
              .trim()
          } else if (msg.parts && Array.isArray(msg.parts)) {
            textContent = msg.parts
              .filter((part: any) => part.type === "text" && part.text)
              .map((part: any) => part.text)
              .join(" ")
              .trim()
          }

          if (!textContent || textContent.trim() === "") {
            console.warn(`[v0] [SERVER] Skipping message ${index} with empty content`)
            return null
          }

          return {
            role: msg.role,
            content: textContent,
          } as CoreMessage
        })
        .filter((msg): msg is CoreMessage => msg !== null)

      console.log("[v0] [SERVER] Converted to", messagesArray.length, "core messages")

      if (messagesArray.length === 0) {
        console.error("[v0] [SERVER] ERROR: No valid messages after filtering")
        return new Response("No valid messages", { status: 400 })
      }
    } catch (parseError) {
      console.error("[v0] [SERVER] ERROR parsing messages:", parseError)
      return new Response("Invalid messages", { status: 400 })
    }

    console.log("[v0] [SERVER] Getting user context...")
    let userContext = ""
    try {
      const authId = authUser.id
      console.log("[v0] [SERVER] Using auth ID:", authId)

      const sql = neon(process.env.DATABASE_URL || "")

      const neonUser = user

      if (neonUser) {
        const contextParts: string[] = []

        const [brandResult] = await sql`
          SELECT * FROM user_personal_brand
          WHERE user_id = ${neonUser.id}
          AND is_completed = true
          LIMIT 1
        `

        if (brandResult) {
          contextParts.push("=== USER'S PERSONAL BRAND ===")
          if (brandResult.name) contextParts.push(`Name: ${brandResult.name}`)
          if (brandResult.business_type) contextParts.push(`Business Type: ${brandResult.business_type}`)
          if (brandResult.brand_vibe) contextParts.push(`Brand Vibe: ${brandResult.brand_vibe}`)
          if (brandResult.color_theme) contextParts.push(`Color Theme: ${brandResult.color_theme}`)

          try {
            let colorPalette = brandResult.color_palette
            if (typeof colorPalette === "string") {
              colorPalette = JSON.parse(colorPalette)
            }
            if (Array.isArray(colorPalette) && colorPalette.length > 0) {
              const colors = colorPalette.filter((c: any) => typeof c === "string" && c.trim().length > 0)
              if (colors.length > 0) {
                contextParts.push(`Brand Colors: ${colors.join(", ")}`)
                contextParts.push(`IMPORTANT: Use these exact brand colors in all visual prompts: ${colors.join(", ")}`)
              }
            }
          } catch (e) {
            console.error("[v0] [SERVER] Error parsing color_palette:", e)
          }

          contextParts.push("")
        }

        const existingFeeds = await sql`
          SELECT
            fl.id,
            fl.brand_vibe,
            fl.business_type,
            fl.color_palette,
            fl.visual_rhythm,
            fl.feed_story,
            fl.created_at,
            COUNT(fp.id) as post_count
          FROM feed_layouts fl
          LEFT JOIN feed_posts fp ON fl.id = fp.feed_layout_id
          WHERE fl.user_id = ${neonUser.id}
          GROUP BY fl.id, fl.brand_vibe, fl.business_type, fl.color_palette, fl.visual_rhythm, fl.feed_story, fl.created_at
          ORDER BY fl.created_at DESC
          LIMIT 1
        `

        if (existingFeeds.length > 0) {
          const latestFeed = existingFeeds[0]
          contextParts.push("=== EXISTING FEED STRATEGY ===")
          contextParts.push(`Feed ID: ${latestFeed.id}`)
          contextParts.push(`Brand Vibe: ${latestFeed.brand_vibe}`)
          contextParts.push(`Business Type: ${latestFeed.business_type}`)
          contextParts.push(`Color Palette: ${latestFeed.color_palette}`)
          contextParts.push(`Visual Rhythm: ${latestFeed.visual_rhythm}`)
          contextParts.push(`Feed Story: ${latestFeed.feed_story}`)
          contextParts.push(`Posts: ${latestFeed.post_count} concept cards created`)
          contextParts.push(`Created: ${new Date(latestFeed.created_at).toLocaleDateString()}`)
          contextParts.push("")
          contextParts.push(
            "IMPORTANT: A feed strategy already exists! Unless the user explicitly asks for a 'new feed' or 'fresh feed', you should refine and improve the existing feed instead of creating a new one. Use your expertise to suggest improvements, adjust specific posts, or refine the strategy.",
          )
          contextParts.push("")
        }

        userContext = contextParts.length > 0 ? `\n\n${contextParts.join("\n")}` : ""
      }

      console.log("[v0] [SERVER] User context retrieved, length:", userContext.length)
    } catch (contextError) {
      console.error("[v0] [SERVER] WARNING: Error getting user context, continuing without it:", contextError)
      userContext = ""
    }

    console.log("[v0] [SERVER] Building system prompt...")
    const enhancedSystemPrompt = MAYA_SYSTEM_PROMPT + MAYA_FEED_STRATEGIST_EXTENSION + userContext
    console.log("[v0] [SERVER] System prompt built, length:", enhancedSystemPrompt.length)

    console.log("[v0] [SERVER] Calling streamText...")
    try {
      const result = await streamText({
        model: "anthropic/claude-sonnet-4",
        system: enhancedSystemPrompt,
        messages: messagesArray,
        tools: {
          generateCompleteFeed: generateCompleteFeedTool,
          generateStoryHighlights: generateStoryHighlightsTool,
          generateProfileImage: generateProfileImageTool,
          rewriteCaption: rewriteCaptionTool,
          callCaptionStrategist: callCaptionStrategistTool,
        },
        maxSteps: 5,
      })

      console.log("[v0] [SERVER] streamText completed")
      console.log("[v0] [SERVER] === FEED CHAT API END (success) ===")
      return result.toUIMessageStreamResponse()
    } catch (streamError) {
      console.error("[v0] [SERVER] streamText failed")
      console.error("[v0] [SERVER] Stream error:", streamError)
      if (streamError instanceof Error) {
        console.error("[v0] [SERVER] Stream error message:", streamError.message)
        console.error("[v0] [SERVER] Stream error stack:", streamError.stack)
      }
      throw streamError
    }
  } catch (error) {
    console.error("[v0] [SERVER] === FEED CHAT API ERROR ===")
    console.error("[v0] [SERVER] Feed chat error:", error)
    if (error instanceof Error) {
      console.error("[v0] [SERVER] Error name:", error.name)
      console.error("[v0] [SERVER] Error message:", error.message)
      console.error("[v0] [SERVER] Error stack:", error.stack)
    }
    console.error("[v0] [SERVER] === FEED CHAT API END (error) ===")
    return new Response(
      JSON.stringify({
        error: "Internal Server Error",
        message: error instanceof Error ? error.message : "Unknown error",
        details: "Check server logs for more information",
      }),
      {
        status: 500,
        headers: { "Content-Type": "application/json" },
      },
    )
  }
}
