/**
 * Analytics Workflow
 *
 * Weekly summary workflow that analyzes email campaigns, identifies best performers,
 * and generates optimization recommendations for the Admin Supervisor.
 *
 * Responsibilities:
 * - Analyze last 7 days of campaigns
 * - Identify best subject lines and performing segments
 * - Find lowest performing content
 * - Generate Admin Summary Report
 * - Send report to ADMIN_EMAIL
 */

import { generateWeeklySummary } from "../tools/analyticsEmailTools"
import { generateText } from "ai"
import { sendEmailNow } from "../marketing/marketingAutomationAgent"

export interface WorkflowInput {
  adminEmail?: string // Optional override, defaults to ADMIN_EMAIL env var
}

export interface WorkflowOutput {
  success: boolean
  summary?: any
  report?: string
  emailSent?: boolean
  error?: string
}

/**
 * Main workflow execution function
 * Analyzes campaign performance and sends summary to admin
 */
export async function runWorkflow(input: WorkflowInput): Promise<WorkflowOutput> {
  console.log("[AnalyticsWorkflow] Starting weekly analytics workflow...")

  try {
    // Step 1: Generate weekly summary from analytics tools
    const summaryResult = await generateWeeklySummary()

    if (!summaryResult.success) {
      return {
        success: false,
        error: `Failed to generate summary: ${summaryResult.error}`,
      }
    }

    const summary = summaryResult.data
    console.log("[AnalyticsWorkflow] Weekly summary generated:", summary)

    // Step 2: Generate AI-powered Admin Summary Report using Content Tools
    const reportPrompt = `You are creating a weekly analytics report for Sandra, the founder of SSELFIE.

Analyze the following email campaign data from the last 7 days and create a concise, actionable summary report.

Data:
${JSON.stringify(summary, null, 2)}

Report structure:
1. **Executive Summary** (2-3 sentences on overall performance)
2. **Key Metrics** (highlight the most important numbers)
3. **Best Performers** (which campaigns/subject lines/segments performed best and why)
4. **Areas for Improvement** (which campaigns underperformed and optimization suggestions)
5. **Action Items** (3-5 specific recommendations for next week)

Tone: Professional, concise, data-driven, strategic.
Format: HTML with headings, bullet points, and clear sections.
No emojis.`

    const { text: report } = await generateText({
      model: "openai/gpt-4o",
      prompt: reportPrompt,
      temperature: 0.3,
    })

    console.log("[AnalyticsWorkflow] Admin summary report generated")

    // Step 3: Send report to admin email
    const adminEmail = input.adminEmail || process.env.ADMIN_EMAIL || "sandra@sselfie.com"

    const emailResult = await sendEmailNow(
      adminEmail,
      `SSELFIE Weekly Analytics Report - ${summary.period}`,
      `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: system-ui, -apple-system, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }
    h1 { color: #000; font-size: 24px; margin-bottom: 10px; }
    h2 { color: #000; font-size: 18px; margin-top: 30px; margin-bottom: 10px; }
    table { width: 100%; border-collapse: collapse; margin: 20px 0; }
    th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
    th { background: #f5f5f5; font-weight: 600; }
    .metric { font-size: 32px; font-weight: bold; color: #000; }
    .metric-label { font-size: 14px; color: #666; text-transform: uppercase; letter-spacing: 0.5px; }
    .metrics-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px; margin: 30px 0; }
    .metric-card { padding: 20px; background: #f9f9f9; border-radius: 8px; text-align: center; }
  </style>
</head>
<body>
  <h1>📊 SSELFIE Weekly Analytics Report</h1>
  <p style="color: #666; margin-bottom: 30px;">${summary.period}</p>
  
  <div class="metrics-grid">
    <div class="metric-card">
      <div class="metric-label">Total Sent</div>
      <div class="metric">${summary.overall.total_sent}</div>
    </div>
    <div class="metric-card">
      <div class="metric-label">Open Rate</div>
      <div class="metric">${summary.overall.open_rate}%</div>
    </div>
    <div class="metric-card">
      <div class="metric-label">Click Rate</div>
      <div class="metric">${summary.overall.click_rate}%</div>
    </div>
  </div>

  ${report}

  <hr style="margin: 40px 0; border: none; border-top: 1px solid #ddd;" />
  <p style="color: #999; font-size: 12px;">
    This report was automatically generated by the SSELFIE Analytics Workflow.
    <br />For questions, contact your AdminSupervisorAgent.
  </p>
</body>
</html>
      `,
    )

    if (!emailResult.success) {
      return {
        success: false,
        summary,
        report,
        emailSent: false,
        error: `Report generated but email failed: ${emailResult.error}`,
      }
    }

    console.log(`[AnalyticsWorkflow] Report sent to ${adminEmail}`)

    return {
      success: true,
      summary,
      report,
      emailSent: true,
    }
  } catch (error) {
    console.error("[AnalyticsWorkflow] Error:", error)
    return {
      success: false,
      error: error instanceof Error ? error.message : "Unknown error",
    }
  }
}
