/**
 * Pro Photoshoot Prompts
 * Universal prompt for grids 2-8, custom prompt for grid 1 (created by Maya)
 */

// Universal prompt for Grids 2-8 (Step 2)
export const UNIVERSAL_PROMPT = `Create a totally new 3x3 photo grid featuring the same model shown in nine distinct photographic compositions, maintaining perfect facial and body consistency. Each frame represents a new unique camera perspective: portrait close-up, mid-shot, full-body product shot, macro texture detail, low-angle dynamic pose, high-angle cinematic perspective, wide-angle lifestyle scene, ultra-wide environmental context, and over-the-shoulder narrative shot. The grid layout is clean and symmetrical with subtle separation lines. Each photo is realistically lit and color-graded for a cohesive visual set. The model's identity, outfit, and environment remain consistent across all shots, emphasizing photographic diversity and visual storytelling coherence. High-resolution, photorealistic style. The angle must be different from the reference image.`

export function getUniversalPrompt(): string {
  return UNIVERSAL_PROMPT
}

export function getPromptForGrid(
  gridNumber: number,
  customPromptData?: {
    outfit?: string
    location?: string
    colorGrade?: string
    mayaGeneratedPrompt?: string // Full prompt generated by Maya for Grid 1
  }
): string {
  if (gridNumber === 1) {
    // If Maya has already generated a full prompt, use it directly
    if (customPromptData?.mayaGeneratedPrompt) {
      return customPromptData.mayaGeneratedPrompt
    }

    // Otherwise, construct a base prompt from provided data (fallback)
    const outfit = customPromptData?.outfit || "stylish outfit"
    const location = customPromptData?.location || "modern setting"
    const colorGrade = customPromptData?.colorGrade || "natural tones"

    return `Create a 3x3 grid showcasing 9 distinct photographic angles of the subject from the reference image. Each frame captures a different perspective while maintaining absolute continuity in identity, styling, and environment. The grid layout is clean and symmetrical with subtle separation lines. Each photo is realistically lit and color-graded for a cohesive visual set. The model's identity, outfit, and environment remain consistent across all shots, emphasizing photographic diversity and visual storytelling coherence. High-resolution, photorealistic style. The angle must be different from the reference image. Maintain a strict perfect facial and body consistency.

Setting: ${location}, ${outfit}, natural lighting.

Angles include: Close-up portrait, Full body, Side profile, Over-shoulder, Waist-up/mid-shot, Environmental portrait, Candid moment, Dynamic movement, Elevated perspective.

Color grade: ${colorGrade}.`
  }

  // Grids 2-8: Use universal prompt (Step 2)
  return UNIVERSAL_PROMPT
}

export function getGridName(gridNumber: number): string {
  const names: Record<number, string> = {
    1: "Custom Concept",
    2: "Street Style",
    3: "Cozy Home",
    4: "Outdoor",
    5: "Professional",
    6: "Social",
    7: "Lifestyle",
    8: "Creative",
  }

  return names[gridNumber] || `Grid ${gridNumber}`
}

