// Importing necessary types or interfaces
import type { QualitySettings } from "./types" // Hypothetical import, adjust according to actual file structure

// Instagram aesthetic is now achieved through prompt keywords instead of LoRA
export const MAYA_DEFAULT_QUALITY_SETTINGS: QualitySettings = {
  guidance_scale: 3.5,
  num_inference_steps: 50,
  aspect_ratio: "4:5",
  megapixels: "1",
  output_format: "png",
  output_quality: 95,
  lora_scale: 1.0,
  disable_safety_checker: true,
  go_fast: false,
  num_outputs: 1,
  model: "dev",
  extra_lora: "https://huggingface.co/strangerzonehf/Flux-Super-Realism-LoRA/resolve/main/super-realism.safetensors",
  extra_lora_scale: 0.4,
}

export const MAYA_QUALITY_PRESETS = {
  portrait: {
    ...MAYA_DEFAULT_QUALITY_SETTINGS,
    aspect_ratio: "4:5",
    guidance_scale: 3.5,
    lora_scale: 1.0,
    num_inference_steps: 50,
    extra_lora: "https://huggingface.co/strangerzonehf/Flux-Super-Realism-LoRA/resolve/main/super-realism.safetensors",
    extra_lora_scale: 0.4,
  },
  headshot: {
    ...MAYA_DEFAULT_QUALITY_SETTINGS,
    aspect_ratio: "1:1",
    guidance_scale: 3.5,
    lora_scale: 1.0,
    num_inference_steps: 50,
    extra_lora: "https://huggingface.co/strangerzonehf/Flux-Super-Realism-LoRA/resolve/main/super-realism.safetensors",
    extra_lora_scale: 0.4,
  },
  "Close-Up": {
    ...MAYA_DEFAULT_QUALITY_SETTINGS,
    aspect_ratio: "4:5",
    guidance_scale: 3.5,
    lora_scale: 1.0,
    num_inference_steps: 50,
    extra_lora: "https://huggingface.co/strangerzonehf/Flux-Super-Realism-LoRA/resolve/main/super-realism.safetensors",
    extra_lora_scale: 0.4,
  },
  "Half Body": {
    ...MAYA_DEFAULT_QUALITY_SETTINGS,
    aspect_ratio: "4:5",
    guidance_scale: 3.5,
    lora_scale: 1.0,
    num_inference_steps: 50,
    extra_lora: "https://huggingface.co/strangerzonehf/Flux-Super-Realism-LoRA/resolve/main/super-realism.safetensors",
    extra_lora_scale: 0.4,
  },
  lifestyle: {
    ...MAYA_DEFAULT_QUALITY_SETTINGS,
    aspect_ratio: "4:5",
    guidance_scale: 3.5,
    lora_scale: 1.0,
    num_inference_steps: 50,
    extra_lora: "https://huggingface.co/strangerzonehf/Flux-Super-Realism-LoRA/resolve/main/super-realism.safetensors",
    extra_lora_scale: 0.4,
  },
  Lifestyle: {
    ...MAYA_DEFAULT_QUALITY_SETTINGS,
    aspect_ratio: "4:5",
    guidance_scale: 3.5,
    lora_scale: 1.0,
    num_inference_steps: 50,
    extra_lora: "https://huggingface.co/strangerzonehf/Flux-Super-Realism-LoRA/resolve/main/super-realism.safetensors",
    extra_lora_scale: 0.4,
  },
  Action: {
    ...MAYA_DEFAULT_QUALITY_SETTINGS,
    aspect_ratio: "4:5",
    guidance_scale: 3.5,
    lora_scale: 1.0,
    num_inference_steps: 50,
    extra_lora: "https://huggingface.co/strangerzonehf/Flux-Super-Realism-LoRA/resolve/main/super-realism.safetensors",
    extra_lora_scale: 0.4,
  },
  Environmental: {
    ...MAYA_DEFAULT_QUALITY_SETTINGS,
    aspect_ratio: "4:5",
    guidance_scale: 3.5,
    lora_scale: 1.0,
    num_inference_steps: 50,
    extra_lora: "https://huggingface.co/strangerzonehf/Flux-Super-Realism-LoRA/resolve/main/super-realism.safetensors",
    extra_lora_scale: 0.4,
  },
  editorial: {
    ...MAYA_DEFAULT_QUALITY_SETTINGS,
    aspect_ratio: "3:4",
    guidance_scale: 3.5,
    lora_scale: 1.0,
    num_inference_steps: 50,
    extra_lora: "https://huggingface.co/strangerzonehf/Flux-Super-Realism-LoRA/resolve/main/super-realism.safetensors",
    extra_lora_scale: 0.4,
  },
  default: MAYA_DEFAULT_QUALITY_SETTINGS,
}
