"use client"

import type React from "react"

import { useState, useEffect, useRef } from "react"
import { Button } from "@/components/ui/button"
import { useChat } from "@ai-sdk/react"
import { DefaultChatTransport } from "ai"
import { Textarea } from "@/components/ui/textarea"
import { Plus, History, MessageCircle, X, Minimize2, RefreshCw, ImageIcon, Upload } from "lucide-react"
import { toast } from "@/hooks/use-toast"

import FeedPostCard from "./feed-post-card"
import BrandProfileWizard from "./brand-profile-wizard"
import StoryHighlightCard from "./story-highlight-card"
import MayaChatHistory from "./maya-chat-history"
import FeedAnalyticsPanel from "./feed-analytics-panel"
import HashtagStrategyPanel from "./hashtag-strategy-panel"
import ImageGalleryModal from "./image-gallery-modal"
import ComingSoonScreen from "./coming-soon-screen"
import { Dialog, DialogContent } from "@/components/ui/dialog"
import useSWR, { mutate } from "swr"

interface FeedPost {
  id: string | number
  imageUrl: string | null
  status: "concept" | "generating" | "ready" | "error"
  title: string
  description: string
  prompt: string
  category: string
  caption?: string
  hashtags?: string
  textOverlay?: {
    text: string
    position: "top" | "center" | "bottom"
    font: string
    color: string
  }
  position: number // Added for FeedPostCard
}

interface InstagramProfile {
  profileImage: string
  name: string
  handle: string
  bio: string
  // </CHANGE>
  highlights: Array<{ title: string; coverUrl: string; description: string; type: "image" | "color"; id?: number }>
}

const fetcher = (url: string) => fetch(url).then((res) => res.json())

export default function FeedDesignerScreen() {
  const [isInitializing, setIsInitializing] = useState(true)
  const [isDesigning, setIsDesigning] = useState(false)
  const [isApplyingDesign, setIsApplyingDesign] = useState(false)
  const [isCreatingNewFeed, setIsCreatingNewFeed] = useState(false)
  const isCreatingNewFeedRef = useRef(false)
  const [isFeedGenerating, setIsFeedGenerating] = useState(false)
  // </CHANGE>
  const [feedPosts, setFeedPosts] = useState<FeedPost[]>([])
  const [profile, setProfile] = useState<InstagramProfile>({
    profileImage: "/placeholder.svg?height=80&width=80",
    name: "",
    handle: "",
    bio: "",
    // </CHANGE>
    highlights: [],
  })
  const [feedStrategy, setFeedStrategy] = useState<any>(null)
  // const [mobileView, setMobileView] = useState<"chat" | "preview">("chat") // REMOVED
  const [feedUrl, setFeedUrl] = useState<string | null>(null)
  const [currentFeedId, setCurrentFeedId] = useState<string | null>(null) // Added for tracking current feed ID
  const [generationError, setGenerationError] = useState<string | null>(null)
  const [hasTrainedModel, setHasTrainedModel] = useState<boolean>(true)
  const [currentPrompts, setCurrentPrompts] = useState<Array<{ label: string; prompt: string }>>([])
  const [brandData, setBrandData] = useState<any>(null)
  const [showBrandWizard, setShowBrandWizard] = useState(false)
  const [brandCompleted, setBrandCompleted] = useState(true) // Default to true to prevent premature rendering
  const [editingHighlights, setEditingHighlights] = useState(false)
  const [chatId, setChatId] = useState<number | null>(null)
  const [isLoadingChat, setIsLoadingChat] = useState(true)
  const [showHistory, setShowHistory] = useState(false)
  const savedMessageIds = useRef(new Set<string>())

  const [isGeneratingProfile, setIsGeneratingProfile] = useState(false)
  const [profileError, setProfileError] = useState<string | null>(null)
  const [profilePredictionId, setProfilePredictionId] = useState<string | null>(null)
  const [isProfileGenerated, setIsProfileGenerated] = useState(false)

  const isDesigningSetRef = useRef(false)

  // New state variables for wizard, analytics, and hashtags
  const [showAnalytics, setShowAnalytics] = useState(false)
  const [showHashtags, setShowHashtags] = useState(false)

  const [isChatOpen, setIsChatOpen] = useState(false)
  const [isChatMinimized, setIsChatMinimized] = useState(false)

  const [mayaThinking, setMayaThinking] = useState<string | null>(null) // Changed to setIsMayaThinking in update
  const [proactiveSuggestions, setProactiveSuggestions] = useState<string[]>([])
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false) //
  const [hasShownSuggestions, setHasShownSuggestions] = useState(false)

  const [isEditingBio, setIsEditingBio] = useState(false)
  const [bioValue, setBioValue] = useState(profile.bio)
  const [isSavingBio, setIsSavingBio] = useState(false)

  // State to track highlight image generation status
  const [highlightPredictions, setHighlightPredictions] = useState<Map<number, string>>(new Map())

  const [showNewFeedModal, setShowNewFeedModal] = useState(false)

  const [showProfileFullSize, setShowProfileFullSize] = useState(false)
  const [showProfileGallery, setShowProfileGallery] = useState(false)
  const [isReplacingProfile, setIsReplacingProfile] = useState(false)
  const profileFileInputRef = useRef<HTMLInputElement>(null)

  const [progressPolling, setProgressPolling] = useState(false)
  const progressIntervalRef = useRef<NodeJS.Timeout | null>(null)

  const { data: galleryData } = useSWR("/api/images", fetcher)
  const galleryImages = galleryData?.images || []

  const prevStatusRef = useRef<string>("")
  // </CHANGE>

  const [activeScreen, setActiveScreen] = useState<"feed" | "calendar" | "carousel" | "stories">("feed")
  const [isAddingRow, setIsAddingRow] = useState(false)

  const handleGenerateProfileImage = async () => {
    if (!feedUrl) return

    const feedId = feedUrl.split("/").pop()
    if (!feedId) return

    try {
      setIsGeneratingProfile(true)
      setProfileError(null)

      const response = await fetch(`/api/feed/${feedId}/generate-profile`, {
        method: "POST",
      })

      if (!response.ok) {
        throw new Error("Failed to start profile image generation")
      }

      const data = await response.json()
      setProfilePredictionId(data.predictionId)

      pollProfileImage(feedId, data.predictionId)
    } catch (error) {
      console.error("[v0] Error generating profile image:", error)
      setProfileError("Failed to generate profile image")
      setIsGeneratingProfile(false)
    }
  }

  const pollProfileImage = async (feedId: string, predictionId: string) => {
    const maxAttempts = 60
    let attempts = 0

    while (attempts < maxAttempts) {
      try {
        const response = await fetch(`/api/feed/${feedId}/check-profile?predictionId=${predictionId}`)

        if (!response.ok) {
          throw new Error("Failed to check profile image status")
        }

        const data = await response.json()

        if (data.status === "succeeded" && data.imageUrl) {
          await fetch(`/api/feed/${feedId}/profile-image`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ imageUrl: data.imageUrl }),
          })

          setProfile((prev) => ({ ...prev, profileImage: data.imageUrl }))
          setIsProfileGenerated(true)
          setIsGeneratingProfile(false)
          setProfilePredictionId(null)
          break
        }

        if (data.status === "failed") {
          setProfileError("Profile image generation failed")
          setIsGeneratingProfile(false)
          setProfilePredictionId(null)
          break
        }

        await new Promise((resolve) => setTimeout(resolve, 3000))
        attempts++
      } catch (error) {
        console.error("[v0] Error polling profile image:", error)
        attempts++
      }
    }

    if (attempts >= maxAttempts) {
      console.warn("[v0] Profile image polling timed out")
      setProfileError("Profile image generation timed out")
      setIsGeneratingProfile(false)
      setProfilePredictionId(null)
    }
  }

  const handleSaveBio = async () => {
    if (!feedUrl) return

    const feedId = feedUrl.split("/").pop()
    if (!feedId) return

    try {
      setIsSavingBio(true)

      const response = await fetch(`/api/feed/${feedId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.JSON.stringify({ bio: bioValue }),
      })

      if (!response.ok) {
        throw new Error("Failed to save bio")
      }

      setProfile((prev) => ({ ...prev, bio: bioValue }))
      setIsEditingBio(false)
    } catch (error) {
      console.error("[v0] Error saving bio:", error)
      alert("Failed to save bio. Please try again.")
    } finally {
      setIsSavingBio(false)
    }
  }

  const handleCancelBio = () => {
    setBioValue(profile.bio)
    setIsEditingBio(false)
  }

  useEffect(() => {
    setBioValue(profile.bio)
  }, [profile.bio])

  const { status, messages, sendMessage, setMessages, append } = useChat({
    transport: new DefaultChatTransport({ api: "/api/maya/feed-chat" }),
    initialMessages: [],
    onError: (error) => {
      console.error("[v0] Feed chat error:", error)
      setIsDesigning(false)
      setIsApplyingDesign(false)
      setMayaThinking(null)
      setIsFeedGenerating(false)
    },
    onFinish: async (message) => {
      const contentPreview = message.content ? message.content.substring(0, 100) : "(empty message)"
      console.log("[v0] Chat finished, message:", contentPreview)

      setMayaThinking(null)
      setIsDesigning(false)
      // </CHANGE>

      // Check if this was a feed generation
      if (
        message.content &&
        (message.content.includes("Feed ID:") || message.content.includes("complete Instagram feed"))
      ) {
        console.log("[v0] Feed generation completed, reloading feed...")
        setIsFeedGenerating(false)

        // Wait a moment for database to commit
        await new Promise((resolve) => setTimeout(resolve, 1000))

        // Reload the feed
        await loadLatestFeed()
      }
    },
  })

  const isTyping = status === "submitted" || status === "streaming"
  const [inputValue, setInputValue] = useState("")

  const messagesEndRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    const handleStreamingEnd = async () => {
      // When streaming ends, do one final poll to check for completion
      if (prevStatusRef.current === "streaming" && status === "ready" && progressPolling) {
        console.log("[v0] Chat finished, doing final progress check...")

        try {
          // Get user ID from client-side Supabase session
          const {
            data: { session },
          } = await fetch("/api/auth/session")
            .then((r) => r.json())
            .catch(() => ({ data: { session: null } }))
          const userId = session?.user?.id

          if (userId) {
            // Wait a moment for the final progress update to be written to Redis
            await new Promise((resolve) => setTimeout(resolve, 500))

            const response = await fetch(`/api/maya/feed-progress?userId=${userId}`)
            if (response.ok) {
              const data = await response.json()
              console.log("[v0] Final progress check:", data)

              if (data.status === "complete") {
                console.log("[v0] Feed generation complete, reloading...")

                // Clear thinking state
                setMayaThinking(null)
                setIsDesigning(false)
                setIsFeedGenerating(false)

                // Reload the feed
                await loadLatestFeed()
                console.log("[v0] Feed reload complete")
              }
            }
          }
        } catch (error) {
          console.error("[v0] Error in final progress check:", error)
        }

        // Stop polling after final check
        console.log("[v0] Stopping progress polling...")
        setProgressPolling(false)
        if (progressIntervalRef.current) {
          clearInterval(progressIntervalRef.current)
          progressIntervalRef.current = null
        }
      }
    }

    handleStreamingEnd()
  }, [status, progressPolling])
  // </CHANGE>

  useEffect(() => {
    if (status === "streaming" && !progressPolling) {
      console.log("[v0] Starting progress polling...")
      setProgressPolling(true)

      const pollProgress = async () => {
        try {
          // Get user ID from client-side Supabase session (no database query)
          const {
            data: { session },
          } = await fetch("/api/auth/session")
            .then((r) => r.json())
            .catch(() => ({ data: { session: null } }))
          const userId = session?.user?.id

          if (!userId) {
            console.log("[v0] No user session, skipping progress poll")
            return
          }

          const response = await fetch(`/api/maya/feed-progress?userId=${userId}`)

          if (response.ok) {
            const data = await response.json()
            console.log("[v0] Progress update:", data)

            if (data.status !== "idle" && data.message) {
              setMayaThinking(data.message)

              if (data.status === "complete") {
                console.log("[v0] Feed generation complete!")
                console.log("[v0] Feed ID from progress:", data.feedId)

                // Stop polling immediately
                setProgressPolling(false)
                if (progressIntervalRef.current) {
                  clearInterval(progressIntervalRef.current)
                  progressIntervalRef.current = null
                }

                // Clear thinking state
                setMayaThinking(null)
                setIsDesigning(false)
                setIsFeedGenerating(false)

                // Reload the feed immediately (no delay)
                console.log("[v0] Reloading feed now...")
                await loadLatestFeed()
                console.log("[v0] Feed reload complete")
              }
            }
          }
        } catch (error) {
          console.error("[v0] Error polling progress:", error)
        }
      }

      // Poll immediately, then every 3 seconds
      pollProgress()
      progressIntervalRef.current = setInterval(pollProgress, 3000)
    }

    // This prevents stopping before the final poll can detect completion

    return () => {
      if (progressIntervalRef.current) {
        clearInterval(progressIntervalRef.current)
        progressIntervalRef.current = null
      }
    }
  }, [status, progressPolling])
  // </CHANGE>

  useEffect(() => {
    // Only log and act if status actually changed
    if (prevStatusRef.current !== status) {
      console.log("[v0] Chat status changed:", prevStatusRef.current, "->", status)
      prevStatusRef.current = status

      if (status === "submitted" || status === "streaming") {
        // Check if the last user message is about creating a feed
        const lastUserMessage = messages.filter((m) => m.role === "user").pop()
        const messageText = lastUserMessage?.content?.toLowerCase() || ""

        if (
          messageText.includes("new feed") ||
          messageText.includes("create feed") ||
          messageText.includes("generate feed") ||
          messageText.includes("design feed")
        ) {
          console.log("[v0] Detected feed generation request, showing thinking overlay")
          setMayaThinking("Analyzing your brand and creating feed strategy...")
          setIsDesigning(true)
          setIsFeedGenerating(true)
        } else if (!mayaThinking) {
          // For other messages, show a generic thinking state
          setMayaThinking("Maya is thinking...")
        }
      } else if (status === "idle" || status === "error") {
        // Don't clear thinking state immediately - let onFinish handle it
        // This prevents flickering
      }
    }
  }, [status])
  // </CHANGE>

  const generatePersonalizedPrompts = (brand: any) => {
    return [
      {
        label: "Story Highlights",
        prompt: "Create my story highlights",
      },
      {
        label: "Profile Picture",
        prompt: "Create my profile picture",
      },
      {
        label: "Feed Layout",
        prompt: "Design my feed layout",
      },
      {
        label: "Instagram Strategy",
        prompt: "Create my instagram strategy",
      },
    ]
  }

  useEffect(() => {
    const initializeComponent = async () => {
      try {
        await loadBrandProfile()
        await loadLatestFeed() // This will now override brand profile with feed data
        await checkTrainedModel()
      } catch (error) {
        console.error("[v0] Error initializing component:", error)
      } finally {
        setIsInitializing(false)
      }
    }

    initializeComponent()
  }, [])

  //
  useEffect(() => {
    const autoGenerateFeed = async () => {
      if (
        brandCompleted &&
        brandData &&
        feedPosts.length === 0 &&
        !hasAutoGenerated &&
        !isDesigning &&
        !isApplyingDesign &&
        !currentFeedId // Only auto-generate if no current feed exists
      ) {
        console.log("[v0] Auto-generating feed STRATEGY (concepts only, no images)...")
        setHasAutoGenerated(true)
        setMayaThinking("Looking at your brand profile...")

        await new Promise((resolve) => setTimeout(resolve, 1000))

        setMayaThinking("Crafting your perfect Instagram strategy...")

        const autoPrompt = `Create my Instagram feed strategy based on my brand profile.`
        sendMessage({ text: autoPrompt })
      }
    }

    if (!isInitializing && !isLoadingChat) {
      autoGenerateFeed()
    }
  }, [
    brandCompleted,
    brandData,
    feedPosts.length,
    hasAutoGenerated,
    isDesigning,
    isApplyingDesign,
    isInitializing,
    isLoadingChat,
    currentFeedId,
  ])

  useEffect(() => {
    if (
      feedPosts.length === 9 &&
      feedPosts.every((p) => p.status === "concept") &&
      proactiveSuggestions.length === 0 &&
      !hasShownSuggestions
    ) {
      // Feed just generated, show proactive suggestions
      const suggestions = [
        "Want me to adjust the color palette?",
        "Should we add more lifestyle shots?",
        "I can make it more editorial if you'd like",
        "Need help with the captions?",
      ]
      setProactiveSuggestions(suggestions)
      setHasShownSuggestions(true)
    }
  }, [feedPosts, proactiveSuggestions.length, hasShownSuggestions])

  useEffect(() => {
    if (!feedUrl || profile.highlights.length === 0) return

    const feedId = feedUrl.split("/").pop()
    if (!feedId) return

    // Check which highlights need polling
    const highlightsToCheck = profile.highlights
      .map((h, index) => ({ highlight: h, index }))
      .filter(
        (
          { highlight, index }, // FIX: undeclared variable 'index' removed from here and used from closure
        ) =>
          highlight.coverUrl === "generating" ||
          (highlight.coverUrl.includes("placeholder") && !highlightPredictions.has(index)),
      )

    if (highlightsToCheck.length === 0) return

    console.log("[v0] Starting highlight polling for", highlightsToCheck.length, "highlights")

    const pollHighlights = async () => {
      for (const { highlight, index } of highlightsToCheck) {
        // Get the highlight ID from the database
        try {
          const response = await fetch(`/api/feed/${feedId}/highlights`)
          if (!response.ok) continue

          const data = await response.json()
          // Find the correct highlight using its potentially persisted ID
          const dbHighlight = data.highlights.find((h: any) => h.id === highlight.id)

          if (!dbHighlight || !dbHighlight.prediction_id) continue

          // Check if this prediction is already being polled
          if (highlightPredictions.has(index)) continue

          // Start polling this highlight
          setHighlightPredictions((prev) => new Map(prev).set(index, dbHighlight.prediction_id))
          pollSingleHighlight(feedId, dbHighlight.id, dbHighlight.prediction_id, index)
        } catch (error) {
          console.error("[v0] Error checking highlight:", error)
        }
      }
    }

    pollHighlights()
  }, [feedUrl, profile.highlights, highlightPredictions])

  const pollSingleHighlight = async (feedId: string, highlightId: number, predictionId: string, index: number) => {
    const maxAttempts = 60
    let attempts = 0

    console.log("[v0] [HIGHLIGHT DEBUG] Starting poll for highlight:", {
      feedId,
      highlightId,
      predictionId,
      index,
    })

    while (attempts < maxAttempts) {
      try {
        const response = await fetch(
          `/api/feed/${feedId}/check-highlight?predictionId=${predictionId}&highlightId=${highlightId}`,
        )

        if (!response.ok) {
          console.error("[v0] [HIGHLIGHT DEBUG] Check highlight failed:", response.status)
          throw new Error("Failed to check highlight status")
        }

        const data = await response.json()
        console.log("[v0] [HIGHLIGHT DEBUG] Poll attempt", attempts, "status:", data.status)

        if (data.status === "succeeded" && data.imageUrl) {
          console.log("[v0] [HIGHLIGHT DEBUG] Generation succeeded, saving to database:", {
            highlightId,
            imageUrl: data.imageUrl,
          })

          const saveResponse = await fetch(`/api/feed/${feedId}/highlight-image`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ highlightId, imageUrl: data.imageUrl }),
          })

          if (!saveResponse.ok) {
            const errorText = await saveResponse.text()
            console.error("[v0] [HIGHLIGHT DEBUG] Failed to save highlight image:", {
              status: saveResponse.status,
              error: errorText,
            })
          } else {
            const saveData = await saveResponse.json()
            console.log("[v0] [HIGHLIGHT DEBUG] Successfully saved highlight image:", saveData)
          }
          // </CHANGE>

          // Update the local state
          setProfile((prev) => ({
            ...prev,
            highlights: prev.highlights.map((h, i) => (i === index ? { ...h, coverUrl: data.imageUrl } : h)),
          }))

          console.log("[v0] [HIGHLIGHT DEBUG] Updated local state for highlight", index)

          // Remove from polling map
          setHighlightPredictions((prev) => {
            const newMap = new Map(prev)
            newMap.delete(index)
            return newMap
          })

          break
        }

        if (data.status === "failed") {
          console.error("[v0] [HIGHLIGHT DEBUG] Generation failed:", data.error)
          setHighlightPredictions((prev) => {
            const newMap = new Map(prev)
            newMap.delete(index)
            return newMap
          })
          break
        }

        await new Promise((resolve) => setTimeout(resolve, 3000))
        attempts++
      } catch (error) {
        console.error("[v0] [HIGHLIGHT DEBUG] Error polling highlight:", error)
        attempts++
      }
    }

    if (attempts >= maxAttempts) {
      console.warn("[v0] [HIGHLIGHT DEBUG] Polling timed out for highlight", index)
      setHighlightPredictions((prev) => {
        const newMap = new Map(prev)
        newMap.delete(index)
        return newMap
      })
    }
  }

  const loadBrandProfile = async () => {
    try {
      const [brandResponse, profileResponse] = await Promise.all([
        fetch("/api/profile/personal-brand"),
        fetch("/api/profile/info"),
      ])

      const brandData = await brandResponse.json()
      const profileData = await profileResponse.json()

      console.log("[v0] Brand profile data (for Maya context only):", brandData)

      if (brandData.exists && brandData.completed) {
        setBrandData(brandData.data)
        setBrandCompleted(true)
        setShowBrandWizard(false)
        // Don't set profile state here - it will be set from feed data only
        setCurrentPrompts(generatePersonalizedPrompts(brandData.data))
      } else {
        setShowBrandWizard(true)
        setBrandCompleted(false)
        setCurrentPrompts(generatePersonalizedPrompts(null))
      }
    } catch (error) {
      console.error("[v0] Error loading brand profile:", error)
      setCurrentPrompts(generatePersonalizedPrompts(null))
    }
  }

  const checkTrainedModel = async () => {
    try {
      console.log("[v0] Checking trained model status...")
      const response = await fetch("/api/training/status")
      const data = await response.json()
      console.log("[v0] Training status response:", data)

      const hasModel = data.hasTrainedModel === true
      console.log("[v0] Has trained model:", hasModel)

      setHasTrainedModel(hasModel)
    } catch (error) {
      console.error("[v0] Error checking trained model:", error)
      setHasTrainedModel(false)
    }
  }

  const checkFeedStatus = async () => {
    if (!currentFeedId) {
      // Use currentFeedId for checking status
      console.log("[v0] No current feed ID, skipping status check")
      setMayaThinking(null)
      setIsDesigning(false)
      setIsApplyingDesign(false)
      return
    }

    console.log("[v0] Checking feed status for feed:", currentFeedId)

    try {
      const response = await fetch(`/api/feed/${currentFeedId}/status`)
      if (!response.ok) {
        throw new Error("Failed to check feed status")
      }

      const data = await response.json()
      console.log("[v0] Feed status:", data.status)

      if (data.status === "complete") {
        console.log("[v0] Feed is complete! Loading feed data...")

        // Clear all thinking states
        setMayaThinking(null)
        setIsDesigning(false)
        setIsApplyingDesign(false)

        // Load the completed feed
        await loadLatestFeed()

        console.log("[v0] Feed loaded successfully")
      } else {
        console.log("[v0] Feed not complete yet, status:", data.status)
        setMayaThinking(null)
        setIsDesigning(false)
        setIsApplyingDesign(false)
      }
    } catch (error) {
      console.error("[v0] Error checking feed status:", error)
      setMayaThinking(null)
      setIsDesigning(false)
      setIsApplyingDesign(false)
    }
  }
  // </CHANGE>

  // </CHANGE>
  useEffect(() => {
    if (isTyping) {
      const lastMessage = messages[messages.length - 1]
      if (lastMessage?.role === "assistant") {
        const parts = lastMessage.parts || []
        const hasToolCalls = parts.some(
          (part: any) =>
            part.type === "tool-call" &&
            (part.toolName === "generateCompleteFeed" ||
              part.toolName === "rewriteCaption" ||
              part.toolName === "callCaptionStrategist"),
        )
        // </CHANGE>

        if (hasToolCalls) {
          console.log("[v0] Maya is designing feed strategy...")
          setIsDesigning(true)
          isDesigningSetRef.current = true

          const thinkingMessages = [
            "Analyzing your brand vibe...",
            "Choosing the perfect color palette...",
            "Designing your feed layout...",
            "Creating concepts that match your style...",
            "Almost there, adding the finishing touches...",
          ]

          let messageIndex = 0
          const thinkingInterval = setInterval(() => {
            if (messageIndex < thinkingMessages.length) {
              setMayaThinking(thinkingMessages[messageIndex])
              messageIndex++
            }
          }, 2000)
          ;(window as any).__mayaThinkingInterval = thinkingInterval

          // ✅ Fix #6: 5-minute timeout
          const timeoutId = setTimeout(
            () => {
              console.warn("[v0] Feed generation timed out after 5 minutes")
              if ((window as any).__mayaThinkingInterval) {
                clearInterval((window as any).__mayaThinkingInterval)
                ;(window as any).__mayaThinkingInterval = null
              }
              setMayaThinking(null)
              setIsDesigning(false)
              setIsApplyingDesign(false)
              isDesigningSetRef.current = false
              setGenerationError("Feed generation timed out. Please try again.")
            },
            5 * 60 * 1000,
          )
          ;(window as any).__feedTimeoutId = timeoutId
        }
      }
    }

    if (!isTyping && messages.length > 0) {
      const lastMessage = messages[messages.length - 1]
      if (lastMessage.role === "assistant") {
        if (isDesigningSetRef.current) {
          console.log("[v0] Maya finished responding, checking feed status...")
          setIsApplyingDesign(true)
          isDesigningSetRef.current = false

          if ((window as any).__feedTimeoutId) {
            clearTimeout((window as any).__feedTimeoutId)
            ;(window as any).__feedTimeoutId = null
          }

          if ((window as any).__mayaThinkingInterval) {
            clearInterval((window as any).__mayaThinkingInterval)
            ;(window as any).__mayaThinkingInterval = null
          }

          // Execute the status check
          checkFeedStatus()
        }
      }
    }
    // </CHANGE>
  }, [isTyping, messages, feedUrl, currentFeedId]) // Added currentFeedId dependency

  useEffect(() => {
    // const isLoading = status === "loading"; // Removed as isLoading is not used in this specific effect. The original code block had an error where `isLoading` was undeclared. This fix ensures the effect runs correctly without relying on an undeclared variable.
    if (status !== "loading" && messages.length > 0) {
      const lastMessage = messages[messages.length - 1]

      // Check if the last message is from the assistant and has tool invocations
      if (lastMessage.role === "assistant" && lastMessage.toolInvocations) {
        const feedGenerationTools = ["generateCompleteFeed"]
        const hasFeedTool = lastMessage.toolInvocations.some(
          (inv: any) => feedGenerationTools.includes(inv.toolName) && inv.state === "result",
        )

        if (hasFeedTool) {
          console.log("[v0] [FEED REFRESH] Feed generation tool completed, loading latest feed")
          setMayaThinking(null)

          // Load the latest feed after a short delay to ensure database writes are complete
          setTimeout(() => {
            console.log("[v0] [FEED REFRESH] Calling loadLatestFeed()")
            loadLatestFeed()
          }, 1000)
        }
      }
    }
  }, [messages, status]) // Changed dependency to 'status' to correctly track loading state
  // </CHANGE>

  //
  useEffect(() => {
    if (!isTyping && messages.length > 0) {
      const lastMessage = messages[messages.length - 1]

      // Check if the last message has tool invocations
      if (lastMessage.role === "assistant" && lastMessage.toolInvocations) {
        const feedGenerationTools = ["generateCompleteFeed", "rewriteCaption", "callCaptionStrategist"]
        const hasFeedTool = lastMessage.toolInvocations.some((inv: any) => feedGenerationTools.includes(inv.toolName))

        if (hasFeedTool) {
          console.log("[v0] Feed strategy tool completed, loading concept cards...")
          // Simply load the latest feed when tool completes
          loadLatestFeed()
            .then(() => {
              console.log("[v0] Feed concepts loaded successfully - users can now click to generate images")
              setMayaThinking(null)
            })
            .catch((error) => {
              console.error("[v0] Error loading feed:", error)
              setMayaThinking(null)
            })
        }
      }
    }
  }, [isTyping, messages])
  // </CHANGE>

  const loadLatestFeed = async () => {
    try {
      console.log("[v0] [FEED DEBUG] Loading latest feed...")
      const response = await fetch("/api/feed/latest")

      if (!response.ok) {
        console.log("[v0] [FEED DEBUG] Failed to load feed:", response.status)
        // If the latest feed fails to load, reset the currentFeedId
        setCurrentFeedId(null)
        return
      }

      const data = await response.json()

      if (data.exists && data.feed) {
        console.log("[v0] [FEED DEBUG] Latest feed found:", {
          feedId: data.feed.id,
          postsCount: data.posts?.length || 0,
          highlightsCount: data.highlights?.length || 0,
          username: data.username,
          brandName: data.brandName,
          bio: data.bio?.bio_text,
        })

        const actualBio = data.bio?.bio_text || ""
        const actualUsername = data.username || ""
        const actualBrandName = data.brandName || ""

        console.log("[v0] [FEED DEBUG] Using feed data:", {
          actualUsername,
          actualBrandName,
          actualBio: actualBio.substring(0, 50) + "...",
        })
        // </CHANGE>

        const strategy = {
          brandVibe: data.feed.brand_vibe,
          businessType: data.feed.business_type,
          colorPalette: data.feed.color_palette,
          visualRhythm: data.feed.visual_rhythm,
          feedStory: data.feed.feed_story,
          instagramBio: actualBio,
          highlights: data.highlights.map((h: any) => ({
            title: h.title,
            description: h.prompt,
            coverUrl: h.image_url || h.cover_url || "/placeholder.svg?height=64&width=64",
            type: h.icon_style || h.type || "image",
          })),
          posts: data.posts.map((p: any) => ({
            id: p.id,
            title: p.post_type || p.category,
            description: p.prompt,
            prompt: p.prompt,
            category: p.post_type || p.category,
            caption: p.caption,
            hashtags: p.hashtags,
            textOverlay: p.text_overlay_style,
          })),
        }

        setFeedStrategy(strategy)
        setFeedUrl(`/feed/${data.feed.id}`)
        setCurrentFeedId(data.feed.id.toString()) // Set the current feed ID

        const newProfile: InstagramProfile = {
          profileImage: data.feed.profile_image_url || "/placeholder.svg?height=80&width=80",
          name: actualBrandName,
          handle: actualUsername.startsWith("@") ? actualUsername : `@${actualUsername}`,
          bio: actualBio,
          highlights: data.highlights.map((h: any) => ({
            id: h.id,
            title: h.title,
            coverUrl: h.image_url || "/placeholder.svg?height=64&width=64",
            description: h.prompt,
            type: h.icon_style || h.type || "image",
          })),
        }

        console.log("[v0] [FEED DEBUG] Setting profile state:", {
          name: newProfile.name,
          handle: newProfile.handle,
          bio: newProfile.bio?.substring(0, 50) + "...",
        })

        if (data.feed.profile_image_url) {
          console.log("[v0] [FEED DEBUG] Loading saved profile image:", data.feed.profile_image_url)
          setIsProfileGenerated(true)
        }

        setProfile(newProfile)
        // </CHANGE>

        const postsWithConcepts = data.posts.map((p: any) => ({
          id: p.id,
          imageUrl: p.image_url,
          status: p.image_url ? ("ready" as const) : ("concept" as const),
          title: p.post_type || "Post",
          description: p.prompt || "",
          prompt: p.prompt || "",
          category: p.post_type || "Portrait",
          caption: p.caption || "",
          hashtags: p.hashtags,
          textOverlay: p.text_overlay_style,
          position: p.position,
        }))

        console.log(
          "[v0] [FEED DEBUG] Setting feed posts with captions:",
          postsWithConcepts.map((p) => ({
            id: p.id,
            position: p.position,
            caption: p.caption?.substring(0, 50) + "...",
          })),
        )

        setFeedPosts([...postsWithConcepts])

        console.log("[v0] ✓ Feed loaded with", postsWithConcepts.length, "concept cards")

        mutate("/api/feed-designer/preview")
        console.log("[v0] Invalidated studio feed preview cache")
      } else {
        console.log("[v0] No existing feed found")
        setProfile({
          profileImage: "/placeholder.svg?height=80&width=80",
          name: "",
          handle: "",
          bio: "",
          highlights: [],
        })
        setCurrentFeedId(null) // Reset current feed ID if none found
        // </CHANGE>
      }
    } catch (error) {
      console.error("[v0] Error loading latest feed:", error)
      setCurrentFeedId(null) // Reset on error as well
    }
  }

  const retryFailedPost = async (postIndex: number) => {
    const post = feedPosts[postIndex]
    if (!currentFeedId) return // Use currentFeedId

    try {
      setFeedPosts((prev) => prev.map((p, i) => (i === postIndex ? { ...p, status: "generating" as const } : p)))

      const response = await fetch(`/api/feed/${currentFeedId}/retry-post`, {
        // Use currentFeedId
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ postIndex }),
      })

      if (!response.ok) {
        throw new Error("Failed to retry generation")
      }

      await pollSinglePost(currentFeedId, postIndex) // Use currentFeedId
    } catch (error) {
      console.error("[v0] Error retrying post:", error)
      setFeedPosts((prev) => prev.map((p, i) => (i === postIndex ? { ...p, status: "error" as const } : p)))
    }
  }

  const pollSinglePost = async (feedId: string, postIndex: number, predictionId?: string) => {
    const maxAttempts = 60
    let attempts = 0

    while (attempts < maxAttempts) {
      try {
        const response = await fetch(
          predictionId ? `/api/feed/${feedId}/prediction/${predictionId}` : `/api/feed/${feedId}/progress`,
        )
        const data = await response.json()
        const post = predictionId ? data.prediction : data.posts[postIndex]

        if (!post) {
          console.error(`[v0] Post data not found for index ${postIndex}`)
          return
        }

        if (post.status === "completed" || post.status === "ready") {
          setFeedPosts((prev) =>
            prev.map((p, i) =>
              i === postIndex
                ? {
                    ...p,
                    imageUrl: post.image_url,
                    status: "ready" as const,
                  }
                : p,
            ),
          )
          break
        }

        if (post.status === "failed") {
          setFeedPosts((prev) => prev.map((p, i) => (i === postIndex ? { ...p, status: "error" as const } : p)))
          break
        }

        await new Promise((resolve) => setTimeout(resolve, 3000))
        attempts++
      } catch (error) {
        console.error("[v0] Error polling single post:", error)
        attempts++
      }
    }
    if (attempts >= maxAttempts) {
      console.warn(`[v0] Polling for post ${postIndex} timed out.`)
      setFeedPosts((prev) => prev.map((p, i) => (i === postIndex ? { ...p, status: "error" as const } : p)))
    }
  }

  const downloadFeed = async () => {
    const JSZip = (await import("jszip")).default
    const zip = new JSZip()

    feedPosts.forEach((post, index) => {
      if (post.imageUrl && post.status === "ready") {
        const base64Data = post.imageUrl.split(",")[1]
        zip.file(`post-${index + 1}.png`, base64Data, { base64: true })
      }
    })

    const captions = feedPosts
      .map((post, index) => {
        if (post.status === "ready") {
          return `Post ${index + 1}: ${post.title}\n${post.description}\n\n`
        }
        return ""
      })
      .join("")

    zip.file("captions.txt", captions)

    const blob = await zip.generateAsync({ type: "blob" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = "instagram-feed.zip"
    a.click()
    URL.revokeObjectURL(url)
  }

  const handleQuickPrompt = (prompt: string) => {
    if (isTyping) return
    sendMessage({ text: prompt })
    setProactiveSuggestions([])
  }

  const handleSendMessage = () => {
    const messageText = inputValue.trim()
    if (messageText && !isTyping) {
      console.log("[v0] Sending message:", messageText)

      // Save user message immediately before sending to AI
      if (chatId) {
        console.log("[v0] 💾 Saving user message to database")
        fetch("/api/maya/save-message", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            chatId,
            role: "user",
            content: messageText,
          }),
        })
          .then((res) => res.json())
          .then((data) => {
            if (data.success) {
              console.log("[v0] ✅ User message saved successfully")
            } else {
              console.error("[v0] ❌ Failed to save user message:", data.error)
            }
          })
          .catch((error) => {
            console.error("[v0] ❌ Error saving user message:", error)
          })
      } else {
        console.error("[v0] ❌ Cannot save user message - chatId is null")
      }

      sendMessage({ text: messageText })
      setInputValue("")
    }
  }
  // </CHANGE>

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" })
  }

  useEffect(() => {
    scrollToBottom()
  }, [messages, isTyping])

  const handleGeneratePost = async (feedId: string, postIndex: number) => {
    console.log("[v0] Generating post:", { feedId, postIndex })

    try {
      setFeedPosts((prev) => prev.map((p, i) => (i === postIndex ? { ...p, status: "generating" as const } : p)))

      const response = await fetch(`/api/feed/${feedId}/generate-post`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ postIndex }),
      })

      if (!response.ok) {
        throw new Error("Failed to generate post")
      }

      const pollInterval = setInterval(async () => {
        const progressResponse = await fetch(`/api/feed/${feedId}/progress`)
        const data = await progressResponse.json()
        const post = data.posts[postIndex]

        if (post.status === "completed") {
          clearInterval(pollInterval)
          setFeedPosts((prev) =>
            prev.map((p, i) =>
              i === postIndex
                ? {
                    ...p,
                    imageUrl: post.image_url,
                    status: "ready" as const,
                  }
                : p,
            ),
          )
        } else if (post.status === "failed") {
          clearInterval(pollInterval)
          setFeedPosts((prev) => prev.map((p, i) => (i === postIndex ? { ...p, status: "error" as const } : p)))
        }
      }, 3000)

      setTimeout(() => clearInterval(pollInterval), 120000) // 2 min timeout
    } catch (error) {
      console.error("[v0] Error generating post:", error)
      setFeedPosts((prev) => prev.map((p, i) => (i === postIndex ? { ...p, status: "error" as const } : p)))
    }
  }

  const handleBrandWizardComplete = () => {
    console.log("[v0] Brand wizard completed, reloading brand profile...")
    setShowBrandWizard(false)
    loadBrandProfile()
  }

  // Function to handle the completion of the Feed Wizard
  const handleWizardComplete = (data: any) => {
    // REMOVED: setShowWizard(false)
    const wizardPrompt = `Create my Instagram feed strategy. I'm a ${data.businessType} targeting ${data.targetAudience}. My brand vibe is ${data.brandVibe}. My goals are: ${data.goals}`
    sendMessage({ text: wizardPrompt })
  }

  const handleAddHighlight = () => {
    setProfile((prev) => ({
      ...prev,
      highlights: [...prev.highlights, { title: "", coverUrl: "generating", description: "", type: "image" }],
    }))
    setEditingHighlights(true)
  }

  const handleUpdateHighlight = async (
    index: number,
    data: { title: string; coverUrl: string; description: string; type: "image" | "color" },
  ) => {
    console.log("[v0] Updating highlight:", index, data)

    setProfile((prev) => {
      const newHighlights = [...prev.highlights]
      newHighlights[index] = { ...newHighlights[index], ...data }
      return { ...prev, highlights: newHighlights }
    })

    if (feedUrl && data.type === "image" && data.coverUrl && data.coverUrl.startsWith("data:")) {
      const feedId = feedUrl.split("/").pop()
      if (feedId) {
        try {
          console.log("[v0] Saving highlight image to database...")

          const response = await fetch(`/api/feed/${feedId}/save-highlight-image`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              highlightIndex: index,
              imageUrl: data.coverUrl,
              title: data.title,
              description: data.description,
            }),
          })

          if (!response.ok) {
            throw new Error("Failed to save highlight image")
          }

          const result = await response.json()
          console.log("[v0] ✅ Highlight image saved successfully:", result.imageUrl)

          // Update the highlight with the saved URL
          setProfile((prev) => {
            const newHighlights = [...prev.highlights]
            newHighlights[index] = { ...newHighlights[index], coverUrl: result.imageUrl }
            return { ...prev, highlights: newHighlights }
          })
        } catch (error) {
          console.error("[v0] ❌ Error saving highlight image:", error)
        }
      }
    }
    // </CHANGE>
  }

  const handleRemoveHighlight = (index: number) => {
    setProfile((prev) => ({
      ...prev,
      highlights: prev.highlights.filter((_, i) => i !== index),
    }))
  }

  useEffect(() => {
    console.log("[v0] 🚀 Feed designer mounted, calling loadChat()")
    loadChat()
  }, [])

  useEffect(() => {
    if (messages.length === 0) return

    const lastMessage = messages[messages.length - 1]

    // Only save assistant messages that haven't been saved yet
    if (lastMessage.role === "assistant" && chatId && !savedMessageIds.current.has(lastMessage.id)) {
      console.log("[v0] 💾 Saving assistant message to database")

      savedMessageIds.current.add(lastMessage.id)

      fetch("/api/maya/save-message", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          chatId,
          role: "assistant",
          content: typeof lastMessage.content === "string" ? lastMessage.content : JSON.stringify(lastMessage.content),
        }),
      })
        .then((res) => res.json())
        .then((data) => {
          if (data.success) {
            console.log("[v0] ✅ Assistant message saved successfully")
          } else {
            console.error("[v0] ❌ Failed to save assistant message:", data.error)
          }
        })
        .catch((error) => {
          console.error("[v0] ❌ Error saving assistant message:", error)
        })
    }
  }, [messages, chatId])
  // </CHANGE>

  const loadChat = async (specificChatId?: number) => {
    try {
      setIsLoadingChat(true)
      const url = specificChatId
        ? `/api/maya/load-chat?chatId=${specificChatId}&chatType=feed-designer`
        : "/api/maya/load-chat?chatType=feed-designer"
      console.log("[v0] Loading feed designer chat:", specificChatId || "active chat")
      console.log("[v0] Fetching from URL:", url)
      const response = await fetch(url)
      console.log("[v0] Load chat response status:", response.status, response.statusText)

      if (response.ok) {
        const data = await response.json()
        console.log("[v0] Loaded chat ID:", data.chatId, "Messages:", data.messages?.length || 0)
        setChatId(data.chatId)

        if (data.messages && Array.isArray(data.messages) && data.messages.length > 0) {
          setMessages(data.messages)
        } else {
          setMessages([])
        }

        setShowHistory(false)
      } else {
        console.error("[v0] ❌ Load chat failed with status:", response.status)
        try {
          const errorData = await response.json()
          console.error("[v0] ❌ Error response:", errorData)
        } catch (e) {
          console.error("[v0] ❌ Could not parse error response")
        }
      }
      // </CHANGE>
    } catch (error) {
      console.error("[v0] Error loading chat:", error)
      if (error instanceof Error) {
        console.error("[v0] ❌ Error details:", {
          message: error.message,
          stack: error.stack,
          name: error.name,
        })
      }
      // </CHANGE>
    } finally {
      setIsLoadingChat(false)
    }
  }

  const handleNewChat = async () => {
    try {
      const response = await fetch("/api/maya/new-chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ chatType: "feed-designer" }),
      })

      if (response.ok) {
        const data = await response.json()
        setChatId(data.chatId)
        savedMessageIds.current.clear()
        setMessages([])
        setShowHistory(false)
      }
    } catch (error) {
      console.error("[v0] Error creating new chat:", error)
    }
  }

  const handleSelectChat = (selectedChatId: number) => {
    if (selectedChatId !== chatId) {
      setChatId(selectedChatId)
      setMessages([])
      savedMessageIds.current.clear()
      loadChat(selectedChatId)
    }
  }

  // Moved the useEffect that was conditionally calling hooks to the top level of the component.
  // This ensures that hooks are always called in the same order, regardless of conditions.
  useEffect(() => {
    if (messages.length === 0) return

    const lastMessage = messages[messages.length - 1]

    if (lastMessage.role === "assistant") {
      const content = typeof lastMessage.content === "string" ? lastMessage.content : ""

      // Check if Maya is calling the feed generation tool
      if (content.includes("=== TOOL EXECUTION STARTED ===") || content.includes("Generating feed strategy")) {
        console.log("[v0] Feed generation tool detected")
        setIsFeedGenerating(true)
        setIsDesigning(true)
        setMayaThinking("Designing your feed strategy...")
      }

      // Check if feed generation completed
      if (content.includes("Feed ID:") && content.includes("complete")) {
        console.log("[v0] Feed generation completed")
        setIsFeedGenerating(false)
        setIsDesigning(false)
        setMayaThinking(null)
      }
    }
  }, [messages])

  if (isInitializing || isLoadingChat) {
    return (
      <div className="h-full flex items-center justify-center bg-stone-50">
        <div className="text-center">
          <div className="w-12 h-12 border-4 border-stone-950 border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
          <p className="text-sm text-stone-600">Loading feed designer...</p>
        </div>
      </div>
    )
  }

  const handleGenerateNewFeed = async () => {
    if (isCreatingNewFeedRef.current) {
      console.log("[v0] [NEW FEED] Already creating new feed, ignoring click")
      return
    }

    isCreatingNewFeedRef.current = true
    setIsCreatingNewFeed(true)

    try {
      console.log("[v0] [NEW FEED] Starting new feed generation")
      console.log("[v0] [NEW FEED] Current feed ID:", currentFeedId)

      // Delete current feed if exists
      if (currentFeedId) {
        console.log("[v0] [NEW FEED] Deleting current feed:", currentFeedId)
        const deleteResponse = await fetch(`/api/feed/${currentFeedId}`, { method: "DELETE" })
        console.log("[v0] [NEW FEED] Delete response status:", deleteResponse.status)

        if (deleteResponse.status === 429) {
          const data = await deleteResponse.json()
          toast({
            title: "Please wait",
            description: "Too many requests. Please wait a moment and try again.",
            variant: "destructive",
          })
          return
        }

        if (deleteResponse.ok) {
          console.log("[v0] [NEW FEED] Current feed deleted successfully")
        } else {
          const errorText = await deleteResponse.text()
          console.error("[v0] [NEW FEED] Failed to delete feed:", errorText)
        }

        await new Promise((resolve) => setTimeout(resolve, 1000))
      } else {
        console.log("[v0] [NEW FEED] No current feed to delete")
      }

      // Reset state
      console.log("[v0] [NEW FEED] Resetting UI state")
      setFeedPosts([])
      setProfile({
        profileImage: "/placeholder.svg?height=80&width=80",
        name: "",
        handle: "",
        bio: "",
        highlights: [],
      })
      setIsProfileGenerated(false)
      setFeedStrategy(null)
      setCurrentFeedId(null)

      setIsFeedGenerating(true)
      setIsDesigning(true)
      setMayaThinking("Starting your feed generation...")
      setShowNewFeedModal(false)

      await new Promise((resolve) => setTimeout(resolve, 500))

      console.log("[v0] [NEW FEED] Sending message to Maya")

      const messageContent =
        "Please design a complete new Instagram feed for me with 9 posts, bio, and highlights based on my brand profile."

      await sendMessage({ text: messageContent })
      // </CHANGE>

      console.log("[v0] [NEW FEED] Feed generation request sent to Maya")
    } catch (error) {
      console.error("[v0] [NEW FEED] Error:", error)
      setMayaThinking(null)
      setIsFeedGenerating(false)
      setIsDesigning(false)
      toast({
        title: "Error",
        description: "Failed to generate new feed. Please try again.",
        variant: "destructive",
      })
    } finally {
      isCreatingNewFeedRef.current = false
      setIsCreatingNewFeed(false)
    }
  }
  // </CHANGE>

  const handleUploadProfileImage = async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0]
    if (!file) return

    const feedId = currentFeedId // Use currentFeedId
    if (!feedId) return

    setIsReplacingProfile(true)
    setProfileError(null)

    const formData = new FormData()
    formData.append("image", file)

    try {
      const response = await fetch(`/api/feed/${feedId}/upload-profile-image`, {
        // Use currentFeedId
        method: "POST",
        body: formData,
      })

      if (!response.ok) {
        throw new Error("Failed to upload profile image")
      }

      const data = await response.json()
      setProfile((prev) => ({ ...prev, profileImage: data.imageUrl }))
      setIsProfileGenerated(true)
    } catch (error) {
      console.error("[v0] Error uploading profile image:", error)
      setProfileError("Failed to upload profile image")
    } finally {
      setIsReplacingProfile(false)
      if (profileFileInputRef.current) {
        profileFileInputRef.current.value = "" // Clear the input
      }
    }
  }

  const handleReplaceProfileFromGallery = async (imageUrl: string) => {
    const feedId = currentFeedId // Use currentFeedId
    if (!feedId) return

    setIsReplacingProfile(true)
    setShowProfileGallery(false)
    setProfileError(null)

    try {
      const response = await fetch(`/api/feed/${feedId}/update-profile-image`, {
        // Use currentFeedId
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ imageUrl }),
      })

      if (!response.ok) {
        throw new Error("Failed to update profile image")
      }

      setProfile((prev) => ({ ...prev, profileImage: imageUrl }))
      setIsProfileGenerated(true)
    } catch (error) {
      console.error("[v0] Error replacing profile image:", error)
      setProfileError("Failed to update profile image")
    } finally {
      setIsReplacingProfile(false)
    }
  }

  const handleAddRow = async () => {
    if (!currentFeedId) {
      toast({
        title: "No feed found",
        description: "Please generate a feed first",
        variant: "destructive",
      })
      return
    }

    setIsAddingRow(true)
    setMayaThinking("Designing 3 more posts for your feed...")

    try {
      console.log("[v0] [ADD-ROW] Adding row to feed:", currentFeedId)

      const response = await fetch(`/api/feed/${currentFeedId}/add-row`, {
        method: "POST",
      })

      if (!response.ok) {
        throw new Error("Failed to add row")
      }

      const data = await response.json()
      console.log("[v0] [ADD-ROW] Success:", data.posts.length, "new posts")

      setFeedPosts((prev) => [...data.posts, ...prev])
      // </CHANGE>

      setMayaThinking(null)

      toast({
        title: "Posts added!",
        description: "3 new posts have been added to the top of your feed",
      })

      setTimeout(() => {
        window.scrollTo({
          top: 0,
          behavior: "smooth",
        })
      }, 100)
      // </CHANGE>
    } catch (error) {
      console.error("[v0] [ADD-ROW] Error:", error)
      setMayaThinking(null)
      toast({
        title: "Error",
        description: "Failed to add new posts. Please try again.",
        variant: "destructive",
      })
    } finally {
      setIsAddingRow(false)
    }
  }
  // </CHANGE>

  return (
    <div className="h-full flex flex-col bg-stone-50">
      {showBrandWizard && !brandCompleted && (
        <BrandProfileWizard
          isOpen={showBrandWizard}
          onClose={() => setShowBrandWizard(false)}
          onComplete={handleBrandWizardComplete}
          existingData={brandData}
        />
      )}

      {showNewFeedModal && (
        <div
          className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4"
          onClick={() => setShowNewFeedModal(false)}
        >
          <div className="bg-white rounded-2xl shadow-2xl max-w-md w-full p-6" onClick={(e) => e.stopPropagation()}>
            <h3 className="font-serif text-2xl font-extralight tracking-[0.2em] uppercase text-stone-950 mb-4">
              GENERATE NEW FEED?
            </h3>
            <p className="text-sm text-stone-700 leading-relaxed mb-6">
              This will replace your current feed with a completely new strategy. Your existing posts and concepts will
              be cleared.
            </p>
            <div className="flex gap-3">
              <button
                onClick={() => setShowNewFeedModal(false)}
                className="flex-1 px-6 py-3 bg-stone-100 hover:bg-stone-200 rounded-lg text-sm font-medium tracking-wider uppercase text-stone-950 transition-all"
              >
                CANCEL
              </button>
              <button
                onClick={(e) => {
                  e.stopPropagation()
                  handleGenerateNewFeed()
                }}
                disabled={isCreatingNewFeedRef.current}
                className="flex-1 px-6 py-3 bg-stone-950 hover:bg-stone-800 rounded-lg text-sm font-medium tracking-wider uppercase text-white transition-all disabled:opacity-50 disabled:cursor-not-allowed"
              >
                CONTINUE
              </button>
            </div>
          </div>
        </div>
      )}

      <div className="flex-1 flex overflow-hidden">
        <div className="flex-1 flex flex-col bg-stone-50 overflow-hidden">
          {(isDesigning || isApplyingDesign || mayaThinking) && (
            <div className="absolute inset-0 bg-white/80 backdrop-blur-sm z-50 flex items-center justify-center">
              <div className="text-center max-w-md px-6">
                <div className="w-16 h-16 mx-auto mb-6 relative">
                  <div className="absolute inset-0 rounded-full bg-stone-200/20 animate-ping"></div>
                  <div className="relative w-16 h-16 rounded-full overflow-hidden border-2 border-stone-200">
                    <img
                      src="https://i.postimg.cc/fTtCnzZv/out-1-22.png"
                      alt="Maya"
                      className="w-full h-full object-cover"
                    />
                  </div>
                </div>
                <p className="text-base font-normal text-stone-950 mb-2">
                  {mayaThinking || (isDesigning ? "Designing your feed..." : "Applying design...")}
                </p>
                <p className="text-sm text-stone-600 leading-relaxed">
                  {mayaThinking
                    ? "This will just take a moment"
                    : isDesigning
                      ? "Creating a strategic 9-post layout tailored to your brand"
                      : "Your feed strategy is being loaded"}
                </p>
              </div>
            </div>
          )}

          <div className="flex-shrink-0 bg-white border-b border-stone-200 px-6 py-3">
            <div className="flex items-center justify-between max-w-4xl mx-auto">
              <h2 className="font-serif text-xl font-extralight tracking-[0.2em] uppercase text-stone-950">
                INSTAGRAM FEED DESIGNER
              </h2>
              <div className="flex items-center gap-2">
                <button
                  onClick={() => setActiveScreen("feed")}
                  className={`px-4 py-2 rounded-lg text-xs font-medium tracking-wider uppercase transition-all ${
                    activeScreen === "feed"
                      ? "bg-stone-950 text-white"
                      : "bg-stone-100 text-stone-600 hover:bg-stone-200"
                  }`}
                >
                  FEED DESIGNER
                </button>
                <button
                  onClick={() => setActiveScreen("calendar")}
                  className={`px-4 py-2 rounded-lg text-xs font-medium tracking-wider uppercase transition-all ${
                    activeScreen === "calendar"
                      ? "bg-stone-950 text-white"
                      : "bg-stone-100 text-stone-600 hover:bg-stone-200"
                  }`}
                >
                  CONTENT CALENDAR
                </button>
                <button
                  onClick={() => setActiveScreen("carousel")}
                  className={`px-4 py-2 rounded-lg text-xs font-medium tracking-wider uppercase transition-all ${
                    activeScreen === "carousel"
                      ? "bg-stone-950 text-white"
                      : "bg-stone-100 text-stone-600 hover:bg-stone-200"
                  }`}
                >
                  CAROUSEL
                </button>
                <button
                  onClick={() => setActiveScreen("stories")}
                  className={`px-4 py-2 rounded-lg text-xs font-medium tracking-wider uppercase transition-all ${
                    activeScreen === "stories"
                      ? "bg-stone-950 text-white"
                      : "bg-stone-100 text-stone-600 hover:bg-stone-200"
                  }`}
                >
                  STORIES
                </button>
              </div>
            </div>
          </div>

          {activeScreen === "feed" && (
            <div className="flex-1 overflow-y-auto pb-24 sm:pb-28 md:pb-32">
              <div className="max-w-4xl mx-auto p-3 sm:p-4 md:p-6">
                <div className="bg-white rounded-xl border border-stone-200 overflow-hidden mb-6">
                  {/* Profile Header */}
                  <div className="p-3 sm:p-4 md:p-6 border-b border-stone-200">
                    <div className="flex items-start gap-3 sm:gap-4 md:gap-6 mb-4 sm:mb-6">
                      <div className="relative group flex-shrink-0">
                        {!isProfileGenerated && !isGeneratingProfile && profile.profileImage.includes("placeholder") ? (
                          <button
                            onClick={handleGenerateProfileImage}
                            className="w-16 h-16 sm:w-20 sm:h-20 md:w-24 md:h-24 rounded-full overflow-hidden border-2 border-dashed border-stone-300 bg-stone-50 flex flex-col items-center justify-center hover:border-stone-400 hover:bg-stone-100 transition-all"
                          >
                            <span className="text-[10px] sm:text-xs font-medium text-stone-600 text-center px-2">
                              Generate Profile
                            </span>
                          </button>
                        ) : isGeneratingProfile ? (
                          <div className="w-16 h-16 sm:w-20 sm:h-20 md:w-24 md:h-24 rounded-full overflow-hidden border-2 border-stone-200 bg-stone-100 flex items-center justify-center">
                            <div className="relative w-8 h-8 sm:w-10 sm:h-10 md:w-12 md:h-12">
                              <div className="absolute inset-0 rounded-full bg-stone-200/20 animate-ping"></div>
                              <div className="relative w-full h-full rounded-full bg-stone-950 animate-spin border-4 border-transparent border-t-white"></div>
                            </div>
                          </div>
                        ) : (
                          <>
                            <button
                              onClick={() => setShowProfileFullSize(true)}
                              className="w-16 h-16 sm:w-20 sm:h-20 md:w-24 md:h-24 rounded-full overflow-hidden border-2 border-stone-200"
                            >
                              <img
                                src={profile.profileImage || "/placeholder.svg"}
                                alt={profile.name}
                                className="w-full h-full object-cover"
                              />
                            </button>
                            <div className="absolute inset-0 rounded-full bg-stone-950/0 group-hover:bg-stone-950/60 transition-all duration-300 flex items-center justify-center opacity-0 group-hover:opacity-100">
                              <div className="flex items-center gap-1">
                                {/* Replace from Gallery */}
                                <button
                                  onClick={() => setShowProfileGallery(true)}
                                  disabled={isReplacingProfile}
                                  className="p-2 bg-white/90 backdrop-blur-xl rounded-full hover:bg-white transition-all hover:scale-110 disabled:opacity-50"
                                  title="Replace from Gallery"
                                >
                                  <ImageIcon size={14} className="text-stone-950" strokeWidth={2} />
                                </button>

                                {/* Upload Own Image */}
                                <button
                                  onClick={() => profileFileInputRef.current?.click()}
                                  disabled={isReplacingProfile}
                                  className="p-2 bg-white/90 backdrop-blur-xl rounded-full hover:bg-white transition-all hover:scale-110 disabled:opacity-50"
                                  title="Upload Image"
                                >
                                  <Upload size={14} className="text-stone-950" strokeWidth={2} />
                                </button>

                                {/* Regenerate */}
                                <button
                                  onClick={handleGenerateProfileImage}
                                  disabled={isReplacingProfile}
                                  className="p-2 bg-white/90 backdrop-blur-xl rounded-full hover:bg-white transition-all hover:scale-110 disabled:opacity-50"
                                  title="Regenerate Profile Image"
                                >
                                  <RefreshCw size={14} className="text-stone-950" strokeWidth={2} />
                                </button>
                              </div>
                            </div>
                          </>
                        )}
                      </div>

                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 sm:gap-3 md:gap-4 mb-3 sm:mb-4">
                          <h2 className="text-sm sm:text-base md:text-xl font-normal text-stone-950 truncate">
                            {profile.handle}
                          </h2>
                          <button className="px-2 sm:px-3 md:px-4 py-1 sm:py-1.5 bg-stone-100 hover:bg-stone-200 rounded-lg text-[10px] sm:text-xs md:text-sm font-medium text-stone-950 transition-all whitespace-nowrap">
                            Edit profile
                          </button>
                        </div>

                        {/* Stats */}
                        <div className="flex items-center gap-3 sm:gap-4 md:gap-6 mb-3 sm:mb-4">
                          <div className="text-center">
                            <div className="text-xs sm:text-sm font-semibold text-stone-950">{feedPosts.length}</div>
                            <div className="text-[10px] sm:text-xs text-stone-500">posts</div>
                          </div>
                          <div className="text-center">
                            <div className="text-xs sm:text-sm font-semibold text-stone-950">1,234</div>
                            <div className="text-[10px] sm:text-xs text-stone-500">followers</div>
                          </div>
                          <div className="text-center">
                            <div className="text-xs sm:text-sm font-semibold text-stone-950">567</div>
                            <div className="text-[10px] sm:text-xs text-stone-500">following</div>
                          </div>
                        </div>

                        <div>
                          <div className="text-sm font-semibold text-stone-950 mb-1">{profile.name}</div>
                          {!isEditingBio ? (
                            <div
                              onClick={() => setIsEditingBio(true)}
                              className="text-sm text-stone-700 leading-relaxed whitespace-pre-wrap cursor-text hover:bg-stone-50 rounded px-2 py-1 -mx-2 -my-1 transition-all"
                              title="Click to edit bio"
                            >
                              {profile.bio}
                            </div>
                          ) : (
                            <div className="space-y-2">
                              <Textarea
                                value={bioValue}
                                onChange={(e) => setBioValue(e.target.value)}
                                className="text-sm resize-none bg-white border-stone-300 focus:border-stone-950"
                                rows={3}
                                maxLength={150}
                                placeholder="Write your bio..."
                              />
                              <div className="flex items-center justify-between">
                                <span className="text-xs text-stone-500">{bioValue.length}/150</span>
                                <div className="flex gap-2">
                                  <button
                                    onClick={handleCancelBio}
                                    disabled={isSavingBio}
                                    className="px-3 py-1.5 text-xs font-medium text-stone-600 hover:text-stone-950 transition-all disabled:opacity-50"
                                  >
                                    Cancel
                                  </button>
                                  <button
                                    onClick={handleSaveBio}
                                    disabled={isSavingBio || bioValue === profile.bio}
                                    className="px-3 py-1.5 bg-stone-950 hover:bg-stone-800 text-white text-xs font-medium rounded-lg transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                                  >
                                    {isSavingBio ? "Saving..." : "Save"}
                                  </button>
                                </div>
                              </div>
                            </div>
                          )}
                        </div>
                        {profileError && <p className="text-xs text-red-600 mt-2">{profileError}</p>}
                      </div>
                    </div>

                    {/* Story Highlights */}
                    <div className="flex items-center gap-3 sm:gap-4 overflow-x-auto pb-2 -mx-3 px-3 sm:mx-0 sm:px-0">
                      {profile.highlights.map((highlight, index) => (
                        <StoryHighlightCard
                          key={index}
                          highlight={highlight}
                          index={index}
                          onUpdate={handleUpdateHighlight}
                          onRemove={handleRemoveHighlight}
                          userColorTheme={brandData?.colorTheme}
                          feedId={currentFeedId || ""} // Use currentFeedId
                          isEditing={editingHighlights}
                        />
                      ))}

                      {(editingHighlights || profile.highlights.length === 0) && profile.highlights.length < 10 && (
                        <button
                          onClick={handleAddHighlight}
                          className="flex flex-col items-center gap-2 flex-shrink-0 w-[70px] sm:w-[80px] group"
                        >
                          <div className="w-14 h-14 sm:w-16 sm:h-16 rounded-full bg-stone-100 border-2 border-dashed border-stone-300 flex items-center justify-center group-hover:border-stone-400 group-hover:bg-stone-50 transition-all">
                            <span className="text-xl sm:text-2xl text-stone-400 group-hover:text-stone-600">+</span>
                          </div>
                          <span className="text-[10px] sm:text-xs text-stone-400 group-hover:text-stone-600">New</span>
                        </button>
                      )}
                    </div>
                  </div>

                  {/* Feed Posts Grid */}
                  {feedPosts.length > 0 && (
                    <div className="space-y-6 sm:space-y-8">
                      <div className="grid grid-cols-3 gap-0.5 sm:gap-1">
                        {feedPosts.map((post, index) => (
                          <FeedPostCard key={post.id} post={post} feedId={currentFeedId} onGenerated={loadLatestFeed} />
                        ))}
                      </div>

                      <div className="flex justify-center pt-2 sm:pt-4 pb-4">
                        <button
                          onClick={handleAddRow}
                          disabled={isAddingRow || !currentFeedId}
                          className="px-6 sm:px-8 py-3 sm:py-4 bg-stone-950 hover:bg-stone-800 text-white rounded-lg font-medium tracking-wider uppercase text-xs sm:text-sm transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2 sm:gap-3"
                        >
                          {isAddingRow ? (
                            <>
                              <div className="w-3 h-3 sm:w-4 sm:h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                              Adding Posts...
                            </>
                          ) : (
                            <>
                              <Plus className="w-4 h-4" />
                              Add Row (3 More Posts)
                            </>
                          )}
                        </button>
                      </div>
                      {/* </CHANGE> */}
                    </div>
                  )}
                </div>

                {/* Side Panels */}
                {(showAnalytics || showHashtags) && (
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
                    {showAnalytics && <FeedAnalyticsPanel feedStrategy={feedStrategy} />}
                    {showHashtags && <HashtagStrategyPanel businessType={brandData?.businessType} />}
                  </div>
                )}

                {/* Action Buttons */}
                {feedPosts.some((p) => p.status === "ready") && (
                  <div className="flex gap-3 justify-center">
                    {currentFeedId && ( // Use currentFeedId
                      <Button
                        onClick={() => window.open(`/feed/${currentFeedId}`, "_blank")} // Use currentFeedId
                        className="bg-stone-950 hover:bg-stone-800 text-white px-8 py-3 text-sm font-medium tracking-wider uppercase"
                      >
                        VIEW FULL FEED
                      </Button>
                    )}
                    <Button
                      onClick={downloadFeed}
                      variant="outline"
                      className="border-stone-300 bg-transparent px-8 py-3 text-sm font-medium tracking-wider uppercase"
                    >
                      DOWNLOAD ZIP
                    </Button>
                  </div>
                )}

                {/* Error Messages */}
                {generationError && (
                  <div className="bg-red-50 border border-red-200 rounded-xl p-4 mb-6">
                    <div className="flex items-start gap-3">
                      <div className="flex-1">
                        <p className="text-sm font-medium text-red-950 mb-1">Generation Error</p>
                        <p className="text-sm text-red-700">{generationError}</p>
                      </div>
                      <button
                        onClick={() => setGenerationError(null)}
                        className="text-red-400 hover:text-red-600 text-xl leading-none"
                      >
                        ×
                      </button>
                    </div>
                  </div>
                )}

                {!hasTrainedModel && (
                  <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 mb-6">
                    <div className="flex items-start gap-3">
                      <div className="flex-1">
                        <p className="text-sm font-medium text-amber-950 mb-1">Training Required</p>
                        <p className="text-sm text-amber-700 mb-3">
                          You need to train your personal model before generating feed images.
                        </p>
                        <Button
                          onClick={() => (window.location.href = "/?tab=studio")}
                          className="bg-amber-950 hover:bg-amber-800 text-white"
                        >
                          Go to Studio
                        </Button>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            </div>
          )}

          {/* Render other screens conditionally */}
          {activeScreen === "calendar" && (
            <ComingSoonScreen
              title="Content Calendar"
              description="Plan and schedule your Instagram posts with our intelligent content calendar. Visualize your posting strategy and maintain consistent engagement with your audience."
            />
          )}
          {activeScreen === "carousel" && (
            <ComingSoonScreen
              title="Carousel Creator"
              description="Create stunning multi-image carousel posts that tell your story across multiple slides. Perfect for tutorials, before-and-afters, and engaging narratives."
            />
          )}
          {activeScreen === "stories" && (
            <ComingSoonScreen
              title="Story Sequences"
              description="Design cohesive Instagram Story sequences that captivate your audience. Create professional story templates with consistent branding and flow."
            />
          )}

          {proactiveSuggestions.length > 0 && !isDesigning && !isApplyingDesign && !isFeedGenerating && (
            <div className="fixed bottom-24 right-6 bg-white rounded-2xl shadow-2xl border border-stone-200 p-4 max-w-sm z-40 animate-in slide-in-from-bottom-4">
              <div className="flex items-start gap-3 mb-3">
                <div className="w-10 h-10 rounded-full overflow-hidden border-2 border-stone-200 flex-shrink-0">
                  <img
                    src="https://i.postimg.cc/fTtCnzZv/out-1-22.png"
                    alt="Maya"
                    className="w-full h-full object-cover"
                  />
                </div>
                <div className="flex-1">
                  <h4 className="text-sm font-semibold text-stone-950 mb-1">Your feed looks great!</h4>
                  <p className="text-xs text-stone-600 mb-3">Want me to refine anything?</p>
                  <div className="space-y-2">
                    {proactiveSuggestions.map((suggestion, index) => (
                      <button
                        key={index}
                        onClick={() => {
                          handleQuickPrompt(suggestion)
                          setIsChatOpen(true)
                        }}
                        className="w-full text-left px-3 py-2 bg-stone-50 hover:bg-stone-100 rounded-lg text-xs text-stone-700 transition-all border border-stone-200"
                      >
                        {suggestion}
                      </button>
                    ))}
                  </div>
                </div>
                <button
                  onClick={() => setProactiveSuggestions([])}
                  className="text-stone-400 hover:text-stone-600 flex-shrink-0"
                >
                  <X size={16} />
                </button>
              </div>
            </div>
          )}

          {!isChatOpen && (
            <button
              onClick={() => setIsChatOpen(true)}
              className="fixed bottom-6 right-6 w-16 h-16 bg-stone-950 hover:bg-stone-800 text-white rounded-full shadow-2xl flex items-center justify-center transition-all z-40 group"
            >
              <MessageCircle size={28} className="group-hover:scale-110 transition-transform" />
              {(messages.length === 0 || proactiveSuggestions.length > 0) && (
                <div className="absolute -top-1 -right-1 w-4 h-4 bg-red-500 rounded-full animate-pulse"></div>
              )}
            </button>
          )}

          {isChatOpen && (
            <div
              className={`fixed bottom-6 right-6 bg-white rounded-2xl shadow-2xl border border-stone-200 z-50 transition-all ${
                isChatMinimized ? "w-80 h-16" : "w-96 h-[600px]"
              }`}
            >
              {/* Chat Header */}
              <div className="flex-shrink-0 border-b border-stone-200 p-4 bg-stone-50 rounded-t-2xl">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-full overflow-hidden border-2 border-stone-200">
                      <img
                        src="https://i.postimg.cc/fTtCnzZv/out-1-22.png"
                        alt="Maya"
                        className="w-full h-full object-cover"
                      />
                    </div>
                    {!isChatMinimized && (
                      <div>
                        <h3 className="text-sm font-bold text-stone-950">Maya</h3>
                        <p className="text-xs text-stone-500">Instagram Strategist</p>
                      </div>
                    )}
                  </div>

                  <div className="flex items-center gap-2">
                    {!isChatMinimized && (
                      <>
                        <button
                          onClick={() => setShowHistory(!showHistory)}
                          className="p-2 rounded-lg hover:bg-stone-200 transition-all"
                          title="Chat history"
                        >
                          <History size={16} />
                        </button>
                        <button
                          onClick={handleNewChat}
                          className="p-2 rounded-lg hover:bg-stone-200 transition-all"
                          title="New chat"
                        >
                          <Plus size={16} />
                        </button>
                      </>
                    )}
                    <button
                      onClick={() => setIsChatMinimized(!isChatMinimized)}
                      className="p-2 rounded-lg hover:bg-stone-200 transition-all"
                      title={isChatMinimized ? "Expand" : "Minimize"}
                    >
                      <Minimize2 size={16} />
                    </button>
                    <button
                      onClick={() => setIsChatOpen(false)}
                      className="p-2 rounded-lg hover:bg-stone-200 transition-all"
                      title="Close"
                    >
                      <X size={16} />
                    </button>
                  </div>
                </div>
              </div>

              {!isChatMinimized && (
                <>
                  {showHistory && (
                    <div className="flex-shrink-0 border-b border-stone-200 p-4 bg-stone-50 max-h-48 overflow-y-auto">
                      <MayaChatHistory
                        currentChatId={chatId}
                        onSelectChat={handleSelectChat}
                        onNewChat={handleNewChat}
                      />
                    </div>
                  )}

                  {/* Chat Messages */}
                  <div className="flex-1 overflow-y-auto p-4 space-y-4 h-[400px]">
                    {messages.length === 0 && !isTyping && !brandCompleted && (
                      <div className="flex flex-col items-center justify-center h-full px-4 py-8">
                        <div className="w-16 h-16 rounded-full overflow-hidden border-2 border-stone-200 mb-4">
                          <img
                            src="https://i.postimg.cc/fTtCnzZv/out-1-22.png"
                            alt="Maya"
                            className="w-full h-full object-cover"
                          />
                        </div>
                        <h3 className="text-lg font-bold text-stone-950 mb-2 text-center">
                          Let's Start with Your Brand
                        </h3>
                        <p className="text-xs text-stone-600 text-center mb-4 leading-relaxed">
                          I'll create your perfect Instagram feed once I understand your brand story
                        </p>
                        <Button
                          onClick={() => setShowBrandWizard(true)}
                          className="bg-stone-950 hover:bg-stone-800 text-white text-sm"
                        >
                          Complete Brand Profile
                        </Button>
                      </div>
                    )}

                    {messages.length === 0 &&
                      !isTyping &&
                      brandCompleted &&
                      !hasAutoGenerated &&
                      !currentFeedId && // Check for currentFeedId
                      !isFeedGenerating && ( // Hide this if feed is generating
                        <div className="flex flex-col items-center justify-center h-full px-4 py-8">
                          <div className="w-16 h-16 rounded-full overflow-hidden border-2 border-stone-200 mb-4">
                            <img
                              src="https://i.postimg.cc/fTtCnzZv/out-1-22.png"
                              alt="Maya"
                              className="w-full h-full object-cover"
                            />
                          </div>
                          <h3 className="text-lg font-bold text-stone-950 mb-2 text-center">
                            Ready to Design Your Feed?
                          </h3>
                          <p className="text-xs text-stone-600 text-center mb-4 leading-relaxed">
                            I'll create a strategic 9-post feed based on your brand profile
                          </p>

                          <Button
                            onClick={() =>
                              handleQuickPrompt("Create my Instagram feed strategy based on my brand profile.")
                            }
                            className="bg-stone-950 hover:bg-stone-800 text-white text-sm mb-3"
                          >
                            Generate My Feed
                          </Button>

                          <div className="text-xs text-stone-500 mb-3">or ask me about</div>

                          <div className="grid grid-cols-2 gap-2 w-full">
                            {currentPrompts.slice(0, 4).map((item, index) => (
                              <button
                                key={index}
                                onClick={() => handleQuickPrompt(item.prompt)}
                                className="px-2 py-2 bg-stone-50 border border-stone-200 rounded-lg hover:bg-stone-100 transition-all text-center"
                              >
                                <span className="text-xs font-medium text-stone-700">{item.label}</span>
                              </button>
                            ))}
                          </div>
                        </div>
                      )}

                    {messages.map((message, index) => (
                      <div
                        key={index}
                        className={`flex gap-2 ${message.role === "user" ? "justify-end" : "justify-start"}`}
                      >
                        {message.role === "assistant" && (
                          <div className="flex-shrink-0 w-7 h-7 rounded-full overflow-hidden border-2 border-stone-200">
                            <img
                              src="https://i.postimg.cc/fTtCnzZv/out-1-22.png"
                              alt="Maya"
                              className="w-full h-full object-cover"
                            />
                          </div>
                        )}
                        <div className={`max-w-[75%] ${message.role === "user" ? "order-2" : "order-1"}`}>
                          {message.parts &&
                            Array.isArray(message.parts) &&
                            message.parts.map((part, partIndex) => {
                              if (part.type === "text") {
                                return (
                                  <div
                                    key={partIndex}
                                    className={`rounded-2xl px-3 py-2 ${
                                      message.role === "user"
                                        ? "bg-stone-950 text-white"
                                        : "bg-stone-100 text-stone-950"
                                    }`}
                                  >
                                    <p className="text-xs leading-relaxed whitespace-pre-wrap">{part.text}</p>
                                  </div>
                                )
                              }
                              return null
                            })}
                        </div>
                      </div>
                    ))}

                    {isTyping && (
                      <div className="flex justify-start gap-2">
                        <div className="flex-shrink-0 w-7 h-7 rounded-full overflow-hidden border-2 border-stone-200">
                          <img
                            src="https://i.postimg.cc/fTtCnzZv/out-1-22.png"
                            alt="Maya"
                            className="w-full h-full object-cover"
                          />
                        </div>
                        <div className="bg-stone-100 rounded-2xl px-3 py-2">
                          <div className="flex gap-1">
                            <div className="w-2 h-2 rounded-full animate-bounce bg-stone-700"></div>
                            <div
                              className="w-2 h-2 rounded-full animate-bounce bg-stone-700"
                              style={{ animationDelay: "0.2s" }}
                            ></div>
                            <div
                              className="w-2 h-2 rounded-full animate-bounce bg-stone-700"
                              style={{ animationDelay: "0.4s" }}
                            ></div>
                          </div>
                        </div>
                      </div>
                    )}
                    <div ref={messagesEndRef} />
                  </div>

                  {/* Chat Input */}
                  <div className="flex-shrink-0 border-t border-stone-200 p-3">
                    <div className="flex gap-2">
                      <Textarea
                        value={inputValue}
                        onChange={(e) => setInputValue(e.target.value)}
                        placeholder="Ask Maya..."
                        className="flex-1 resize-none bg-stone-50 border-stone-200 text-sm max-h-[120px] overflow-y-auto"
                        rows={2}
                        disabled={isTyping || isFeedGenerating}
                        onKeyDown={(e) => {
                          if (e.key === "Enter" && !e.shiftKey) {
                            e.preventDefault()
                            handleSendMessage()
                          }
                        }}
                      />
                      <Button
                        onClick={handleSendMessage}
                        disabled={isTyping || !inputValue?.trim() || isFeedGenerating}
                        className="bg-stone-950 hover:bg-stone-800 text-white self-end px-4 text-sm"
                      >
                        Send
                      </Button>
                    </div>
                  </div>
                </>
              )}
            </div>
          )}

          <input
            ref={profileFileInputRef}
            type="file"
            accept="image/*"
            onChange={handleUploadProfileImage}
            className="hidden"
          />

          {showProfileGallery && (
            <ImageGalleryModal
              images={galleryImages}
              onSelect={handleReplaceProfileFromGallery}
              onClose={() => setShowProfileGallery(false)}
            />
          )}

          {showProfileFullSize && (
            <Dialog open={showProfileFullSize} onOpenChange={setShowProfileFullSize}>
              <DialogContent className="max-w-2xl p-0 bg-transparent border-none">
                <div className="relative">
                  <button
                    onClick={() => setShowProfileFullSize(false)}
                    className="absolute -top-12 right-0 px-4 py-2 text-sm text-white hover:text-stone-300 transition-colors"
                  >
                    Close
                  </button>
                  <img
                    src={profile.profileImage || "/placeholder.svg"}
                    alt={profile.name}
                    className="w-full h-auto rounded-2xl shadow-2xl"
                  />
                  <div className="mt-4 text-center">
                    <h3 className="text-xl font-bold text-white">{profile.name}</h3>
                    <p className="text-sm text-stone-300 mt-2">{profile.handle}</p>
                  </div>
                </div>
              </DialogContent>
            </Dialog>
          )}
        </div>
      </div>
    </div>
  )
}
