"use client"

import { useState, useEffect, useRef } from "react"
import { Button } from "@/components/ui/button"
import { useChat } from "@ai-sdk/react"
import { DefaultChatTransport } from "ai"
import { Textarea } from "@/components/ui/textarea"
import { Plus, History, MessageCircle, X, Minimize2, RefreshCw } from "lucide-react"

import FeedPostCard from "./feed-post-card"
import BrandProfileWizard from "./brand-profile-wizard"
import StoryHighlightCard from "./story-highlight-card"
import MayaChatHistory from "./maya-chat-history"
import FeedAnalyticsPanel from "./feed-analytics-panel"
import HashtagStrategyPanel from "./hashtag-strategy-panel"

interface FeedPost {
  id: string | number
  imageUrl: string | null
  status: "concept" | "generating" | "ready" | "error"
  title: string
  description: string
  prompt: string
  category: string
  caption?: string
  hashtags?: string
  textOverlay?: {
    text: string
    position: "top" | "center" | "bottom"
    font: string
    color: string
  }
  position: number // Added for FeedPostCard
}

interface InstagramProfile {
  profileImage: string
  name: string
  handle: string
  bio: string
  highlights: Array<{ title: string; coverUrl: string; description: string; type: "image" | "color" }>
}

export default function FeedDesignerScreen() {
  const [isInitializing, setIsInitializing] = useState(true)
  const [isDesigning, setIsDesigning] = useState(false)
  const [isApplyingDesign, setIsApplyingDesign] = useState(false)
  const [feedPosts, setFeedPosts] = useState<FeedPost[]>([])
  const [profile, setProfile] = useState<InstagramProfile>({
    profileImage: "/placeholder.svg?height=80&width=80",
    name: "Your Brand",
    handle: "@yourbrand",
    bio: "Loading your brand story...",
    highlights: [],
  })
  const [feedStrategy, setFeedStrategy] = useState<any>(null)
  // const [mobileView, setMobileView] = useState<"chat" | "preview">("chat") // REMOVED
  const [feedUrl, setFeedUrl] = useState<string | null>(null)
  const [generationError, setGenerationError] = useState<string | null>(null)
  const [hasTrainedModel, setHasTrainedModel] = useState<boolean>(true)
  const [currentPrompts, setCurrentPrompts] = useState<Array<{ label: string; prompt: string }>>([])
  const [brandData, setBrandData] = useState<any>(null)
  const [showBrandWizard, setShowBrandWizard] = useState(false)
  const [brandCompleted, setBrandCompleted] = useState(true) // Default to true to prevent premature rendering
  const [editingHighlights, setEditingHighlights] = useState(false)
  const [chatId, setChatId] = useState<number | null>(null)
  const [isLoadingChat, setIsLoadingChat] = useState(true)
  const [showHistory, setShowHistory] = useState(false)
  const savedMessageIds = useRef(new Set<string>())

  const [isGeneratingProfile, setIsGeneratingProfile] = useState(false)
  const [profileError, setProfileError] = useState<string | null>(null)
  const [profilePredictionId, setProfilePredictionId] = useState<string | null>(null)
  const [isProfileGenerated, setIsProfileGenerated] = useState(false)

  const isDesigningSetRef = useRef(false)

  // New state variables for wizard, analytics, and hashtags
  const [showAnalytics, setShowAnalytics] = useState(false)
  const [showHashtags, setShowHashtags] = useState(false)

  const [isChatOpen, setIsChatOpen] = useState(false)
  const [isChatMinimized, setIsChatMinimized] = useState(false)

  const [mayaThinking, setMayaThinking] = useState<string | null>(null)
  const [proactiveSuggestions, setProactiveSuggestions] = useState<string[]>([])
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false)
  const [hasShownSuggestions, setHasShownSuggestions] = useState(false)

  const [isEditingBio, setIsEditingBio] = useState(false)
  const [bioValue, setBioValue] = useState(profile.bio)
  const [isSavingBio, setIsSavingBio] = useState(false)

  // State to track highlight image generation status
  const [highlightPredictions, setHighlightPredictions] = useState<Map<number, string>>(new Map())

  const [showNewFeedModal, setShowNewFeedModal] = useState(false)

  const handleGenerateProfileImage = async () => {
    if (!feedUrl) return

    const feedId = feedUrl.split("/").pop()
    if (!feedId) return

    try {
      setIsGeneratingProfile(true)
      setProfileError(null)

      const response = await fetch(`/api/feed/${feedId}/generate-profile`, {
        method: "POST",
      })

      if (!response.ok) {
        throw new Error("Failed to start profile image generation")
      }

      const data = await response.json()
      setProfilePredictionId(data.predictionId)

      pollProfileImage(feedId, data.predictionId)
    } catch (error) {
      console.error("[v0] Error generating profile image:", error)
      setProfileError("Failed to generate profile image")
      setIsGeneratingProfile(false)
    }
  }

  const pollProfileImage = async (feedId: string, predictionId: string) => {
    const maxAttempts = 60
    let attempts = 0

    while (attempts < maxAttempts) {
      try {
        const response = await fetch(`/api/feed/${feedId}/check-profile?predictionId=${predictionId}`)

        if (!response.ok) {
          throw new Error("Failed to check profile image status")
        }

        const data = await response.json()

        if (data.status === "succeeded" && data.imageUrl) {
          // Save the image URL to the database
          await fetch(`/api/feed/${feedId}/profile-image`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ imageUrl: data.imageUrl }),
          })

          setProfile((prev) => ({ ...prev, profileImage: data.imageUrl }))
          setIsProfileGenerated(true)
          setIsGeneratingProfile(false)
          setProfilePredictionId(null)
          break
        }

        if (data.status === "failed") {
          setProfileError("Profile image generation failed")
          setIsGeneratingProfile(false)
          setProfilePredictionId(null)
          break
        }

        await new Promise((resolve) => setTimeout(resolve, 3000))
        attempts++
      } catch (error) {
        console.error("[v0] Error polling profile image:", error)
        attempts++
      }
    }

    if (attempts >= maxAttempts) {
      console.warn("[v0] Profile image polling timed out")
      setProfileError("Profile image generation timed out")
      setIsGeneratingProfile(false)
      setProfilePredictionId(null)
    }
  }

  const handleSaveBio = async () => {
    if (!feedUrl) return

    const feedId = feedUrl.split("/").pop()
    if (!feedId) return

    try {
      setIsSavingBio(true)

      const response = await fetch(`/api/feed/${feedId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ bio: bioValue }),
      })

      if (!response.ok) {
        throw new Error("Failed to save bio")
      }

      setProfile((prev) => ({ ...prev, bio: bioValue }))
      setIsEditingBio(false)
    } catch (error) {
      console.error("[v0] Error saving bio:", error)
      alert("Failed to save bio. Please try again.")
    } finally {
      setIsSavingBio(false)
    }
  }

  const handleCancelBio = () => {
    setBioValue(profile.bio)
    setIsEditingBio(false)
  }

  useEffect(() => {
    setBioValue(profile.bio)
  }, [profile.bio])

  const { status, messages, sendMessage, setMessages } = useChat({
    transport: new DefaultChatTransport({ api: "/api/maya/feed-chat" }),
    initialMessages: [],
    body: {
      chatId: chatId,
    },
    onError: (error) => {
      console.error("[v0] Feed chat error:", error)
      setIsDesigning(false)
    },
  })

  const isTyping = status === "submitted" || status === "streaming"
  const [inputValue, setInputValue] = useState("")

  const messagesEndRef = useRef<HTMLDivElement>(null)

  const generatePersonalizedPrompts = (brand: any) => {
    return [
      {
        label: "Story Highlights",
        prompt: "Create my story highlights",
      },
      {
        label: "Profile Picture",
        prompt: "Create my profile picture",
      },
      {
        label: "Feed Layout",
        prompt: "Design my feed layout",
      },
      {
        label: "Instagram Strategy",
        prompt: "Create my instagram strategy",
      },
    ]
  }

  useEffect(() => {
    const initializeComponent = async () => {
      try {
        await Promise.all([loadBrandProfile(), checkTrainedModel(), loadLatestFeed()])
      } catch (error) {
        console.error("[v0] Error initializing component:", error)
      } finally {
        setIsInitializing(false)
      }
    }

    initializeComponent()
  }, [])

  useEffect(() => {
    const autoGenerateFeed = async () => {
      // Only auto-generate if:
      // 1. Brand profile is completed
      // 2. No existing feed
      // 3. Haven't auto-generated yet this session
      if (brandCompleted && brandData && feedPosts.length === 0 && !hasAutoGenerated && !isDesigning) {
        console.log("[v0] Auto-generating feed from brand profile...")
        setHasAutoGenerated(true)
        setMayaThinking("Looking at your brand profile...")

        // Wait a moment for the thinking message to show
        await new Promise((resolve) => setTimeout(resolve, 1000))

        setMayaThinking("Crafting your perfect Instagram strategy...")

        // Auto-send message to Maya to generate feed
        const autoPrompt = `Create my Instagram feed strategy based on my brand profile.`
        sendMessage({ text: autoPrompt })
      }
    }

    if (!isInitializing && !isLoadingChat) {
      autoGenerateFeed()
    }
  }, [brandCompleted, brandData, feedPosts.length, hasAutoGenerated, isDesigning, isInitializing, isLoadingChat])

  useEffect(() => {
    if (
      feedPosts.length === 9 &&
      feedPosts.every((p) => p.status === "concept") &&
      proactiveSuggestions.length === 0 &&
      !hasShownSuggestions
    ) {
      // Feed just generated, show proactive suggestions
      const suggestions = [
        "Want me to adjust the color palette?",
        "Should we add more lifestyle shots?",
        "I can make it more editorial if you'd like",
        "Need help with the captions?",
      ]
      setProactiveSuggestions(suggestions)
      setHasShownSuggestions(true)
    }
  }, [feedPosts, proactiveSuggestions.length, hasShownSuggestions])

  useEffect(() => {
    if (!feedUrl || profile.highlights.length === 0) return

    const feedId = feedUrl.split("/").pop()
    if (!feedId) return

    // Check which highlights need polling
    const highlightsToCheck = profile.highlights
      .map((h, index) => ({ highlight: h, index }))
      .filter(
        (
          { highlight, index }, // FIX: undeclared variable 'index' removed from here and used from closure
        ) =>
          highlight.coverUrl === "generating" ||
          (highlight.coverUrl.includes("placeholder") && !highlightPredictions.has(index)),
      )

    if (highlightsToCheck.length === 0) return

    console.log("[v0] Starting highlight polling for", highlightsToCheck.length, "highlights")

    const pollHighlights = async () => {
      for (const { highlight, index } of highlightsToCheck) {
        // Get the highlight ID from the database
        try {
          const response = await fetch(`/api/feed/${feedId}/highlights`)
          if (!response.ok) continue

          const data = await response.json()
          const dbHighlight = data.highlights[index]

          if (!dbHighlight || !dbHighlight.prediction_id) continue

          // Check if this prediction is already being polled
          if (highlightPredictions.has(index)) continue

          // Start polling this highlight
          setHighlightPredictions((prev) => new Map(prev).set(index, dbHighlight.prediction_id))
          pollSingleHighlight(feedId, dbHighlight.id, dbHighlight.prediction_id, index)
        } catch (error) {
          console.error("[v0] Error checking highlight:", error)
        }
      }
    }

    pollHighlights()
  }, [feedUrl, profile.highlights, highlightPredictions])

  const pollSingleHighlight = async (feedId: string, highlightId: number, predictionId: string, index: number) => {
    const maxAttempts = 60
    let attempts = 0

    console.log("[v0] Polling highlight", index, "with prediction", predictionId)

    while (attempts < maxAttempts) {
      try {
        const response = await fetch(
          `/api/feed/${feedId}/check-highlight?predictionId=${predictionId}&highlightId=${highlightId}`,
        )

        if (!response.ok) {
          throw new Error("Failed to check highlight status")
        }

        const data = await response.json()

        if (data.status === "succeeded" && data.imageUrl) {
          console.log("[v0] Highlight", index, "generation succeeded:", data.imageUrl)

          // Save the image URL to the database
          await fetch(`/api/feed/${feedId}/highlight-image`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ highlightId, imageUrl: data.imageUrl }),
          })

          // Update the local state
          setProfile((prev) => ({
            ...prev,
            highlights: prev.highlights.map((h, i) => (i === index ? { ...h, coverUrl: data.imageUrl } : h)),
          }))

          // Remove from polling map
          setHighlightPredictions((prev) => {
            const newMap = new Map(prev)
            newMap.delete(index)
            return newMap
          })

          break
        }

        if (data.status === "failed") {
          console.error("[v0] Highlight", index, "generation failed:", data.error)
          setHighlightPredictions((prev) => {
            const newMap = new Map(prev)
            newMap.delete(index)
            return newMap
          })
          break
        }

        await new Promise((resolve) => setTimeout(resolve, 3000))
        attempts++
      } catch (error) {
        console.error("[v0] Error polling highlight:", error)
        attempts++
      }
    }

    if (attempts >= maxAttempts) {
      console.warn("[v0] Highlight", index, "polling timed out")
      setHighlightPredictions((prev) => {
        const newMap = new Map(prev)
        newMap.delete(index)
        return newMap
      })
    }
  }

  const loadBrandProfile = async () => {
    try {
      const response = await fetch("/api/profile/personal-brand")
      const data = await response.json()

      if (data.exists && data.completed) {
        setBrandData(data.data)
        setBrandCompleted(true)
        setShowBrandWizard(false)
        setProfile({
          profileImage: data.data.profileImage || "/placeholder.svg?height=80&width=80",
          name: data.data.name || "Your Brand",
          handle: `@${data.data.name?.toLowerCase().replace(/\s+/g, "") || "yourbrand"}`,
          bio: data.data.futureVision || data.data.currentSituation || "Building something amazing",
          highlights: data.data.highlights || [],
        })
        setCurrentPrompts(generatePersonalizedPrompts(data.data))
      } else {
        setShowBrandWizard(true)
        setBrandCompleted(false)
        setCurrentPrompts(generatePersonalizedPrompts(null))
      }
    } catch (error) {
      console.error("[v0] Error loading brand profile:", error)
      setCurrentPrompts(generatePersonalizedPrompts(null))
    }
  }

  const checkTrainedModel = async () => {
    try {
      console.log("[v0] Checking trained model status...")
      const response = await fetch("/api/training/status")
      const data = await response.json()
      console.log("[v0] Training status response:", data)

      const hasModel = data.hasTrainedModel === true
      console.log("[v0] Has trained model:", hasModel)

      setHasTrainedModel(hasModel)
    } catch (error) {
      console.error("[v0] Error checking trained model:", error)
      setHasTrainedModel(false)
    }
  }

  useEffect(() => {
    if (isTyping && messages.length > 0) {
      const lastMessage = messages[messages.length - 1]
      if (lastMessage.role === "assistant" && !isDesigningSetRef.current) {
        console.log("[v0] Maya is designing feed strategy...")
        setIsDesigning(true)
        isDesigningSetRef.current = true

        const thinkingMessages = [
          "Analyzing your brand vibe...",
          "Choosing the perfect color palette...",
          "Designing your feed layout...",
          "Creating concepts that match your style...",
          "Almost there, adding the finishing touches...",
        ]

        let messageIndex = 0
        const thinkingInterval = setInterval(() => {
          if (messageIndex < thinkingMessages.length) {
            setMayaThinking(thinkingMessages[messageIndex])
            messageIndex++
          }
        }, 2000)

        // Store interval ID to clear it later
        ;(window as any).__mayaThinkingInterval = thinkingInterval
      }
    }

    if (!isTyping && messages.length > 0) {
      const lastMessage = messages[messages.length - 1]
      if (lastMessage.role === "assistant") {
        console.log("[v0] Maya finished responding, reloading feed data in 2 seconds...")
        setIsApplyingDesign(true)
        isDesigningSetRef.current = false

        if ((window as any).__mayaThinkingInterval) {
          clearInterval((window as any).__mayaThinkingInterval)
          ;(window as any).__mayaThinkingInterval = null
        }
        setMayaThinking(null)

        setTimeout(() => {
          loadLatestFeed()
          setIsDesigning(false)
          setIsApplyingDesign(false)
        }, 2000)
      }
    }
  }, [isTyping, messages])

  const loadLatestFeed = async () => {
    try {
      console.log("[v0] Loading latest feed...")
      const response = await fetch("/api/feed/latest")

      if (!response.ok) {
        console.error("[v0] Failed to load feed:", response.status)
        return
      }

      const data = await response.json()

      if (data.exists && data.feed) {
        console.log("[v0] ✓ Latest feed found with", data.posts?.length || 0, "posts")

        const strategy = {
          brandVibe: data.feed.brand_vibe,
          businessType: data.feed.business_type,
          colorPalette: data.feed.color_palette,
          visualRhythm: data.feed.visual_rhythm,
          feedStory: data.feed.feed_story,
          instagramBio: data.bio?.bio_text || profile.bio,
          highlights: data.highlights.map((h: any) => ({
            title: h.title,
            description: h.prompt,
            coverUrl: h.image_url || h.cover_url || "/placeholder.svg?height=64&width=64",
            type: h.icon_style || h.type || "image",
          })),
          posts: data.posts.map((p: any) => ({
            id: p.id,
            title: p.post_type || p.category,
            description: p.prompt,
            prompt: p.prompt,
            category: p.post_type || p.category,
            caption: p.caption,
            hashtags: p.hashtags,
            textOverlay: p.text_overlay_style,
          })),
        }

        setFeedStrategy(strategy)
        setFeedUrl(`/feed/${data.feed.id}`)

        if (data.feed.profile_image_url) {
          console.log("[v0] Loading saved profile image:", data.feed.profile_image_url)
          setProfile((prev) => ({
            ...prev,
            profileImage: data.feed.profile_image_url,
          }))
          setIsProfileGenerated(true)
        }

        if (data.bio) {
          setProfile((prev) => ({
            ...prev,
            bio: data.bio.bio_text,
          }))
        }

        if (data.highlights.length > 0) {
          const mappedHighlights = data.highlights.map((h: any) => ({
            title: h.title,
            coverUrl: h.image_url || h.cover_url || "/placeholder.svg?height=64&width=64",
            description: h.prompt, // This is the FLUX prompt Maya generated
            type: h.icon_style || h.type || "image",
          }))
          console.log(
            "[v0] Loaded highlights with image URLs:",
            mappedHighlights.map((h) => ({ title: h.title, coverUrl: h.coverUrl })),
          )
          setProfile((prev) => ({
            ...prev,
            highlights: mappedHighlights,
          }))
        }

        const postsWithConcepts = data.posts.map((p: any) => ({
          id: p.id, // Use actual database ID
          imageUrl: p.image_url,
          status: p.image_url ? ("ready" as const) : ("concept" as const),
          title: p.post_type || "Post",
          description: p.prompt || "",
          prompt: p.prompt || "",
          category: p.post_type || "Portrait",
          caption: p.caption,
          hashtags: p.hashtags,
          textOverlay: p.text_overlay_style,
          position: p.position,
        }))

        setFeedPosts(postsWithConcepts)
        console.log("[v0] ✓ Feed loaded with", postsWithConcepts.length, "concept cards")
      } else {
        console.log("[v0] No existing feed found")
      }
    } catch (error) {
      console.error("[v0] Error loading latest feed:", error)
    }
  }

  const retryFailedPost = async (postIndex: number) => {
    const post = feedPosts[postIndex]
    if (!feedUrl) return

    const feedId = feedUrl.split("/").pop()
    if (!feedId) return

    try {
      setFeedPosts((prev) => prev.map((p, i) => (i === postIndex ? { ...p, status: "generating" as const } : p)))

      const response = await fetch(`/api/feed/${feedId}/retry-post`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ postIndex }),
      })

      if (!response.ok) {
        throw new Error("Failed to retry generation")
      }

      await pollSinglePost(feedId, postIndex)
    } catch (error) {
      console.error("[v0] Error retrying post:", error)
      setFeedPosts((prev) => prev.map((p, i) => (i === postIndex ? { ...p, status: "error" as const } : p)))
    }
  }

  const pollSinglePost = async (feedId: string, postIndex: number, predictionId?: string) => {
    const maxAttempts = 60
    let attempts = 0

    while (attempts < maxAttempts) {
      try {
        const response = await fetch(
          predictionId ? `/api/feed/${feedId}/prediction/${predictionId}` : `/api/feed/${feedId}/progress`,
        )
        const data = await response.json()
        const post = predictionId ? data.prediction : data.posts[postIndex]

        if (!post) {
          console.error(`[v0] Post data not found for index ${postIndex}`)
          return
        }

        if (post.status === "completed" || post.status === "ready") {
          setFeedPosts((prev) =>
            prev.map((p, i) =>
              i === postIndex
                ? {
                    ...p,
                    imageUrl: post.image_url,
                    status: "ready" as const,
                  }
                : p,
            ),
          )
          break
        }

        if (post.status === "failed") {
          setFeedPosts((prev) => prev.map((p, i) => (i === postIndex ? { ...p, status: "error" as const } : p)))
          break
        }

        await new Promise((resolve) => setTimeout(resolve, 3000))
        attempts++
      } catch (error) {
        console.error("[v0] Error polling single post:", error)
        attempts++
      }
    }
    if (attempts >= maxAttempts) {
      console.warn(`[v0] Polling for post ${postIndex} timed out.`)
      setFeedPosts((prev) => prev.map((p, i) => (i === postIndex ? { ...p, status: "error" as const } : p)))
    }
  }

  const downloadFeed = async () => {
    const JSZip = (await import("jszip")).default
    const zip = new JSZip()

    feedPosts.forEach((post, index) => {
      if (post.imageUrl && post.status === "ready") {
        const base64Data = post.imageUrl.split(",")[1]
        zip.file(`post-${index + 1}.png`, base64Data, { base64: true })
      }
    })

    const captions = feedPosts
      .map((post, index) => {
        if (post.status === "ready") {
          return `Post ${index + 1}: ${post.title}\n${post.description}\n\n`
        }
        return ""
      })
      .join("")

    zip.file("captions.txt", captions)

    const blob = await zip.generateAsync({ type: "blob" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = "instagram-feed.zip"
    a.click()
    URL.revokeObjectURL(url)
  }

  const handleQuickPrompt = (prompt: string) => {
    if (isTyping) return
    sendMessage({ text: prompt })
    setProactiveSuggestions([])
  }

  const handleSendMessage = () => {
    const messageText = inputValue.trim()
    if (messageText && !isTyping) {
      console.log("[v0] Sending message:", messageText)

      if (chatId) {
        fetch("/api/maya/save-message", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            chatId,
            role: "user",
            content: messageText,
          }),
        }).catch((error) => {
          console.error("[v0] Error saving user message:", error)
        })
      }

      sendMessage({ text: messageText })
      setInputValue("")
    }
  }

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" })
  }

  useEffect(() => {
    scrollToBottom()
  }, [messages, isTyping])

  const handleGeneratePost = async (feedId: string, postIndex: number) => {
    console.log("[v0] Generating post:", { feedId, postIndex })

    try {
      setFeedPosts((prev) => prev.map((p, i) => (i === postIndex ? { ...p, status: "generating" as const } : p)))

      const response = await fetch(`/api/feed/${feedId}/generate-post`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ postIndex }),
      })

      if (!response.ok) {
        throw new Error("Failed to generate post")
      }

      const pollInterval = setInterval(async () => {
        const progressResponse = await fetch(`/api/feed/${feedId}/progress`)
        const data = await progressResponse.json()
        const post = data.posts[postIndex]

        if (post.status === "completed") {
          clearInterval(pollInterval)
          setFeedPosts((prev) =>
            prev.map((p, i) =>
              i === postIndex
                ? {
                    ...p,
                    imageUrl: post.image_url,
                    status: "ready" as const,
                  }
                : p,
            ),
          )
        } else if (post.status === "failed") {
          clearInterval(pollInterval)
          setFeedPosts((prev) => prev.map((p, i) => (i === postIndex ? { ...p, status: "error" as const } : p)))
        }
      }, 3000)

      setTimeout(() => clearInterval(pollInterval), 120000) // 2 min timeout
    } catch (error) {
      console.error("[v0] Error generating post:", error)
      setFeedPosts((prev) => prev.map((p, i) => (i === postIndex ? { ...p, status: "error" as const } : p)))
    }
  }

  const handleBrandWizardComplete = () => {
    console.log("[v0] Brand wizard completed, reloading brand profile...")
    setShowBrandWizard(false)
    loadBrandProfile()
  }

  // Function to handle the completion of the Feed Wizard
  const handleWizardComplete = (data: any) => {
    // REMOVED: setShowWizard(false)
    const wizardPrompt = `Create my Instagram feed strategy. I'm a ${data.businessType} targeting ${data.targetAudience}. My brand vibe is ${data.brandVibe}. My goals are: ${data.goals}`
    sendMessage({ text: wizardPrompt })
  }

  const handleAddHighlight = () => {
    setProfile((prev) => ({
      ...prev,
      highlights: [...prev.highlights, { title: "", coverUrl: "generating", description: "", type: "image" }],
    }))
    setEditingHighlights(true)
  }

  const handleUpdateHighlight = async (
    index: number,
    data: { title: string; coverUrl: string; description: string; type: "image" | "color" },
  ) => {
    setProfile((prev) => ({
      ...prev,
      highlights: prev.highlights.map((h, i) =>
        i === index
          ? { title: data.title, coverUrl: data.coverUrl, description: data.description, type: data.type }
          : h,
      ),
    }))

    if (feedUrl) {
      const feedId = feedUrl.split("/").pop()
      if (feedId) {
        try {
          const updatedHighlights = profile.highlights.map((h, i) =>
            i === index
              ? { title: data.title, coverUrl: data.coverUrl, description: data.description, type: data.type }
              : h,
          )

          console.log("[v0] Saving highlight to database:", { index, coverUrl: data.coverUrl })

          await fetch(`/api/feed/${feedId}/highlights`, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ highlights: updatedHighlights }),
          })

          console.log("[v0] Highlight saved successfully")
        } catch (error) {
          console.error("[v0] Error saving highlights:", error)
        }
      }
    }
  }

  const handleRemoveHighlight = (index: number) => {
    setProfile((prev) => ({
      ...prev,
      highlights: prev.highlights.filter((_, i) => i !== index),
    }))
  }

  useEffect(() => {
    loadChat()
  }, [])

  useEffect(() => {
    if (!chatId || isTyping) return

    const lastMessage = messages[messages.length - 1]
    if (!lastMessage || lastMessage.role !== "assistant") return
    if (savedMessageIds.current.has(lastMessage.id)) return

    const textParts = lastMessage.parts?.filter((p: any) => p.type === "text") || []
    const textContent = textParts
      .map((p: any) => p.text)
      .join("\n")
      .trim()

    if (!textContent) return

    savedMessageIds.current.add(lastMessage.id)

    fetch("/api/maya/save-message", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        chatId,
        role: lastMessage.role,
        content: textContent,
      }),
    })
      .then((res) => res.json())
      .then((data) => {
        if (!data.success) {
          savedMessageIds.current.delete(lastMessage.id)
        }
      })
      .catch(() => {
        savedMessageIds.current.delete(lastMessage.id)
      })
  }, [messages, chatId, isTyping])

  const loadChat = async (specificChatId?: number) => {
    try {
      setIsLoadingChat(true)
      const url = specificChatId
        ? `/api/maya/load-chat?chatId=${specificChatId}&chatType=feed-designer`
        : "/api/maya/load-chat?chatType=feed-designer"
      const response = await fetch(url)
      if (response.ok) {
        const data = await response.json()
        setChatId(data.chatId)

        if (data.messages && Array.isArray(data.messages) && data.messages.length > 0) {
          setMessages(data.messages)
        } else {
          setMessages([])
        }

        setShowHistory(false)
      }
    } catch (error) {
      console.error("[v0] Error loading chat:", error)
    } finally {
      setIsLoadingChat(false)
    }
  }

  const handleNewChat = async () => {
    try {
      const response = await fetch("/api/maya/new-chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ chatType: "feed-designer" }),
      })

      if (response.ok) {
        const data = await response.json()
        setChatId(data.chatId)
        savedMessageIds.current.clear()
        setMessages([])
        setShowHistory(false)
      }
    } catch (error) {
      console.error("[v0] Error creating new chat:", error)
    }
  }

  const handleSelectChat = (selectedChatId: number) => {
    if (selectedChatId !== chatId) {
      setChatId(selectedChatId)
      setMessages([])
      savedMessageIds.current.clear()
      loadChat(selectedChatId)
    }
  }

  if (isInitializing || isLoadingChat) {
    return (
      <div className="h-full flex items-center justify-center bg-stone-50">
        <div className="text-center">
          <div className="w-12 h-12 border-4 border-stone-950 border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
          <p className="text-sm text-stone-600">Loading feed designer...</p>
        </div>
      </div>
    )
  }

  const handleGenerateNewFeed = () => {
    setShowNewFeedModal(false)
    setMayaThinking("Starting fresh with a new feed strategy...")

    // Reset feed state
    setFeedPosts([])
    setFeedStrategy(null)
    setProactiveSuggestions([])
    setIsProfileGenerated(false)
    setHasShownSuggestions(false)

    // Wait a moment for the thinking message to show
    setTimeout(() => {
      setMayaThinking("Analyzing your brand profile...")

      setTimeout(() => {
        setMayaThinking("Crafting your perfect Instagram strategy...")

        // Trigger Maya to generate new feed
        const autoPrompt = `Create a completely new Instagram feed strategy based on my brand profile. Give me fresh creative direction.`
        sendMessage({ text: autoPrompt })
      }, 1000)
    }, 1000)
  }

  return (
    <div className="h-full flex flex-col bg-stone-50">
      {showBrandWizard && !brandCompleted && (
        <BrandProfileWizard
          isOpen={showBrandWizard}
          onClose={() => setShowBrandWizard(false)}
          onComplete={handleBrandWizardComplete}
          existingData={brandData}
        />
      )}

      {showNewFeedModal && (
        <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl shadow-2xl max-w-md w-full p-6">
            <h3 className="font-['Times_New_Roman'] text-2xl font-extralight tracking-[0.2em] uppercase text-stone-950 mb-4">
              GENERATE NEW FEED?
            </h3>
            <p className="text-sm text-stone-700 leading-relaxed mb-6">
              This will replace your current feed with a completely new strategy. Your existing posts and concepts will
              be cleared.
            </p>
            <div className="flex gap-3">
              <button
                onClick={() => setShowNewFeedModal(false)}
                className="flex-1 px-6 py-3 bg-stone-100 hover:bg-stone-200 rounded-lg text-sm font-medium tracking-wider uppercase text-stone-950 transition-all"
              >
                CANCEL
              </button>
              <button
                onClick={handleGenerateNewFeed}
                className="flex-1 px-6 py-3 bg-stone-950 hover:bg-stone-800 rounded-lg text-sm font-medium tracking-wider uppercase text-white transition-all"
              >
                CONTINUE
              </button>
            </div>
          </div>
        </div>
      )}

      <div className="flex-1 flex overflow-hidden">
        <div className="flex-1 flex flex-col bg-stone-50 overflow-hidden">
          {(isDesigning || isApplyingDesign || mayaThinking) && (
            <div className="absolute inset-0 bg-white/80 backdrop-blur-sm z-50 flex items-center justify-center">
              <div className="text-center max-w-md px-6">
                <div className="w-16 h-16 mx-auto mb-6 relative">
                  <div className="absolute inset-0 rounded-full bg-stone-200/20 animate-ping"></div>
                  <div className="relative w-16 h-16 rounded-full overflow-hidden border-2 border-stone-200">
                    <img
                      src="https://i.postimg.cc/fTtCnzZv/out-1-22.png"
                      alt="Maya"
                      className="w-full h-full object-cover"
                    />
                  </div>
                </div>
                <p className="text-base font-normal text-stone-950 mb-2">
                  {mayaThinking || (isDesigning ? "Designing your feed..." : "Applying design...")}
                </p>
                <p className="text-sm text-stone-600 leading-relaxed">
                  {mayaThinking
                    ? "This will just take a moment"
                    : isDesigning
                      ? "Creating a strategic 9-post layout tailored to your brand"
                      : "Your feed strategy is being loaded"}
                </p>
              </div>
            </div>
          )}

          <div className="flex-shrink-0 bg-white border-b border-stone-200 px-6 py-3">
            <div className="flex items-center justify-between max-w-4xl mx-auto">
              <h2 className="font-['Times_New_Roman'] text-xl font-extralight tracking-[0.2em] uppercase text-stone-950">
                INSTAGRAM FEED DESIGNER
              </h2>
              <div className="flex items-center gap-2">
                {feedPosts.length > 0 && (
                  <button
                    onClick={() => setShowNewFeedModal(true)}
                    disabled={isDesigning || isApplyingDesign}
                    className="px-4 py-2 rounded-lg text-xs font-medium tracking-wider uppercase transition-all bg-stone-950 text-white hover:bg-stone-800 disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    NEW FEED
                  </button>
                )}
                <button
                  onClick={() => setShowAnalytics(!showAnalytics)}
                  className={`px-4 py-2 rounded-lg text-xs font-medium tracking-wider uppercase transition-all ${
                    showAnalytics ? "bg-stone-950 text-white" : "bg-stone-100 text-stone-600 hover:bg-stone-200"
                  }`}
                >
                  ANALYTICS
                </button>
                <button
                  onClick={() => setShowHashtags(!showHashtags)}
                  className={`px-4 py-2 rounded-lg text-xs font-medium tracking-wider uppercase transition-all ${
                    showHashtags ? "bg-stone-950 text-white" : "bg-stone-100 text-stone-600 hover:bg-stone-200"
                  }`}
                >
                  HASHTAGS
                </button>
              </div>
            </div>
          </div>

          <div className="flex-1 overflow-y-auto">
            <div className="max-w-4xl mx-auto p-6">
              <div className="bg-white rounded-xl border border-stone-200 overflow-hidden mb-6">
                {/* Profile Header */}
                <div className="p-6 border-b border-stone-200">
                  <div className="flex items-start gap-6 mb-6">
                    <div className="relative group flex-shrink-0">
                      {!isProfileGenerated && !isGeneratingProfile && profile.profileImage.includes("placeholder") ? (
                        <button
                          onClick={handleGenerateProfileImage}
                          className="w-24 h-24 rounded-full overflow-hidden border-2 border-dashed border-stone-300 bg-stone-50 flex flex-col items-center justify-center hover:border-stone-400 hover:bg-stone-100 transition-all"
                        >
                          <span className="text-xs font-medium text-stone-600 text-center px-2">Generate Profile</span>
                        </button>
                      ) : isGeneratingProfile ? (
                        <div className="w-24 h-24 rounded-full overflow-hidden border-2 border-stone-200 bg-stone-100 flex items-center justify-center">
                          <div className="relative w-12 h-12">
                            <div className="absolute inset-0 rounded-full bg-stone-200/20 animate-ping"></div>
                            <div className="relative w-12 h-12 rounded-full bg-stone-950 animate-spin border-4 border-transparent border-t-white"></div>
                          </div>
                        </div>
                      ) : (
                        <>
                          <div className="w-24 h-24 rounded-full overflow-hidden border-2 border-stone-200">
                            <img
                              src={profile.profileImage || "/placeholder.svg"}
                              alt={profile.name}
                              className="w-full h-full object-cover"
                            />
                          </div>
                          <div className="absolute inset-0 rounded-full bg-stone-950/0 group-hover:bg-stone-950/60 transition-all duration-300 flex items-center justify-center opacity-0 group-hover:opacity-100">
                            <button
                              onClick={handleGenerateProfileImage}
                              className="p-3 bg-white/90 backdrop-blur-xl rounded-full hover:bg-white transition-all hover:scale-110"
                              title="Regenerate Profile Image"
                            >
                              <RefreshCw size={16} className="text-stone-950" strokeWidth={2} />
                            </button>
                          </div>
                        </>
                      )}
                    </div>

                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-4 mb-4">
                        <h2 className="text-xl font-normal text-stone-950">{profile.handle}</h2>
                        <button className="px-4 py-1.5 bg-stone-100 hover:bg-stone-200 rounded-lg text-sm font-medium text-stone-950 transition-all">
                          Edit profile
                        </button>
                      </div>

                      {/* Stats */}
                      <div className="flex items-center gap-6 mb-4">
                        <div className="text-center">
                          <div className="text-sm font-semibold text-stone-950">{feedPosts.length}</div>
                          <div className="text-xs text-stone-500">posts</div>
                        </div>
                        <div className="text-center">
                          <div className="text-sm font-semibold text-stone-950">1,234</div>
                          <div className="text-xs text-stone-500">followers</div>
                        </div>
                        <div className="text-center">
                          <div className="text-sm font-semibold text-stone-950">567</div>
                          <div className="text-xs text-stone-500">following</div>
                        </div>
                      </div>

                      <div>
                        <div className="text-sm font-semibold text-stone-950 mb-1">{profile.name}</div>
                        {!isEditingBio ? (
                          <div
                            onClick={() => setIsEditingBio(true)}
                            className="text-sm text-stone-700 leading-relaxed whitespace-pre-wrap cursor-text hover:bg-stone-50 rounded px-2 py-1 -mx-2 -my-1 transition-all"
                            title="Click to edit bio"
                          >
                            {profile.bio}
                          </div>
                        ) : (
                          <div className="space-y-2">
                            <Textarea
                              value={bioValue}
                              onChange={(e) => setBioValue(e.target.value)}
                              className="text-sm resize-none bg-white border-stone-300 focus:border-stone-950"
                              rows={3}
                              maxLength={150}
                              placeholder="Write your bio..."
                            />
                            <div className="flex items-center justify-between">
                              <span className="text-xs text-stone-500">{bioValue.length}/150</span>
                              <div className="flex gap-2">
                                <button
                                  onClick={handleCancelBio}
                                  disabled={isSavingBio}
                                  className="px-3 py-1.5 text-xs font-medium text-stone-600 hover:text-stone-950 transition-all disabled:opacity-50"
                                >
                                  Cancel
                                </button>
                                <button
                                  onClick={handleSaveBio}
                                  disabled={isSavingBio || bioValue === profile.bio}
                                  className="px-3 py-1.5 bg-stone-950 hover:bg-stone-800 text-white text-xs font-medium rounded-lg transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                                >
                                  {isSavingBio ? "Saving..." : "Save"}
                                </button>
                              </div>
                            </div>
                          </div>
                        )}
                      </div>
                      {profileError && <p className="text-xs text-red-600 mt-2">{profileError}</p>}
                    </div>
                  </div>

                  {/* Story Highlights */}
                  <div className="flex items-center gap-4 overflow-x-auto pb-2">
                    {profile.highlights.map((highlight, index) => (
                      <StoryHighlightCard
                        key={index}
                        highlight={highlight}
                        index={index}
                        onUpdate={handleUpdateHighlight}
                        onRemove={handleRemoveHighlight}
                        userColorTheme={brandData?.colorTheme}
                        feedId={feedUrl?.split("/").pop()}
                        isEditing={editingHighlights}
                      />
                    ))}

                    {(editingHighlights || profile.highlights.length === 0) && profile.highlights.length < 10 && (
                      <button
                        onClick={handleAddHighlight}
                        className="flex flex-col items-center gap-2 flex-shrink-0 w-[80px] group"
                      >
                        <div className="w-16 h-16 rounded-full bg-stone-100 border-2 border-dashed border-stone-300 flex items-center justify-center group-hover:border-stone-400 group-hover:bg-stone-50 transition-all">
                          <span className="text-2xl text-stone-400 group-hover:text-stone-600">+</span>
                        </div>
                        <span className="text-xs text-stone-400 group-hover:text-stone-600">New</span>
                      </button>
                    )}
                  </div>
                </div>

                <div className="grid grid-cols-3 gap-1 bg-stone-100">
                  {feedPosts.map((post) => {
                    const feedId = feedUrl?.split("/").pop()

                    return (
                      <div key={post.id} className="aspect-[3/4] bg-stone-100 relative group">
                        {isDesigning && !post.title && (
                          <div className="absolute inset-0 bg-gradient-to-br from-stone-200 to-stone-300 animate-pulse">
                            <div className="absolute inset-0 flex items-center justify-center">
                              <div className="text-center">
                                <div className="w-8 h-8 border-2 border-stone-400 border-t-transparent rounded-full animate-spin mx-auto mb-2"></div>
                                <span className="text-xs text-stone-500">Designing...</span>
                              </div>
                            </div>
                          </div>
                        )}

                        {!isDesigning && post.status === "concept" && !post.title && (
                          <div className="absolute inset-0 flex items-center justify-center bg-stone-50">
                            <span className="text-stone-400 text-sm">{post.position + 1}</span>
                          </div>
                        )}

                        {post.title && feedId && (
                          <div className="absolute inset-0">
                            <FeedPostCard
                              post={{
                                id: post.id,
                                position: post.position,
                                post_type: post.category,
                                prompt: post.prompt,
                                caption: post.caption || "",
                                image_url: post.imageUrl,
                                generation_status:
                                  post.status === "ready"
                                    ? "completed"
                                    : post.status === "generating"
                                      ? "generating"
                                      : "pending",
                                prediction_id: null,
                              }}
                              feedId={feedId}
                              onGenerated={() => loadLatestFeed()}
                            />
                          </div>
                        )}
                      </div>
                    )
                  })}
                </div>
              </div>

              {/* Side Panels */}
              {(showAnalytics || showHashtags) && (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
                  {showAnalytics && <FeedAnalyticsPanel feedStrategy={feedStrategy} />}
                  {showHashtags && <HashtagStrategyPanel businessType={brandData?.businessType} />}
                </div>
              )}

              {/* Action Buttons */}
              {feedPosts.some((p) => p.status === "ready") && (
                <div className="flex gap-3 justify-center">
                  {feedUrl && (
                    <Button
                      onClick={() => window.open(feedUrl, "_blank")}
                      className="bg-stone-950 hover:bg-stone-800 text-white px-8 py-3 text-sm font-medium tracking-wider uppercase"
                    >
                      VIEW FULL FEED
                    </Button>
                  )}
                  <Button
                    onClick={downloadFeed}
                    variant="outline"
                    className="border-stone-300 bg-transparent px-8 py-3 text-sm font-medium tracking-wider uppercase"
                  >
                    DOWNLOAD ZIP
                  </Button>
                </div>
              )}

              {/* Error Messages */}
              {generationError && (
                <div className="bg-red-50 border border-red-200 rounded-xl p-4 mb-6">
                  <div className="flex items-start gap-3">
                    <div className="flex-1">
                      <p className="text-sm font-medium text-red-950 mb-1">Generation Error</p>
                      <p className="text-sm text-red-700">{generationError}</p>
                    </div>
                    <button
                      onClick={() => setGenerationError(null)}
                      className="text-red-400 hover:text-red-600 text-xl leading-none"
                    >
                      ×
                    </button>
                  </div>
                </div>
              )}

              {!hasTrainedModel && (
                <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 mb-6">
                  <div className="flex items-start gap-3">
                    <div className="flex-1">
                      <p className="text-sm font-medium text-amber-950 mb-1">Training Required</p>
                      <p className="text-sm text-amber-700 mb-3">
                        You need to train your personal model before generating feed images.
                      </p>
                      <Button
                        onClick={() => (window.location.href = "/?tab=studio")}
                        className="bg-amber-950 hover:bg-amber-800 text-white"
                      >
                        Go to Studio
                      </Button>
                    </div>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>

      {proactiveSuggestions.length > 0 && !isDesigning && !isApplyingDesign && (
        <div className="fixed bottom-24 right-6 bg-white rounded-2xl shadow-2xl border border-stone-200 p-4 max-w-sm z-40 animate-in slide-in-from-bottom-4">
          <div className="flex items-start gap-3 mb-3">
            <div className="w-10 h-10 rounded-full overflow-hidden border-2 border-stone-200 flex-shrink-0">
              <img src="https://i.postimg.cc/fTtCnzZv/out-1-22.png" alt="Maya" className="w-full h-full object-cover" />
            </div>
            <div className="flex-1">
              <h4 className="text-sm font-semibold text-stone-950 mb-1">Your feed looks great!</h4>
              <p className="text-xs text-stone-600 mb-3">Want me to refine anything?</p>
              <div className="space-y-2">
                {proactiveSuggestions.map((suggestion, index) => (
                  <button
                    key={index}
                    onClick={() => {
                      handleQuickPrompt(suggestion)
                      setIsChatOpen(true)
                    }}
                    className="w-full text-left px-3 py-2 bg-stone-50 hover:bg-stone-100 rounded-lg text-xs text-stone-700 transition-all border border-stone-200"
                  >
                    {suggestion}
                  </button>
                ))}
              </div>
            </div>
            <button
              onClick={() => setProactiveSuggestions([])}
              className="text-stone-400 hover:text-stone-600 flex-shrink-0"
            >
              <X size={16} />
            </button>
          </div>
        </div>
      )}

      {!isChatOpen && (
        <button
          onClick={() => setIsChatOpen(true)}
          className="fixed bottom-6 right-6 w-16 h-16 bg-stone-950 hover:bg-stone-800 text-white rounded-full shadow-2xl flex items-center justify-center transition-all z-40 group"
        >
          <MessageCircle size={28} className="group-hover:scale-110 transition-transform" />
          {(messages.length === 0 || proactiveSuggestions.length > 0) && (
            <div className="absolute -top-1 -right-1 w-4 h-4 bg-red-500 rounded-full animate-pulse"></div>
          )}
        </button>
      )}

      {isChatOpen && (
        <div
          className={`fixed bottom-6 right-6 bg-white rounded-2xl shadow-2xl border border-stone-200 z-50 transition-all ${
            isChatMinimized ? "w-80 h-16" : "w-96 h-[600px]"
          }`}
        >
          {/* Chat Header */}
          <div className="flex-shrink-0 border-b border-stone-200 p-4 bg-stone-50 rounded-t-2xl">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-full overflow-hidden border-2 border-stone-200">
                  <img
                    src="https://i.postimg.cc/fTtCnzZv/out-1-22.png"
                    alt="Maya"
                    className="w-full h-full object-cover"
                  />
                </div>
                {!isChatMinimized && (
                  <div>
                    <h3 className="text-sm font-bold text-stone-950">Maya</h3>
                    <p className="text-xs text-stone-500">Instagram Strategist</p>
                  </div>
                )}
              </div>

              <div className="flex items-center gap-2">
                {!isChatMinimized && (
                  <>
                    <button
                      onClick={() => setShowHistory(!showHistory)}
                      className="p-2 rounded-lg hover:bg-stone-200 transition-all"
                      title="Chat history"
                    >
                      <History size={16} />
                    </button>
                    <button
                      onClick={handleNewChat}
                      className="p-2 rounded-lg hover:bg-stone-200 transition-all"
                      title="New chat"
                    >
                      <Plus size={16} />
                    </button>
                  </>
                )}
                <button
                  onClick={() => setIsChatMinimized(!isChatMinimized)}
                  className="p-2 rounded-lg hover:bg-stone-200 transition-all"
                  title={isChatMinimized ? "Expand" : "Minimize"}
                >
                  <Minimize2 size={16} />
                </button>
                <button
                  onClick={() => setIsChatOpen(false)}
                  className="p-2 rounded-lg hover:bg-stone-200 transition-all"
                  title="Close"
                >
                  <X size={16} />
                </button>
              </div>
            </div>
          </div>

          {!isChatMinimized && (
            <>
              {showHistory && (
                <div className="flex-shrink-0 border-b border-stone-200 p-4 bg-stone-50 max-h-48 overflow-y-auto">
                  <MayaChatHistory currentChatId={chatId} onSelectChat={handleSelectChat} onNewChat={handleNewChat} />
                </div>
              )}

              {/* Chat Messages */}
              <div className="flex-1 overflow-y-auto p-4 space-y-4 h-[400px]">
                {messages.length === 0 && !isTyping && !brandCompleted && (
                  <div className="flex flex-col items-center justify-center h-full px-4 py-8">
                    <div className="w-16 h-16 rounded-full overflow-hidden border-2 border-stone-200 mb-4">
                      <img
                        src="https://i.postimg.cc/fTtCnzZv/out-1-22.png"
                        alt="Maya"
                        className="w-full h-full object-cover"
                      />
                    </div>
                    <h3 className="text-lg font-bold text-stone-950 mb-2 text-center">Let's Start with Your Brand</h3>
                    <p className="text-xs text-stone-600 text-center mb-4 leading-relaxed">
                      I'll create your perfect Instagram feed once I understand your brand story
                    </p>
                    <Button
                      onClick={() => setShowBrandWizard(true)}
                      className="bg-stone-950 hover:bg-stone-800 text-white text-sm"
                    >
                      Complete Brand Profile
                    </Button>
                  </div>
                )}

                {messages.length === 0 && !isTyping && brandCompleted && !hasAutoGenerated && (
                  <div className="flex flex-col items-center justify-center h-full px-4 py-8">
                    <div className="w-16 h-16 rounded-full overflow-hidden border-2 border-stone-200 mb-4">
                      <img
                        src="https://i.postimg.cc/fTtCnzZv/out-1-22.png"
                        alt="Maya"
                        className="w-full h-full object-cover"
                      />
                    </div>
                    <h3 className="text-lg font-bold text-stone-950 mb-2 text-center">Ready to Design Your Feed?</h3>
                    <p className="text-xs text-stone-600 text-center mb-4 leading-relaxed">
                      I'll create a strategic 9-post feed based on your brand profile
                    </p>

                    <Button
                      onClick={() => handleQuickPrompt("Create my Instagram feed strategy based on my brand profile.")}
                      className="bg-stone-950 hover:bg-stone-800 text-white text-sm mb-3"
                    >
                      Generate My Feed
                    </Button>

                    <div className="text-xs text-stone-500 mb-3">or ask me about</div>

                    <div className="grid grid-cols-2 gap-2 w-full">
                      {currentPrompts.slice(0, 4).map((item, index) => (
                        <button
                          key={index}
                          onClick={() => handleQuickPrompt(item.prompt)}
                          className="px-2 py-2 bg-stone-50 border border-stone-200 rounded-lg hover:bg-stone-100 transition-all text-center"
                        >
                          <span className="text-xs font-medium text-stone-700">{item.label}</span>
                        </button>
                      ))}
                    </div>
                  </div>
                )}

                {messages.map((message, index) => (
                  <div
                    key={index}
                    className={`flex gap-2 ${message.role === "user" ? "justify-end" : "justify-start"}`}
                  >
                    {message.role === "assistant" && (
                      <div className="flex-shrink-0 w-7 h-7 rounded-full overflow-hidden border-2 border-stone-200">
                        <img
                          src="https://i.postimg.cc/fTtCnzZv/out-1-22.png"
                          alt="Maya"
                          className="w-full h-full object-cover"
                        />
                      </div>
                    )}
                    <div className={`max-w-[75%] ${message.role === "user" ? "order-2" : "order-1"}`}>
                      {message.parts &&
                        Array.isArray(message.parts) &&
                        message.parts.map((part, partIndex) => {
                          if (part.type === "text") {
                            return (
                              <div
                                key={partIndex}
                                className={`rounded-2xl px-3 py-2 ${
                                  message.role === "user" ? "bg-stone-950 text-white" : "bg-stone-100 text-stone-950"
                                }`}
                              >
                                <p className="text-xs leading-relaxed whitespace-pre-wrap">{part.text}</p>
                              </div>
                            )
                          }
                          return null
                        })}
                    </div>
                  </div>
                ))}

                {isTyping && (
                  <div className="flex justify-start gap-2">
                    <div className="flex-shrink-0 w-7 h-7 rounded-full overflow-hidden border-2 border-stone-200">
                      <img
                        src="https://i.postimg.cos/fTtCnzZv/out-1-22.png"
                        alt="Maya"
                        className="w-full h-full object-cover"
                      />
                    </div>
                    <div className="bg-stone-100 rounded-2xl px-3 py-2">
                      <div className="flex gap-1">
                        <div className="w-2 h-2 rounded-full animate-bounce bg-stone-700"></div>
                        <div
                          className="w-2 h-2 rounded-full animate-bounce bg-stone-700"
                          style={{ animationDelay: "0.2s" }}
                        ></div>
                        <div
                          className="w-2 h-2 rounded-full animate-bounce bg-stone-700"
                          style={{ animationDelay: "0.4s" }}
                        ></div>
                      </div>
                    </div>
                  </div>
                )}
                <div ref={messagesEndRef} />
              </div>

              {/* Chat Input */}
              <div className="flex-shrink-0 border-t border-stone-200 p-3">
                <div className="flex gap-2">
                  <Textarea
                    value={inputValue}
                    onChange={(e) => setInputValue(e.target.value)}
                    placeholder="Ask Maya..."
                    className="flex-1 resize-none bg-stone-50 border-stone-200 text-sm"
                    rows={2}
                    disabled={isTyping}
                    onKeyDown={(e) => {
                      if (e.key === "Enter" && !e.shiftKey) {
                        e.preventDefault()
                        handleSendMessage()
                      }
                    }}
                  />
                  <Button
                    onClick={handleSendMessage}
                    disabled={isTyping || !inputValue?.trim()}
                    className="bg-stone-950 hover:bg-stone-800 text-white self-end px-4 text-sm"
                  >
                    Send
                  </Button>
                </div>
              </div>
            </>
          )}
        </div>
      )}
    </div>
  )
}
