-- Scene Composer table - stores scene compositions and results
CREATE TABLE IF NOT EXISTS scene_composer_scenes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  
  -- Base image from user's gallery
  base_image_id VARCHAR(50), -- e.g., "ai_12345" from ai_images table
  base_image_url TEXT NOT NULL,
  
  -- Product/prop images uploaded for this scene
  product_images JSONB DEFAULT '[]', -- [{url, label, upload_order}]
  
  -- User's scene request
  user_request TEXT NOT NULL,
  
  -- Maya's scene concept (like concept cards)
  scene_title VARCHAR(255) NOT NULL,
  scene_description TEXT NOT NULL,
  maya_technical_prompt TEXT NOT NULL, -- Optimized prompt for Nano Banana Pro
  
  -- Generation settings
  aspect_ratio VARCHAR(10) DEFAULT '9:16',
  resolution VARCHAR(10) DEFAULT '1K', -- '1K', '2K', '4K'
  
  -- Nano Banana Pro generation
  prediction_id VARCHAR(255),
  generated_image_urls TEXT[],
  generation_status VARCHAR(50) DEFAULT 'pending', -- 'pending', 'processing', 'completed', 'failed'
  error_message TEXT,
  
  -- Timestamps
  created_at TIMESTAMP DEFAULT NOW(),
  completed_at TIMESTAMP,
  
  -- Metadata
  credits_used INTEGER DEFAULT 3,
  source VARCHAR(50) DEFAULT 'scene_composer'
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_scene_composer_user_id ON scene_composer_scenes(user_id);
CREATE INDEX IF NOT EXISTS idx_scene_composer_status ON scene_composer_scenes(generation_status);
CREATE INDEX IF NOT EXISTS idx_scene_composer_created ON scene_composer_scenes(created_at DESC);

-- RLS Policy (matches existing pattern)
ALTER TABLE scene_composer_scenes ENABLE ROW LEVEL SECURITY;

CREATE POLICY scene_composer_user_policy ON scene_composer_scenes
  FOR ALL USING (user_id = app_current_user_id() OR app_is_admin());

-- Comments
COMMENT ON TABLE scene_composer_scenes IS 'Scene Composer: Professional brand scenes with products/props using Nano Banana Pro';
COMMENT ON COLUMN scene_composer_scenes.base_image_id IS 'Reference to ai_images table (format: ai_12345)';
COMMENT ON COLUMN scene_composer_scenes.product_images IS 'Array of {url, label, upload_order} for products/props';
COMMENT ON COLUMN scene_composer_scenes.maya_technical_prompt IS 'Optimized Nano Banana Pro prompt generated by Maya';
