-- Seed Sandra's Personal Story
-- This gives agents context about YOU personally, not just SSELFIE the product

INSERT INTO admin_personal_story (story_type, title, content, timeframe, emotional_tone, key_themes, display_order) VALUES
(
  'origin',
  'Why I Built SSELFIE',
  'I started SSELFIE because I saw creative entrepreneurs struggling with the same problem I had - we knew our business inside and out, but creating consistent, professional content felt impossible. I was tired of spending hours trying to get the "perfect selfie" for Instagram, only to post nothing at all. I realized AI could change this - not by replacing our creativity, but by amplifying it. SSELFIE is my mission to help every entrepreneur show up confidently in their content.',
  '2023-2024',
  'inspiring',
  ARRAY['entrepreneurship', 'problem_solving', 'AI_for_good'],
  1
),
(
  'journey',
  'Building in Public',
  'I''m learning as I go, and I''m not afraid to share that journey. Some days I''m excited about new features, other days I''m troubleshooting bugs at midnight. I believe in transparency - my users see the messy middle, not just the highlight reel. That''s what makes SSELFIE different. We''re building this together.',
  '2024-Present',
  'vulnerable',
  ARRAY['transparency', 'learning', 'community'],
  2
),
(
  'values',
  'My Core Values',
  'Authenticity over perfection. Progress over perfection. Community over competition. I believe technology should empower, not intimidate. I believe entrepreneurs deserve tools that work as hard as they do. And I believe showing up is better than staying silent.',
  'Always',
  'confident',
  ARRAY['authenticity', 'progress', 'empowerment'],
  3
),
(
  'daily_life',
  'Behind the Scenes',
  'My day usually starts with coffee and checking user feedback. I love hearing what''s working and what''s not. I''m constantly thinking about how to make SSELFIE better - whether I''m in a meeting, working out, or just scrolling Instagram. Ideas hit me at the weirdest times, and my Notes app is full of random thoughts at 2am.',
  '2024',
  'real',
  ARRAY['work_life', 'dedication', 'user_focused'],
  4
),
(
  'struggles',
  'The Hard Parts',
  'Building a startup is lonely sometimes. There are moments of doubt - am I building the right thing? Is this feature too complicated? Why isn''t growth happening faster? But then a user sends me a message saying SSELFIE changed their content game, and I remember why I''m doing this. Every struggle teaches me something.',
  '2024',
  'vulnerable',
  ARRAY['entrepreneurship', 'doubt', 'resilience'],
  5
),
(
  'wins',
  'Celebrating Milestones',
  'Every new beta user feels like a win. Every piece of positive feedback makes my day. When I see someone post a selfie generated by SSELFIE and say they finally feel confident in their content - that''s what it''s all about. We''re still early, but we''re making progress every single day.',
  '2024',
  'celebratory',
  ARRAY['growth', 'impact', 'gratitude'],
  6
);

-- Add some example writing samples (you can add your actual emails/captions later)
INSERT INTO admin_writing_samples (content_type, sample_text, context, tone, performance_score, target_audience, was_successful, is_template) VALUES
(
  'email',
  'Hey there! 👋

Welcome to SSELFIE! I''m Sandra, and I''m so excited you''re here.

I know how overwhelming it can feel to create content consistently - trust me, I''ve been there. That''s exactly why I built SSELFIE.

Over the next few days, I''ll send you some tips to help you get started. But for now, just explore and have fun. There''s no pressure to be perfect.

If you need anything, just hit reply. I read every message.

xo Sandra 💋',
  'Welcome email for new beta users',
  'warm',
  9.5,
  'new_users',
  true,
  true
),
(
  'caption',
  'Real talk: I used to spend HOURS trying to get content ready for Instagram. 

Now? SSELFIE helps me show up confidently in minutes.

If you''re tired of the content struggle, this is for you. 🙌

Link in bio to join the beta 💕',
  'Instagram post announcing beta launch',
  'casual',
  8.0,
  'existing_customers',
  true,
  false
),
(
  'email',
  'Hey! Quick question - how''s your SSELFIE experience going?

I''d love to hear what''s working for you and what could be better. Your feedback literally shapes what we build next.

Just hit reply and let me know. Even if it''s just "it''s great!" or "this one thing is confusing" - I want to hear it all.

xo Sandra 💋',
  'Feedback request email sent after 1 week',
  'conversational',
  9.0,
  'beta_users',
  true,
  true
);

-- Add initial automation rules
INSERT INTO admin_automation_triggers (trigger_event, trigger_condition, automated_action, action_template, is_active) VALUES
(
  'new_user_signup',
  '{"user_plan": "free", "within_hours": 1}',
  'draft_welcome_email',
  'Use the welcome email template for new users. Keep it warm and personal.',
  true
),
(
  'friday_newsletter',
  '{"day_of_week": "Friday", "time": "09:00"}',
  'draft_weekly_newsletter',
  'Create a weekly roundup with: 1) This week''s wins, 2) New features/updates, 3) User spotlight (if applicable), 4) Tip of the week, 5) CTA',
  true
),
(
  'low_engagement_alert',
  '{"user_inactive_days": 7, "had_previous_activity": true}',
  'draft_re_engagement_email',
  'Create a friendly check-in email asking if they need help or have questions. No pressure, just supportive.',
  false
);

COMMENT ON COLUMN admin_writing_samples.sample_text IS 'Sandra''s actual writing that agents can learn from and use as style templates';
COMMENT ON COLUMN admin_agent_feedback.learned_patterns IS 'Extracted patterns like: {"prefers_short_sentences": true, "uses_emoji": "sparingly", "tone_preference": "conversational"}';
