-- RETIRED
--
-- This customer-specific manual repair created a synthetic subscription and bypassed current
-- Stripe payment verification. It is intentionally non-executable. Use the attended subscription
-- reconciliation workflow, backed by a verified Stripe payment, for any future repair.
